:toc:
:toc-placement!:

= Request for feedback: treatment of 510 (Citation/References) and 555 (Cumulative Index/Finding Aids) notes in public catalog

*We initially did NOT include data from the 510 in mappings to Argot. However, we later agreed to do so after strong requests from Special Collections stakeholders*

Kristina Spurgin
2018-02-28

I am proposing that we drop display of the 510 note from the TRLN Discovery public catalog, because:

- it is a difficult field to display properly
- it seems to me to add little to the user's ability to retrieve, identify, or select a resource from the public catalog

If I am wrong about the 2nd point above, we probably need to keep the 510 in the TRLN Discovery catalog. That's what I'm looking for feedback on.

*It seems like the 510 field is mostly used in archival, rare book, and special collections materials, so requests for feedback should be targeted at our colleagues in those areas.*

The 555 field is closely related to the 510 field, so I believe they should be handled consistently. *The 555 seems most heavily used in serials cataloging.*

toc::[]

== 510 vs. 555
As described below, the 510 can be used to record, among other things,  data about other resources that index the resource described by the record.

555 is used when the resource described in the record contains indexes to itself, which may appear in different issues/volumes over time. 

== How is the 510 field handled in Endeca?

- Displayed (in details/full record tab, with label "Notes")
- NOT indexed

*The following applies to UNC only, as I do not know how other institutions are extracting/transforming their MARC*

- The following is prepended to the data in the MARC field for display: "Cited in: "

http://search.trln.org/search?id=UNCb1071561[Here is an example of a UNC book record containing 510s, as it appears in SearchTRLN.]

== How is the 555 field handled in Endeca?
This is unclear to me (or maybe the way data from this field is handled is inconsistent across institutions?)

Endeca data model includes a specific `Cumulative Indexes` field, with the following properties:

- displayed
- not indexed

http://search.trln.org/search?id=UNCb1273347[SearchTRLN] displays it with all the other notes.

http://search.lib.unc.edu/search?R=UNCb1273347[UNC] displays it separately with its own label ("Indexes:).

== Problem with how 510 is handled in Endeca
Depending on the format of the resource described in the rest of the record, the 510 field means something different:

- For books and music, it contains references to published descriptions or reviews of the item
- For continuing resources, it is used to specify publications in which a continuing resource has been indexed and/or abstracted and the dates of coverage, if known.
- For unpublished visual materials, it contains references to published descriptions of the work.
- For a collection of graphic items, it contains references to published descriptions of the collection.
- For projected visual materials, it contains references to reviews of the work described.
- For mixed materials, it contains references to publications in which abstracts, citations, descriptions, or indexes of the described materials have appeared.

So, this one field may include data about:

- description of resource
- review of resource
- index of resource
- abstract of resource

The referenced resource is a different resource from the one represented by the bibliographic record. 

The MARC standard says that one of the following labels should be displayed for the data in this field, depending on the first indicator value:

- Indexed by:
- Indexed in its entirety by:
- Indexed selectively by:
- References:

The first three labels seem ok, if we assume the first indicator values have been coded accurately.

"References:" strikes me as extremely vague and confusing in the context of display to the user. UNC's chosen label "Cited by: " is probably the best we could do here, given that I assume any description, review, or abstract of the described item would indeed cite it.

Nothing in data recorded in the field states the relationship between the referenced resource and the resource described by our catalog record.

== Problem with how 555 is handled in Endeca
Nothing serious, though it seems the shared interface should leverage the separately defined field to usefully label the data.

== My concerns about 510

- Do these notes mean anything to the user?
- If a user knows what this field means and wants to go to the work that cites, references, indexes, or describes the work described in the record, is there enough info in this field to get them there?

If the answer to the above questions is "No," then we should omit this from TRLN Discovery.

If the answer is "Yes," then I need feedback on how people think data from the 510 should be labeled and displayed.

== My concerns about 555

The bib record is an abstract descriptions of the journal as a whole. The data recorded in these fields, as I understand it, doesn't describe the cumulative index volumes *held by UNC or Duke or any other specific library*. It describes the cumulative index volumes that exist anywhere for the journal.

If a user sees `Indexes: Nos. 1-5, 1948-52 in no. 6.` in our catalog:

- do they know what that means? (I confess I actually don't)
- do they find it confusing/frustrating if we don't even have the no. 6 referred to in our holdings? (I think I would)


== 510 examples
=== http://search.trln.org/search?id=UNCb1071561[Book, Davis Library and Rare Book Collection]

- Cited in: BAL 4537
- Cited in: Hubin, A.J. Crime fiction, 1749-1980, p. 109
- Cited in: Queen, E. Queen's quorum, 29
- Cited in: Quinby, H.C. Davis, 23

=== http://search.trln.org/search?id=UNCb1402681[Book, Davis, NCC, Rare Book]

- Cited in: ESTC(RLIN), N66258
- Cited in: ESTC(RLIN), T149673

=== http://search.trln.org/search?id=UNCb1189479[Serial]

- Cited in: America, history and life 0002-7065 1963-1970
- Cited in: Annual bibliography of English language and literature 0066-3786
- Cited in: Historical abstracts. Part A. Modern history abstracts 0363-2717 1963-1970
- Cited in: Historical abstracts. Part B. Twentieth century abstracts 0363-2725 1963-1970

=== http://search.trln.org/search?id=UNCb8714253[DVD]

- Cited in: DDC
- Cited in: DDEB
- Cited in: DDSE
- Cited in: DDSG
- Cited in: DDST
- Cited in: DDW

=== http://search.trln.org/search?id=UNCb2122047[Printed music]

- Cited in: C. Humphries and W.C. Smith. Music publishing in the British Isles, 2nd ed., p. 203.
- Cited in: Catalog of printed music in the British Library to 1980, v. 46, p. 188.

=== http://search.trln.org/search?id=UNCb4677151[Sound recording]

- Cited in: Morgan E75

=== http://search.trln.org/search?id=UNCb1927072[Image]

- Cited in: Theofiles 191.

== 511 examples
=== http://search.trln.org/search?id=UNCb1288170[UNCb1288170]

- V. 1-11; new ser. v. 1-30, 1888-1928 (includes also index to Current anthropological literature and Memoirs of the American Anthropological Association), 1 v.; v. 31-40, 1929-32 (includes also index to Current anthropological literature and Memoirs of the American Anthropological Association), in v. 42; v. 41-50, 1939-48 (includes also index to Memoirs of the American Anthropological Association), 1 v.; v. 51-60, 1949-58 (includes also index to Memoirs of the American Anthropological Association), 1 v.; v. 61-71, 1959-69 (includes also index to Memoirs of the American Anthropological Association), 1 v.

=== http://search.trln.org/search?id=UNCb1283253[UNCb1283253]

- List of contents, v. 1-50, 1948-1997. l v.; list of contents, v. 1-55, 1948-2002. 1 v.

=== http://search.trln.org/search?id=UNCb1288171[UNCb1288171]

- 1812-80. 1 v.; 1880-1903. 1 v.; 1821-1961. 1 v.
