* Requesting: feedback on modeling this pattern in Argot : $i and $3 should display as labels on fields where they occur, but not be indexed

 - Neither $3 nor $i is required in any field -- they are used when necessary (see below for details)
 - $3 defined for use in 77 MARC fields
 - $i defined for use in 29 MARC fields



* subfields i and 3
** subfield 3
  - *ABOUT*
    - $3 is defined across the MARC standard as "Material specified"
    - $3 is *defined for use in 77 MARC tags* and seems to be added to more fields with every MARC update
    - $3 is used when the data recorded in the field applies to/describes only part of the overall resource described by the record
    - The part(s) to which the field applies are specified in $3
    - There is no clear standard policy or practice for $3's location in a MARC field -- some catalogers prefer to put it first; some put it at the end of the field
  - *DISPLAY*
    - $3 is necessary for an accurate/meaningful display, so that we are not implying the data in the field describes/applies to the entire thing described by the record
    - For display, it should appear first, as a qualifying label to the rest of the field.
  - *INDEXING*
    - $3 should NOT be included in any indexes (except for keyword index, and only then if we decide to dump the entire record in that index)

*Examples*

In UNC's catalog, $3 is most heavily used in the 856 field. 856 coding practices remain highly unstandardized across institutions, so I'll give other examples below

For continuing resources where publisher has changed over time, $3 specifies the dates each publisher was active:
#+BEGIN_SRC 
260 3 _ $3<2013->:$aPeterborough, Ontario :$bBaywolf Press
#+END_SRC

Here, the way a series title appeared in the volumes of that series changed over time. $3 is used to specify, for example, that between 1979 and 2004, the series title on the item was "Resource bulletin NC":
#+BEGIN_SRC 
490 1 _ $31965-1978:$aUSDA Forest Service resource bulletin NC
490 1 _ $31979-2004:$aResource bulletin NC
490 1 _ $32005:$aResource bulletin NRS
#+END_SRC

Here, the bib describes the whole box set. The $3 is used to qualify the transcribed series titles/volume info for the set as a whole, and each piece in the set.
#+BEGIN_SRC 
490 1 _ $3Box set:$aCriterion Collection ;$v813
490 1 _ $3Alice in the Cities:$aCriterion collection ;$v814
490 1 _ $3Wrong Move:$aCriterion collection ;$v815
490 1 _ $3Kings of the Road:$aCriterion collection ;$v816
#+END_SRC

518 - Date/Time and Place of an Event Note specifying the recording details for the different works on a recording
#+BEGIN_SRC 
518 _ _ $31st work$orecorded$d2011 December 18$pAmerican Academy of Arts & Letters, New York City.
518 _ _ $32nd-3rd works$orecorded$d2012 June 3-4$pGranoff Music Center, Distler Hall, Tufts University.
518 _ _ $35th work$orecorded$d2009 December 17$pAmerican Academy of Arts & Letters, New York City.
518 _ _ $34th work$orecorded$d2012 September 19-20$pAmerican Academy of Arts & Letters, New York City.
#+END_SRC

** subfield i
  - *ABOUT*
    - $i is *defined for use in 39 MARC tags* and seems to be added to more fields with every MARC update
    - When defined, $i is usually, but not always, called something like: "Display text" or "Relationship information". *HOWEVER*, in some fields, it's something else altogether
    - Because of the inconsistency mentioned in the previous point, there's no simple blanket definition of $i, but *in general* (and for our purposes) it is used in fields that record data about some entity related to the one described by the record. 
    - The $i specifies how that other entity is related to the one being described here. 
    - There is no clear standard policy or practice mandated for $i's location in a MARC field -- however, it is usually put first
  - *DISPLAY*
    - $i (or a modified version of it) is necessary for an accurate/meaningful display.
    - For display, it should appear first, as a qualifying label to the rest of the field.
  - *INDEXING*
    - $i should NOT be included in any indexes (except for keyword index, and only then if we decide to dump the entire record in that index)
    - $i can be leveraged to determine how certain fields should be indexed

*Examples*

The FRBR WEMI terms in parentheses should be stripped out for display, but we could use this to index Shakespeare's Othello as a related work (or Shakespeare as a related author). The work described in this record may be interesting to a user searching for Shakespeare's Othello, but it probably isn't highly relevant. 

Likewise, we use the 787$i to index that work as a "version of" this one---exact titles and details may differ between reproductions but if a user's searching for the original thing, the work described here is much more likely to be relevant. 
#+BEGIN_SRC 
100 	1#$aVerdi, Giuseppe, $d1813-1901.
245 	10$aOthello :$bin full score /$cGiuseppe Verdi.
700 	1#$iLibretto based on (work):$aShakespeare, William,$d1564-1616.$tOtello.
787 	08$iReproduction of (manifestation):$aVerdi, Giuseppe, 1813-1901.$tOtello.$dMilano: Ricordi, c1913
#+END_SRC

** subfield $3 AND $i
 - This happens. Of course it does.
 - It's possible in 10 MARC fields, 5 of which we will definitely need to handle for indexing/display

In these cases: 
 - neither $3 nor $i should be indexed (except for keyword index, if we decide we're dumping the whole record in there)
 - $3 should be displayed before $i, regardless of the order of these fields in the record

From a record describing a recording of multiple works, one of which was based on another work cited in this 700 field: 
#+BEGIN_SRC 
700 1 _ $31st work$iBased on (work):$aKrell, Max,$d1887-1962.$tDämon.
#+END_SRC

From a record describing a book containing multiple works, one of which (Liber gestorum) is an adaptation of the related work cited in the 700:
#+BEGIN_SRC 
700 0 _ $3Liber gestorum$iAdaptation of:$aJames$bI,$cKing of Aragon,$d1208-1276.$tLlibre dels fets.
#+END_SRC
