= Solr queries cheatsheet
== Admin

CSV of all stored field fieldnames in Solr index::
  https://query.discovery.trln.org/trlnbib/select?q=*:*&wt=csv&rows=0&facet
  +
  Stored fields are NOT generally searchable. For most complete list of
  searchable field names, see
  https://github.com/trln/trln-config/blob/master/solr/trlnbib/config/select_edismax.xml[select_edismax.xml].
  The carat (^) followed by number indicates boost score and is NOT part
  of the field name.

[[formatting_results]]
=== Formatting results

Return different formats (default = json)::
  base + query + &wt=xml
  +
  base + query + &wt=csv
  +
  base + query + &wt=ruby _(returns ruby hash)_

Show only specified fields::
  base + query + &fl=fieldname,fieldname

Change number of documents returned::
  base + query + &rows=100

Page through::
  base + query + &start=101

=== Relevance

Show relevance score when displaying full document::
  base + query + &fl=*,score

Show relevance score when displaying selected fields::
  base + query + &fl=fieldname,score

Show relevance explanation::
  include in the &fl parameter: [explain]

Show query debug::
  base + query + &debugQuery=true

=== Export

Export JSON results::
  base + /export? + query +
  https://lucene.apache.org/solr/guide/7_0/exporting-result-sets.html#specifying-the-sort-criteria[sort
  criteria] (up to 4) +
  https://lucene.apache.org/solr/guide/7_0/exporting-result-sets.html#specifying-the-field-list[fields
  to include]
  +
  https://query.discovery.trln.org/trlnbib/export?q=virtual_collection_t:[*%20TO%20*]&uf=*&sort=id+asc&fl=id

All UNC Sierra catalog IDs::
  https://query.discovery.trln.org/trlnbib/export?q=record_data_source_a:ILSMARC+AND+owner_a:unc&uf=*&sort=id+asc&fl=id

All ICPSR record IDs::
  https://query.discovery.trln.org/trlnbib/export?q=record_data_source_a:ICPSR&uf=*&sort=id+asc&fl=id

=== Queries

Get 5 records::
  https://query.discovery.trln.org/trlnbib/select?q=*:*&rows=5

Get specific record by ID::
  https://query.discovery.trln.org/trlnbib/get?id=UNCb1024201

All records that contain a given field (note_cited_in_a)::
  https://query.discovery.trln.org/trlnbib/select?q=note_cited_in_a:[*%20TO%20*]&uf=*

Title main search (245)::
  https://query.discovery.trln.org/trlnbib/select?q=title_main_t:dwarf+goats&uf=*

Search for name in names_creator_t AND included_author_t::
  https://query.discovery.trln.org/trlnbib/select?qf=names_creator_t%20included_author_t&q=shakespeare%2C%20william%2C%201564-1616&uf=*

UNC records with resource type facet value= Government publication::
  https://query.discovery.trln.org/trlnbib/select?q=institution_a:unc+AND+resource_type_a:%22Government%20publication%22&uf=*

Records for titles that are both online and in physical format::
  https://query.discovery.trln.org/trlnbib/select?q=access_type_f:%22At%20the%20Library%22%20AND%20access_type_f:Online%20AND%20owner_a:u
