:toc:
:toc-placement!:

= TRLN Shared Records
This page updates the Endeca-specific http://archive.trln.org/endeca/shared-records-technical-details.html[TRLN Shared Records Program - Technical Details] page for TRLN Discovery.

See http://archive.trln.org/endeca/shared-records.html[TRLN Shared Records Program documentation] for background on the shared records program and details of the shared records collections.

The major difference in shared record set handling in TRLN Discovery is we no longer need to create a separate data pipeline for each shared record set. This greatly lowers the overhead for creating and maintaining a shared record set.

In TRLN Discovery, each institution responsible for a shared record set must ensure their relevant source-data-to-Argot process inserts the required data (specified in detail for each collection below) in all records that are part of shared record sets.

== Argot for shared records
The Argot fields salient to shared records are:

* `institution` - must include each institution for whom the record should appear as though it belongs to them (The Argot owner field will contain the institution responsible for maintaining the record)
* `url[href]` - institution-specific parts of URL (proxy prefix, institution code, etc.) must be templated
* `url[text]` - should not be institution-specific
* `url[restricted]` - must be set to false if the resources in set are freely available
* `items` - institution-specific items must not be attached to shared records, or the host institution's location will start showing up in everyone's location facet
* `holdings` - institution-specific holdings must not be attached to shared records
* `record_data_source` - must include:
** source data type
** "Shared Records"
** shared record set code
* `virtual collection` - must include: "TRLN Shared Records. {Human readable name of shared record set/collection}."

== MARC shared record sets

Data transformation will be handled by MARC-to-Argot.

Each institution responsible for shared records must ensure their MARC-to-Argot config handles shared records appropriately.

This gives the option for shared records to be treated like any other record in the host ILS – handled on the same update schedule, deleted as necessary without complication. (This is notable if you ever had to deal with a shared record set in Endeca!)

=== Alexander Street Press

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20Alexander%20Street%20Press%20videos.%22&uf=*&rows=0[count]

|`owner`
|unc

|`institution`
|['duke', 'unc']

|`url` handling
|`href`: proxy prefix templated

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" labeling should be sent through in the note element. Examples of "materials specified" labels: English version, Spanish version, PDF version, Text file version, v. 271, v. 272, etc.

`restricted`: not set – defaults to true

|`record_data_source`
|['ILSMARC', 'Shared Records', 'ASP']

|`virtual_collection`
|['TRLN Shared Records. Alexander Street Press videos.']
|===

=== Center for Research Libraries E-Resources

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20Center%20for%20Research%20Libraries%20(CRL)%20e-resources.%22&uf=*&rows=0[count]

|`owner`
|unc

|`institution`
|['duke', 'ncsu', 'unc']

|`url` handling
|`href`: proxy prefix templated

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" (856$3) labeling should be sent through in the note element. **This information is particularly important for this set** because it contains records for newspapers and serials where ONLY SOME of the volumes/issues have been digitized. This note will be how users know if the content they are interested in is available.

`restricted`: not set – defaults to true

|`record_data_source`
|['ILSMARC', 'Shared Records', 'CRL']

|`virtual_collection`
|['TRLN Shared Records. Center for Research Libraries (CRL) e-resources.']
|===

=== Documents Without Shelves

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20Documents%20without%20shelves.%22&uf=*&rows=0[count]

|`owner`
|unc

|`institution`
|['duke', 'nccu', 'ncsu', 'unc']

|`url` handling
|`href`: None. Raw URL sent through to Argot.

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" labeling should be sent through in the note element. Examples of "materials specified" labels: English version, Spanish version, PDF version, Text file version, v. 271, v. 272, etc.

`restricted`: false

|`record_data_source`
|['ILSMARC', 'Shared Records', 'DWS']

|`virtual_collection`
|['TRLN Shared Records. Documents without shelves.']
|===

=== Early English Books Online

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20Early%20English%20Books%20Online.%22&uf=*&rows=0[count]

|`owner`
|ncsu

|`institution`
|['duke', 'ncsu', 'unc']

|`url` handling
|`href`: proxy prefix templated

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" labeling should be sent through in the note element. Examples of "materials specified" labels: English version, Spanish version, PDF version, Text file version, v. 271, v. 272, etc.

`restricted`: not set – defaults to true

|`record_data_source`
|['ILSMARC', 'Shared Records', 'EEBO']

|`virtual_collection`
|['TRLN Shared Records. Early English Books Online.']
|===

=== NC LIVE video collection 

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20NC%20LIVE%20videos.%22&uf=*&rows=0[count]

|`owner`
|ncsu

|`institution`
|['duke', 'nccu', 'ncsu', 'unc']

|`url` handling
|`href`: proxy prefix templated

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" labeling should be sent through in the note element. Examples of "materials specified" labels: English version, Spanish version, PDF version, Text file version, v. 271, v. 272, etc.

`restricted`: not set – defaults to true

|`record_data_source`
|['ILSMARC', 'Shared Records', 'NCLIVE']

|`virtual_collection`
|['TRLN Shared Records. NC LIVE videos.']
|===

=== Oxford University Press Ebooks

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20Oxford%20University%20Press%20online%20titles.%22&uf=*&rows=0[count]

|`owner`
|duke

|`institution`
|['duke', 'nccu', 'ncsu', 'unc']

|`url` handling
|`href`: proxy prefix templated

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" labeling should be sent through in the note element. Examples of "materials specified" labels: English version, Spanish version, PDF version, Text file version, v. 271, v. 272, etc.

`restricted`: not set – defaults to true

|`record_data_source`
|['ILSMARC', 'Shared Records', 'OUPE']

|`virtual_collection`
|['TRLN Shared Records. Oxford University Press online titles.']
|===

=== Oxford University Press Print

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20Oxford%20University%20Press%20print%20titles.%22&uf=*&rows=0[count]

|`owner`
|unc

|`institution`
|['duke', 'nccu', 'ncsu', 'unc']

|`url` handling
|None. Print materials should not have fulltext URLs. Any with `type` = `related` will be sent through as usual.

|`record_data_source`
|['ILSMARC', 'Shared Records', 'OUPP']

|`virtual_collection`
|['TRLN Shared Records. Oxford University Press print titles.']
|===

[NOTE]
====
These physical items are stored at the LSC and are assigned a "TRLN" location code in the UNC ILS.

We do **not** set TRLN as part of the location facet hierarchy in these records in TRLN Discovery. They just show up as if they belonged to each institution.
====

== Non-MARC shared record sets

Data transformation will be handled by local institutional processes.

Each institution responsible for shared records must ensure their Argot is output appropriately.

=== Inter-University Consortium for Political and Social Research Datasets

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20ICPSR.%22&uf=*&rows=0[count]

|`owner`
|unc

|`institution`
|['duke', 'ncsu', 'unc']

|`url` handling
|`href`: proxy prefix templated

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" labeling should be sent through in the note element. Examples of "materials specified" labels: English version, Spanish version, PDF version, Text file version, v. 271, v. 272, etc.

`restricted`: not set – defaults to true

URLs with `type`=related are sent through for how to get ICPSR help at each institution. The url['text'] subelement is retained for display at TRLN level when url['type'] = related.

|`record_data_source`
|['DDI-XML', 'Shared Records', 'ICPSR']

|`virtual_collection`
|['TRLN Shared Records. ICPSR.']
|===

=== Statistical Datasets from the Odum Institute Dataverse

[cols=2*]
|===
|record count
|https://query.discovery.trln.org/trlnbib/select?q=virtual_collection_t:%22TRLN%20Shared%20Records.%20Odum%20Institute%20Dataverse.%22&uf=*&rows=0[count]

|`owner`
|unc

|`institution`
|['duke', 'nccu', 'ncsu', 'unc']

|`url` handling
|`href`: no proxy needed

`text`: URL text element values will be overwritten in expand to TRLN mode.

`note`: "Materials specified" labeling should be sent through in the note element. Examples of "materials specified" labels: English version, Spanish version, PDF version, Text file version, v. 271, v. 272, etc.

`restricted`: false
|`record_data_source`
|['OAI DC', 'Shared Records', 'Dataverse']

|`virtual_collection`
|['TRLN Shared Records. Odum Institute Dataverse.']
|===
