:toc:
:toc-placement!:

= MARC 76X-78X linking fields processing patterns

These fields are mapped into Argot's https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_work_entry.adoc[work_entry pattern].

Specific Argot fields that employ this patterns include:

* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/included_work.adoc[included_work]
* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/included_work.adoc[related work]

http://www.loc.gov/marc/bibliographic/bd76x78x.html[MARC specification for this field group]

toc::[]

== Is the field mapped at all?
These fields serve the purpose of providing information about works related to, included in, or including the work described in the overall record. In order to say anything useful to users about these linked works, at the very least, we need to be able to tell them the title of the related thing.

*If a 76X-78X field lacks a title element, it is skipped and not mapped into Argot*, because there's not much useful that we can do with it.

Another reason contributing to this decision is that if the cataloger provided title data without coding it properly in a title subfield, the trustworthiness of the data is, in general, in question.

== `[type]`
Will be set separately for each MARC field in this group.

== `[display]`
=== true if i1=0
Hopefully the data in such a field isn't already recorded elsewhere in the record, and it adds useful info to the display.

Defaults to true, so does not need to be explicitly set.

=== false if i1!=0
==== i1=1
Typically the data in such fields has also been put in a human readable note somewhere else in the record. We don't need to show this info twice, but we can't do anything useful with the info in the note, so we use this more structured data to do some useful indexing.

==== i1!=~/[01]/
Invalid coding. Likely crappy data that wouldn't display right anyway.

== `[label]`

=== General guidelines

A few of the individual fields are treated slightly differently. These differences are highlighted per-field below. Individual field instructions override these general guidelines in the case of conflicts.

==== i2=8 or blank and no $i present
No `[label]` value set. UI display label should provide sufficient context.

==== $i present
Use $i value, following instructions in https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_i.adoc

=== 772

==== i2=0
`label`=> 'Parent item'

=== 773

==== if present, $3 contributes to label
See "When $i as a label occurs in the same field with a $3, they must be combined in the label" section at https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_3.adoc[subfield 3 spec]

=== 775

==== If no $i and $e is present
$e contains language code of alternate language edition. Use default language code lookup (in Traject?) to expand code to name of language. Label is: "#{Language name} language edition"

$efre

'label'=> 'French language edition'

=== 780

[cols=2*,options=header]
|===
|i2
|`label`

|0
|Continues

|1
|Continues in part

|2
|Supersedes

|3
|Supersedes in part

|4
|Formed by the union of

|5
|Absorbed

|6
|Absorbed in part

|7
|Separated from
|===

=== 785

[cols=2*,options=header]
|===
|i2
|`label`

|0
|Continued by

|1
|Continued in part by

|2
|Superseded by

|3
|Superseded in part by

|4
|Absorbed by

|5
|Absorbed in part by

|6
|Split into

|7
|Merged with or into

|8
|Changed back to
|===

== `[author]`

$a

http://www.loc.gov/marc/bibliographic/bd76x78x.html[The MARC spec] says this should be data that'd be recorded in a 100, 110, or 111 field, which should always be author info.

I'm sure we will see issues where a cataloger didn't provide the proper subfield for a title element, the ILS default-stuck that data in $a, and so there's weirdness in TRLN Discovery. However, this is a data problem to be cleaned up in the underlying data.

We expect this point to be mitigated by excluding fields with NO title element from Argot mapping.

== `[title]`
=== source subfield
==== when $s present
*Use $s value.* $t, if present, will map to `[title_variation]`.

==== when $t and no $s
Use $t value.

==== when neither $s nor $t present
Do not map field to Argot

=== segmentation (only necessary when field is `[display]=true`)

[source,ruby]
----
segmented = title_value.gsub(/([^. ]\.) /, '\1||')
----

== `[title_nonfiling]`
Use to index, but not display abbreviated titles from $p

== `[title_variation]`
=== $t AND $s present
Use $t value when `[title]` is set from $s value.

=== Field does not have *both* $t and $s
Do not set.

== `[details]`

=== Subfields that map to `details`
==== General
Concatenate from the following subfields when present, applying the processing steps specified below:

bcdghkmnoruy

==== 773 (no $c)
bdghkmnoruy

==== 760 and 762
bcdghmnoy

* $k undefined
* $r undefined
* $u undefined

==== 786 ($v included)
bcdghkmnoruvy

$j is currently excluded because:

* no example data in UNC catalog to base mapping/processing on
* no example of how this field is actually used in LC or OCLC MARC specs
* According to http://experimental.worldcat.org/marcusage/786[MARC Usage in WorldCat], it is only used in ONE record ever

=== Formatting data for `details` display
==== Prepend in-`details` labels to contextualize the data from some subfields

[cols=2*,options=header]
|===
|Subfield
|Value prefix

|r
|Report number:

|u
|Technical report number:

|v
|Contributed:

|y
|CODEN:
|===

==== Wrap series data ($k) in parentheses

== `[isbn]`
Use $z value(s).

$z is repeatable, so this must be an array.

$z is *not* defined for MARC fields 760 and 762, so should not be extracted from those fields

== `[issn]`
Use $x value

== `[other_ids]`
Array

Map value from each of the following subfields as element in array

oruwy

$w special instructions: strip parenthetical prefix and trim leading spaces from resulting value
