:toc:
:toc-placement!:

= Work entries: Name/title pattern


*Test records*
The UNC bib records referred to by bib number in this document are at:
todo

toc::[]

== The pattern

* `label`: Contextualizing info derived from data in field itself and/or the MARC tag or indicator values. Will not always be present.
** Display but do not index
* `author`: The author name related portion. Some works do not have an author, so will lack this part.
** indexed as `author_related`, `author_included`, or `author_series` as appropriate
** combined with `title` segment to create indexed `work_citation*` value
* `title`: The title related portion. All works must have a title, so this segment should always be present.
** indexed as `title_related`, `title_included`, `title_series`, or `title_variant_indexed` as appropriate
** if there is no separate `title_filing` element set, combined with `author` segment to create indexed `work_citation*` value for in-catalog hyperlink querying and possible use in autosuggest
** subelements of the title portion are separated with `||` to allow for adaptive hyperlinking. This delimiter is stripped out of the display.
* `title_filing` : The title related portion, minus initial article/non-filing characters, if this value would be different than what's in `title`
** indexed as `title_related`, `title_included`, `title_series`, or `title_variant_indexed` as appropriate
** if present, combined with `author` segment to create indexed `work_citation*` value for in-catalog hyperlink querying and possible use in autosuggest
** subelements of the title portion are separated with `||` to allow for adaptive hyperlinking. This delimiter is stripped out of the display.
* `details`: other bib data about related work
** displayed after the author/title hyperlink, but not included in hyperlink
** not indexed
* `isbn`: ISBN of cited related work.
** displayed, with `ISBN:` label, at end of field display
** indexed in `isbn_related` or `isbn_included` as appropriate 
* `issn`: ISSN of cited related work.
** displayed, with `ISSN:` label, at end of field display
** indexed in `issn_related`, `issn_included`, or `issn_series` as appropriate

Display should be built as follows:
 `label` + `author` + `title` + `details` + ISBN: `isbn` + ISSN: `issn`

Clicking the `author` portion of display, if present, conducts an author phrase seach.

[CAUTION]
----
What happens when you click on author part vs. a title part is tricky, and I don't even know if it can be sanely implemented the way I describe it here.

I have said if you click the author portion, it does a regular author index search on that value.

Once you start clicking in the title portion, it's doing a search on the `work_citation` index for precision.

*The reason for this is:* Only the FIRST author should ever be included in the kind of name/title entry that will populate the `work_citation` index.

If we made clicking the author portion search the `work_citation` index instead of do a general author search, only works where that person was the first/main author will be returned, which is probably NOT what we are looking for. 
----

Clicking the `title` portion of the display conducts an adaptive-hyperlinked `work_citation` starts-with search for `author` + segment of `title` clicked on. 


== Argot fields to which this pattern applies

=== work_citation
"Authorized access point" (or approximation thereof) *for resource described by the record*.

Consists of authorized access point for agent with main responsibility for creation of the work (if applicable, plus the preferred title for the work.

The authorized access point is the mechanism by which the following are accomplished in a library catalog (RDA 6.0):

* bringing together all descriptions of manifestations embodying a work when various manifestations have appeared under various titles
* identifying a work when the title by which it is known differs from a title proper of the manifestation being described
* differentiating between two or more works with the same title
* organizing hierarchical displays of descriptions for manifestations embodying different expressions of a work
* recording a relationship to a related work or a related expression

[NOTE]
----
`work_citation` won't ever include `label`, `details`, `isbn`, or `issn` subelements, but the treatement of the remaining elements in `work_citation` is identical to how they are treated in the other fields in this pattern. 
----

[NOTE]
====
*There will be no "uniform title" field in Argot.*

This is because:

* As per the definition of an authorized access point for a work, the uniform title on its own is not useful
* Patrons (and many librarians) have no clue what the heck a "uniform title" is
* "Uniform title" has been replaced by "preferred title for work" in RDA (the current content standard for library cataloging)
====

In TRLN Discovery, displaying/hyperlinking this supports:

* Navigation to records describing other expressions and manifestations of the work

Indexing this supports:

* Precision in inter-catalog hyperlink navigation features
* (?) Improvements to autosuggest

Data sources:

* 130 if present, otherwise...
* 100/110/111 + 240 if present, otherwise...
* 100/110/111 + 243 if present, otherwise...
* 100/110/111 + 245anp (subfields to include need verification) if present, otherwise...
* 245anp (subfields to include need verification) when no 1XX and ind1=0

=== included_work
"Authorized access point" (or approximation thereof) for *work included in the resource described by the catalog record*

Data sources:

* 700, 710, or 711 with ind2=2 and $t or $k present
** Label specifying type of relationship from $i if present
* 730 with ind2=2 (will not include author elements)
** Label specifying type of relationship from $i if present
* 740 with ind2=2 (will not include author elements)
* 774 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== issued_with_work
"Authorized access point" (or approximation thereof) for *work that is separately cataloged but that is issued with or included in the resource described by the catalog record*

Data sources:

* 777 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

=== related_work
"Authorized access point" (or approximation thereof) for *work related to the resource described by the catalog record*

Data sources:

* 700, 710, or 711 with ind2!=2 and $t or $k present
** Label specifying type of relationship from $i if present
* 730 with ind2!=2 (will not include author elements)
** Label specifying type of relationship from $i if present
* 740 with ind2!=2 (will not include author elements)
* 765 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Is a translation of:" (or "Original language version:")
* 767 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Has been translated as:"
* 770 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Has supplement:"
* 772 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Supplement to:" or "Has parent resource:", depending on ind2 value
* 773 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Is part of:"
* 775 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Other edition:"
* 786 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Data source:"
* 786 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== earlier_work
"Authorized access point" (or approximation thereof) for *work that is separately cataloged, of which the resource cataloged here is a continuation*

Data sources:

* 780 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== later_work
"Authorized access point" (or approximation thereof) for *work that is separately cataloged, which continues the resource cataloged here*

Data sources:

* 785 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== series_collocating
"Authorized access point" (or approximation thereof) representing *the series of which the resouce cataloged here is a member*

Data sources:

* 800, 810, 811, or 830


[NOTE]
----
Some subject fields follow this same pattern, so we _could_ implement a `subject_work` field that'd be modeled the same way as the other fields covered here. It would be defined as:

"Authorized access point" (or approximation thereof) for *work that is a subject of the resource cataloged here*

Data sources:

- 600, 610, 611 with $t or $k
- 630

We are currently treating these the same as any other subject headings, which is fine for now. 
----

== Examples
=== this work + included work + series
==== MARC

[source]
----
100 1 _ $aLiszt, Franz,$d1811-1886.
240 1 0 $aPiano music.$kSelections
245 1 4 $aThe complete music for solo piano.$n29$h[sound recording] /$cFranz Liszt.
700 1 2 $aLiszt, Franz,$d1811-1886.$tMagyar dallok.
700 1 2 $aLiszt, Franz,$d1811-1886.$tRhapsodies hongroises.$nNo 9.
800 1 _ $aLiszt, Franz,$d1811-1886.$tPiano music (Howard) ;$v29.$x0084-4411
----

==== Argot

[source:javascript]
----
{
  "authors":{
    "main":[
      {
        "name":"Liszt, Franz, 1811-1886."
      }
    ]
  },
  "work_citation":{
    "author":"Liszt, Franz, 1811-1886.",
    "title":"Piano music.||Selections"
  },
  "title_main":{
    "value":"The complete music for solo piano. 29 [sound recording]",
    "sort":"complete music for solo piano. 29 [sound recording]"
  },
  "statement_of_responsibility":{
    "value":"Franz Liszt."
  },
  "included_work":[
    {
      "author":"Liszt, Franz, 1811-1886.",
      "title":"Magyar dallok."
    },
    {
      "author":"Liszt, Franz, 1811-1886.",
      "title":"Rhapsodies hongroises.||No 9."
    }
  ],
  "series_collocation":{
    "author":"Liszt, Franz, 1811-1886.",
    "title":"Piano music (Howard) ;",
    "details":"29.",
    "issn":"0084-4411"
  }
}
----

==== Full record display (partial)
*The complete music for solo piano. 29 [sound recording]* +
Franz Liszt. +
London : Hyperion, p1994.

*Authors, etc.* +
Author: Liszt, Franz, 1811-1886.

*This item includes* +
http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Magyar_dallok[Magyar dallok.] +
http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Rhapsodies_hongroises[Rhapsodies hongroises.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Rhapsodies_hongroises_No_9[No 9.]

*Related items* +
More like this: http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Piano_music[Piano music.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Piano_music_Selections[Selections]

Other items in series: http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Piano_music_Howard[Piano music (Howard) ;] 29. ISSN: 0084-4411 

==== Indexed

* *authors_main* (Author, Keyword)
** Liszt, Franz, 1811-1886.
* *author_included*  (Author, Keyword)
** Liszt, Franz, 1811-1886.
* *author_series*  (Series, Author, Keyword)
** Liszt, Franz, 1811-1886.
* *statement_of_responsibility* (Author, Keyword)
** Franz Liszt.
* *work_citation* (Work Citation for intercatalog linking)
** Liszt, Franz, 1811-1886. Piano music. Selections
* *work_citation_included*
** Liszt, Franz, 1811-1886. Magyar dallok.
** Liszt, Franz, 1811-1886. Rhapsodies hongroises. No 9.
* *work_citation_series*
** Liszt, Franz, 1811-1886. Piano music (Howard)
* *title_main* (Title, Keyword)
** complete music for solo piano. 29 [sound recording]
** The complete music for solo piano. 29 [sound recording]
* *title_variants* (Title, Keyword)
** Piano music. Selections
* *title_included* (Title, Keyword)
** Magyar dallok.
** Rhapsodies hongroises. No 9.
* *title_series* (Series, Title, Keyword)
** Piano music (Howard) ;
* *issn_series* (ISBN/ISSN, Keyword)
** 0084-4411

=== Earlier/Later titles - display info from notes, index info from linking entries
==== MARC
[source]
----
210 0 _ $aActa bot. neerl.
222 _ 0 $aActa botanica neerlandica
245 0 0 $aActa botanica Neerlandica$h[serial] :$bofficial publication of the Nederlandse Botanische Vereniging.
580 _ _ $aMerger of: Nederlandsch kruidkundig archief, and: Recueil des travaux botaniques néerlandais.
580 _ _ $aMerged with: Botanica acta, to form: Plant biology (Stuttgart, Germany).
770 0 _ $tWentia$w(DLC)   86653984$w(OCoLC)1769608
776 1 _ $tActa botanica neerlandica (Online)$w(OCoLC)38089048
780 1 4 $tNederlandsch kruidkundig archief$g1858-1951$w(OCoLC)1714426
780 1 4 $tRecueil des travaux botaniques néerlandais$w(DLC)sc 82003303$w(OCoLC)1590372
785 1 7 $tBotanica acta$x0932-8629$w(DLC)   88640720$w(OCoLC)17167709
785 1 7 $tPlant biology (Stuttgart, Germany)$x1435-8603$w(DLC)sn 99047129$w(OCoLC)41000240
----

==== Argot (partial)
[source:javascript]
----
{
  "title_variant_indexed":[
    "Acta bot. neerl.",
    "Acta botanica neerlandica"
  ],
  "work_citation":{
    "title":"Acta botanica Neerlandica"
  },
  "title_main":{
    "value":"Acta botanica Neerlandica [serial] : official publication of the Nederlandse Botanische Vereniging."
  },
  "related_work_note":[
    "Merger of: Nederlandsch kruidkundig archief, and: Recueil des travaux botaniques néerlandais.",
    "Merged with: Botanica acta, to form: Plant biology (Stuttgart, Germany)."
  ],
  "related_work":[
    {
      "label":"Has supplement:",
      "title":"Wentia"
    }
  ],
  "title_history_index_only":[
    {
      "title":"Nederlandsch kruidkundig archief"
    },
    {
      "title":"Recueil des travaux botaniques néerlandais"
    },
    {
      "title":"Botanica acta",
      "issn":"0932-8629"
    },
    {
      "title":"Plant biology (Stuttgart, Germany)",
      "issn":"1435-8603"
    }
  ]
}
----

==== Full record display (partial)
*Acta botanica Neerlandica [serial] : official publication of the Nederlandse Botanische Vereniging.* +
Amsterdam : North-Holland Pub. Co., 1952-c1998.

*Related items* +
More like this: http://www.search.com/work_citation_begins_with/Acta_botanica_Neerlandica[Acta botanica Neerlandica] +
Merger of: Nederlandsch kruidkundig archief, and: Recueil des travaux botaniques néerlandais. +
Merged with: Botanica acta, to form: Plant biology (Stuttgart, Germany). +
Has supplement: http://www.search.com/work_citation_begins_with/Wentia[Wentia]

==== Indexed

* *work_citation* (Work Citation for intercatalog linking)
** Acta botanica Neerlandica
* *title_main* (Title, Keyword)
** Acta botanica Neerlandica [serial] : official publication of the Nederlandse Botanische Vereniging.
* *title_variants* (Title, Keyword)
** Acta bot. neerl.
** Acta botanica neerlandica
* *title_related*
** Wentia
* *title_history* (Title, Keyword)
** Nederlandsch kruidkundig archief
** Recueil des travaux botaniques néerlandais
** Botanica acta
** Plant biology (Stuttgart, Germany)
* *issn_title_history* (ISBN/ISSN, Keyword)
** 0932-8629
** 1435-8603

=== UNCb7641376 - related work 700 with $i
==== MARC
100 1 _ $aSabuda, Robert,$eauthor.
245 1 4 $aThe little mermaid :$ba pop-up adaptation of the classic fairy tale /$cRobert Sabuda.
250 _ _ $aFirst edition.
264 _ 1 $aNew York :$bLittle Simon, an imprint of Simon & Schuster Children's Publishing Division,$c[2013]
700 1 _ $iBased on:$aAndersen, H. C.$q(Hans Christian),$d1805-1875.$tLille havfrue.$lEnglish.

==== Argot
[source,javascript]
----
{
  "work_citation":{
    "author":"Sabuda, Robert",
    "title":"Little mermaid"
  },
  "title_main":{
    "value":"The little mermaid : a pop-up adaptation of the classic fairy tale",
    "sort":"little mermaid : a pop-up adaptation of the classic fairy tale"
  },
  "statement_of_responsibility":[
    {
      "value":"Robert Sabuda."
    }
  ],
  "related_work":{
    "label":"Based on:",
    "author":"Andersen, H. C. (Hans Christian), 1805-1875.",
    "title":"Lille havfrue.||English."
  }
}
----

==== Full record display (partial)
*The little mermaid : a pop-up adaptation of the classic fairy tale* +
Robert Sabuda. +
New York : Little Simon, an imprint of Simon & Schuster Children's Publishing Division, [2013] +
First edition.

*Authors, etc.* +
Author: http://www.search.com/author_search_for/Sabuda,_Robert[Sabuda, Robert,] author.

*Related items* +
Based on: http://www.search.com/author_search_for/Andersen_string[Andersen, H. C. (Hans Christian), 1805-1875.] http://www.search.com/work_citation_begins_with_Andersen_string_Lille_havfrue/[Lille havfrue.] http://www.search.com/work_citation_begins_with_Andersen_string_Lille_havfrue_English[English.]

* *authors_main* (Author, Keyword)
** Sabuda, Robert, author.
* *author_related*  (Author, Keyword)
** Andersen, H. C. (Hans Christian), 1805-1875.
* *statement_of_responsibility* (Author, Keyword)
** Robert Sabuda.
* *work_citation* (Work Citation for intercatalog linking)
** Sabuda, Robert. Little mermaid
* *work_citation_included*
** Andersen, H. C. (Hans Christian), 1805-1875. Lille havfrue. English.
* *title_main* (Title, Keyword)
** The little mermaid : a pop-up adaptation of the classic fairy tale
** little mermaid : a pop-up adaptation of the classic fairy tale
* *title_related* (Title, Keyword)
** Lille havfrue. English

