:toc:
:toc-placement!:

= Title variant pattern


*Test records*
The UNC bib records referred to by bib number in this document are at:
todo

toc::[]

== The pattern and its behavior

[source,javascript]
----
{
  "title_variant":[
    {
      "type":"Variant type, controlling final Solr field output",
      "label":"Label for the note displayed with the field content",
      "value":"The displayed content of the note",
      "indexed_value":"The part of above value that should be indexed, if it is different from value",
      "display":"Boolean: true or false"
    }
  ]
}
----

* `type`: *Optional.* Allowed values are: variant, abbrev, former. If not set, defaults to 'variant'
* `label`: Optional. May be set from $3, $i, and/or MARC field tag + indicator values. No need to set if `display` = false.
* `value`: *Required.* The note that will be displayed. If there is no `indexed_value` and `indexed` is not false, this is also the indexed note content.
* `indexed_value`: Optional. This should only be populated if `indexed_value` needs to be different than `value`
* `display`: Optional. If not explicitly set, assumed to equal true. In other words, default assumption is that the field data will be displayed.

=== Post-Argot pseudomapping
[source,javascript]
----
{
  "title_variant":[
    {
      "type":"abbrev",
      "value":"GATT act.",
      "display":"false"
    }
  ]
}
----

* `abbrev_title_indexed`: "GATT act." 

[source,javascript]
----
{
  "title_variant":[
    {
      "value":"Revista do Instituto Historico e Geographico Brazileiro",
      "display":"false"
    }
  ]
}
----

* `variant_title_indexed`: "Revista do Instituto Historico e Geographico Brazileiro"

[source,javascript]
----
{
  "title_variant":[
    {
      "label":"Spine title:",
      "value":"Cicero's epistles"
    }
  ]
}
----

* `variant_title_display`: "Spine title: Cicero's epistles"
* `variant_title_indexed`: "Cicero's epistles"

[source,javascript]
----
{
  "title_variant":[
    {
      "label":"Title varies:",
      "value":"Academic science and engineering. R&D expenditures 1990-",
      "indexed_value":"Academic science and engineering. R&D expenditures",
    }
  ]
}
----

* `variant_title_display`: "Title varies: Academic science and engineering. R&D expenditures 1990-"
* `variant_title_indexed`: "Academic science and engineering. R&D expenditures"

[source,javascript]
----
{
  "title_variant":[
    {
      "value":"ARBA [serial]",
      "indexed_value":"ARBA"
    }
  ]
}
----

* `variant_title_display`: "ARBA [serial]"
* `variant_title_indexed`: "ARBA"


== Examples

=== 210
==== Processing instructions

*`type`='abbrev'*

*`display` is always false*

*`indexed_value` is never needed because `value` contains the indexed value in an indexed-only field*

*indexed subfields include: a*

==== UNCb1300526

===== MARC

[source]
----
210 0 _ $aGATT act.
----

===== Argot

[source,javascript]
----
{
  "title_variant":[
    {
      "type":"abbrev",
      "value":"GATT act.",
      "display":"false"
    }
  ]
}
----

==== UNCb5752056

===== MARC

[source]
----
210 0 _ $aNew-England j. med. surg. collat. branches sci.$b(Online)
----

===== Argot

[source,javascript]
----
{
  "title_variant":[
    {
      "type":"abbrev",
      "value":"New-England j. med. surg. collat. branches sci.",
      "display":"false"
    }
  ]
}
----



=== 246
==== Processing instructions
*`type` can be left blank, as 246 is defined as varying form of title.* +
Alternately, explicitly set `type` to 'variant'

*`display` value is determined by i1 value*

[cols=2*,options=header]
|===
|i1 value
|`display` value

|{blank} (this is an invalid code)
|false

|0
|true (default)

|1
|true (default)

|2
|false

|3
|false
|===

*`display` value is also false when i2=0 or 1*

http://www.loc.gov/marc/bibliographic/bd246.html[The MARC spec for 246] says no note is generated when i2=0 or 1. Fields coded this way are supposed to contain portions of the title data recorded (and displayed) in the 245

*`label` value is determined by i2 value and/or data in $i*

If there is an i2 value that generates a `label`, *and* an $i value, the $i value is appended to the generated i2 value.

[cols=2*,options=header]
|===
|i2 value
|`label` value

|{blank}
|na

|0
|na

|1
|na

|2
|Distinctive title:

|3
|na

|4
|Cover title:

|5
|Added title page title:

|6
|Caption title:

|7
|Running title:

|8
|Spine title:
|===

No `label` value is generated by i2=3 because the only possible constant value we could generate from this indicator value is "Other title." That seems redundant with the overall field label that will be generated when `type`='variant'. It's also awkward/redundant to display "Other title" in concert with a $i display value:

 Other title: Title on t.p. verso: Bright ray of hope

*The following subfields are part of the displayed value: abfghnp*

*The following subfields get indexed as part of the actual varying title: abnp*

==== UNCb1109400
`display`=false based on i2 overrides instruction from i1

===== MARC

[source]
----
245 1 0 $aZodchestvo drevneĭ Rusi.$bEarly Russian architecture. Architecture de la vieille Russie. Altrussische Baukunst. Arquitectura de la antigua Rus.
246 1 1 $aEarly Russian architecture
246 1 1 $aArchitecture de la vieille Russie
246 1 1 $aAltrussische Baukunst
246 1 1 $aArquitectura de la antigua Rus
----

===== Argot

* `type` not set --- defaults to 'variant'
* `label` not set because i2=1 means do not display
* `indexed_value` unnecessary
* `display`=false because i2=1

[source,javascript]
----
{
  "title_variant":[
    {
      "value":"Early Russian architecture",
      "display":"false"
    },
    {
      "value":"Architecture de la vieille Russie",
      "display":"false"
    },
    {
      "value":"Altrussische Baukunst",
      "display":"false"
    },
    {
      "value":"Arquitectura de la antigua Rus",
      "display":"false"
    }
  ]
}
----

==== UNCb1826083
`display`=false based on i1=blank

===== MARC

[source]
----
245 0 0 $aRevista do Instituto Historico e Geografico Brasileiro$h[serial].
246 _ _ $aRevista do Instituto Historico e Geographico Brazileiro$h[serial]
----

===== Argot

* `type` not set --- defaults to 'variant'
* `label` not set because i1=blank means do not display
* `indexed_value` unnecessary -- index-only field does not need to display and index different content, so `value` just contains the part to be indexed
* `display`=false because i2=1

[source,javascript]
----
{
  "title_variant":[
    {
      "value":"Revista do Instituto Historico e Geographico Brazileiro",
      "display":"false"
    }
  ]
}
----

==== UNCb1100989

===== MARC

[source]
----
245 1 4 $aThe epistles of M.T. Cicero to M. Brutus and of Brutus to Cicero :$bwith the Latin text on the opposite page, and English notes to each epistle : together with a prefatory dissertation, in which the authority of the said epistles is vindicated, and all the objections of the Revd. Mr. Tunstall particularly considered and confuted /$cby Conyers Middleton, D.D., principal library keeper of the University of Cambridge.
246 1 8 $aCicero's epistles
----

===== Argot

* `type` not set --- defaults to 'variant'
* `label` set from i2
* `indexed_value` unnecessary -- `value` doesn't get any data mapped from non-indexed subfields
* `display` not set -- defaults to true

[source,javascript]
----
{
  "title_variant":[
    {
      "label":"Spine title:",
      "value":"Cicero's epistles"
    }
  ]
}
----

==== UNCb3688022

===== MARC

[source]
----
245 0 0 $aAcademic science/engineering.$pR&D expenditures.
246 1 _ $iTitle varies:$aAcademic science and engineering.$pR&D expenditures$f1990-
----

===== Argot

* `type` not set --- defaults to 'variant'
* `label` set from $i
* `indexed_value` set because $f is a display-but-don't-index subfield
* `display` not set -- defaults to true

[source,javascript]
----
{
  "title_variant":[
    {
      "label":"Title varies:",
      "value":"Academic science and engineering. R&D expenditures 1990-",
      "indexed_value":"Academic science and engineering. R&D expenditures",
    }
  ]
}
----

==== UNCb4864585

===== MARC

[source]
----
245 1 0 $a"Nadezhdy svetlyĭ luch" /$cGalina Mandelʹshtam.
246 1 3 $iTitle on t.p. verso:$aBright ray of hope
----

===== Argot

* `type` not set --- defaults to 'variant'
* `label` set from $i
* `indexed_value` not set -- defaults to what is in `value`
* `display` not set -- defaults to true

[source,javascript]
----
{
  "title_variant":[
    {
      "label":"Title on t.p. verso:",
      "value":"Bright ray of hope"
    }
  ]
}
----

==== UNCb1224465

===== MARC

[source]
----
245 0 0 $aAmerican reference books annual$h[serial].
246 1 3 $aARBA$h[serial].
----

===== Argot

* `type` not set --- defaults to 'variant'
* `label` not set b/c i2=3 and no $i
* `indexed_value` set because `value` contains data from non-indexed subfields
* `display` not set -- defaults to true

[source,javascript]
----
{
  "title_variant":[
    {
      "value":"ARBA [serial]",
      "indexed_value":"ARBA"
    }
  ]
}
----

==== UNCb7923150

===== MARC

[source]
----
246 1 5 $iBook 3:$aOnuphrij Panuinij Veronensis Fratris Eremitae Augustiniani Imperium Romanum
246 1 5 $iBook 2:$aOnuphrij Panuinij Veronensis Fratris Eremitae Augustiniani Ciuitas Romana
----

===== Argot

* `type` not set --- defaults to 'variant'
* `label` set from i2 and $i
* `indexed_value` not set because `value` does not contain data from non-indexed subfields
* `display` not set -- defaults to true

[source,javascript]
----
{
  "title_variant":[
    {
      "label":"Added title page title: Book 3:",
      "value":"Onuphrij Panuinij Veronensis Fratris Eremitae Augustiniani Imperium Romanum"
    },
    {
      "label":"Added title page title: Book 2:",
      "value":"Onuphrij Panuinij Veronensis Fratris Eremitae Augustiniani Ciuitas Romana"
    }
  ]
}
----

==== UNCb5289988

===== MARC

[source]
----
245 1 0 $aLovin' pretty women$h[sound recording] /$cSteep Canyon Rangers.
246 3 _ $aLoving pretty women
----

===== Argot

* `type` not set -- defaults to 'variant'
* `label` not set because `display`=false
* `indexed_value` not set because `display`=false
* `display`=false based on i1

[source,javascript]
----
{
  "title_variant":[
    {
      "value":"Loving pretty women",
      "display":"false"
    }
  ]
}
----

==== UNCb1300526

===== MARC

[source]
----
245 1 0 $aGATT activities in ... /$cGeneral Agreement on Tariffs and Trade$h[serial].
246 3 _ $aGATT activities$f1984-
----

===== Argot

* `type` not set -- defaults to 'variant'
* `label` not set because `display`=false
* `indexed_value` not set because `display`=false
* `display`=false based on i1

[source,javascript]
----
{
  "title_variant":[
    {
      "value":"GATT activities"
      "display":"false"
    }
  ]
}
----

=== 247




 

