:toc:
:toc-placement!:

= Names pattern

The pattern used to create fields for names recorded in the catalog record.

Names recorded in a catalog record include personal, corporate body, and conference/meeting names.

This is called the `names` pattern instead of the author pattern because the names recorded in a catalog record may represent authors, other work creators (such as composers or artists), contributors (such as arrangers or conductors), manufacturers, publishers, and entities playing other uncategorized roles (owner or former owner of the item described; person who donated or inscribed the item described; etc.).

This pattern is used in the following Argot fields:
* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/names.adoc[names]

toc::[]

== The pattern: Argot elements
=== `name`
This is the full name (with any qualifiers) from the source MARC field

* string
* *required*

Hyperlinked in display to perform author query.

If the name is of a `type` mapped to the author facet, only the `name` portion is included in the facet value.

==== Processing notes

* Strip ending punctuation (.,) and spaces

=== `rel`
The relator term(s) included in the name entry. Specifies the relationship of the agent represented by the name to the item described.

* array/repeatable
* not required - may be empty

Displayed but not part of hyperlink or resulting query, since names in legacy data are likely to lack relator terms and the search should not be over-specific.

==== Processing notes
The following steps should be done in order:

* Strip punctuation and spaces from beginning and end of field. Expected punctuation includes period and comma. 
* Replace relator *codes* with relator *terms* using marc-to-argot/lib/translation_maps/shared/relator_code_to_term.yaml
* Strip WEMI terms (may be parenthetical) from relator *terms* if present: work, expression, manifestation, item
* Deduplicate the resulting array (sometimes both the term and the code for the same role is recorded)

=== `type`
Type, or category, of name.

* string
* required (if not explicitly provided, default to 'no_rel' (i.e. no_relator data)

Serves two major purposes:

* control creation of different indexed fields that can be relevance ranked differently (i.e. creators highest, contributors higher than 'other', etc.) in author search
* control which names get included in author facet

==== `type` values

[NOTE]
====
Legacy MARC data often lacks the relator data required to assign `type` accurately.

We will know for sure that any name in 100, 110, or 111 is a creator.

Names in 7XX fields could be anything and are more likely to be contributors than creators, so names with `type`='no_rel' are treated like names with `type`='contributor'
====

* Highest relevance rank in author search, included in author facet
** `director`
** `creator`

[NOTE]
====
`director` is higher than `creator` to account for the fact that we want directors to specifically be mapped to a directors field.

The director is often also a screenwriter, and screenwriter maps to the `creator` category.

If we ranked `creator` above `director` here, such a director would be assigned `type`='creator' instead of type='director'

Aside: I went back and forth about whether, in such cases, there should be both a `creator` AND a `director` indexed field added, but I think that approach is likely to skew relevance in a weird way.
====

* Slightly lower relevance rank in author search, included in author facet
** `editor`
** `contributor`
** `no_rel` 

* Even lower relevance rank in author search, not included in author facet
** `other`
** `owner`
** `uncategorized`

* Lowest relevance rank in author search. Also include in publisher search. Do not include in author facet
** `distributor`
** `manufacturer`
** `publisher`

==== Processing notes

* If there are no `rel` values
** If MARC data source is 100, 110, 111
*** `type`='creator'
** Otherwise:
*** `type` = 'no_rel'

* Otherwise:
** Look up the relator category for each relator term in marc-to-argot/lib/translation_maps/shared/relator_categories.yaml
*** If relator term is not mapped to a relator category in that file, assign `type`='uncategorized' and ideally emit a warning to a log somewhere that data folks can use to review (cause may be terms from another vocabulary need to be added to mappings, or typo in underlying data needs to be fixed)
** If the name falls into more than one category, assign the highest category in the `type` hierarchy as the `type` value
*** For example, the first name in the abstract example below has two relators terms: author (creator category) and illustrator (contributor category). Creator > contributor, so `type` = 'creator'.

== Abstract example of pattern
=== Argot

[source,ruby]
----
[{'name'=>'aaaa',
  'rel'=>['author', 'illustrator'],
  'type'=>'creator'},
  {'name'=>'dddd'},
  {'name'=>'eeee',
   'rel'=>['fff'],
   'type'=>'owner'},
   {'name'=>'gggg',
   'rel'=>['hhh'],
   'type'=>'manufacturer'},
   {'name'=>'iiii',
   'rel'=>['jjj'],
   'type'=>'contributor'},
   {'name'=>'kkkk',
   'rel'=>['film director'],
   'type'=>'director'},
   {'name'=>'mmmm',
   'rel'=>['editor of compilation'],
   'type'=>'editor'}
  ]
----

=== Display/behavior

*Authors, etc.*

* http://query.info/author_search[aaaa], author, illustrator
* http://query.info/author_search[dddd]
* http://query.info/author_search[eeee], fff
* http://query.info/author_search[gggg], hhh
* http://query.info/author_search[iiii], jjj
* http://query.info/author_search[kkkk], director
* http://query.info/author_search[iiii], editor of compilation

=== Indexing

[source,javascript]
----
{"author_facet_tf_stored": [
  "aaaa", "dddd", "iiii", "kkkk", "mmmm"
  ],
 "names_tf_stored": [
   "aaaa||, author, illustrator",
   "dddd",
   "eeee||, fff",
   "gggg||, hhh",
   "iiii||, jjj",
   "kkkk||, director",
   "mmmm||, editor of complilation"
 ],
 "name_creator_t": [
   "aaaa, author, illustrator"
 ],
 "name_no_rel_t": [
   "dddd"
 ],
 "name_owner_t": [
   "eeee, fff"
 ],
 "name_manufacturer_t": [
   "gggg, hhh"
 ],
 "name_contributor_t": [
   "iiii, jjj"
 ],
 "name_director_t": [
   "kkkk, film director"
 ],
 "name_editor_t": [
   "mmmm, editor of compilation"
 ]  
}
----

[NOTE]
----
Current plan is to send `name` + `rel` to fields that will be included in both author and keyword indexes.

We want to test if inclusion of `rel` value in author index negatively affects relevance of names with a `rel` value when the query does not include the `rel` value. (Important since hyperlinks in the UI will NOT include `rel` values in their queries, will conduct author queries)

If this is seen as a problem, we may need to split the values included in author and keywork indexes into separate fields.
----

== MARC examples
=== UNCb8893558

[source]
----
=100  \\$aKey, Keegan-Michael
=245  10$aDon't think twice /$cproduced by Miranda Bailey, Jason Beck, Mike Birbiglia, Ira Glass, Amanda Marshall ; written and directed by Mike Birbiglia.
=700  1\$aBirbiglia, Mike,$edirector,$escreenwriter,$eproducer,$eactor.
=700  1\$aJacobs, Gillian,$d1982-$eactor. 
=700  1\$aMicucci, Kate,$eactor.
=700  1\$aSagher, Tami,$eactor.
----

[source,ruby]
----
[{'name'=>'Key, Keegan-Michael',
  'type'=>'creator'},
  {'name'=>'Birbiglia, Mike',
   'rel'=>['director', 'screenwriter', 'producer', 'actor'],
   'type'=>'director'},
   {'name'=>'Jacobs, Gillian, 1982-',
   'rel'=>['actor'],
   'type'=>'contributor'},
   {'name'=>'Micucci, Kate',
   'rel'=>['actor'],
   'type'=>'contributor'},
   {'name'=>'Sagher, Tami',
   'rel'=>['actor'],
   'type'=>'contributor'}
  ]
----


=== UNCb9030005

[source]
----
=100  0\$aJerome,$cSaint,$d-419 or 420,$eauthor.$4aut
=245  10$aPréfaces aux livres de la Bible /$cJérôme ; textes latins des éditions de R. Weber et R. Gryson et de l'Abbaye Saint-Jérôme (Rome), revus et corrigés ; introduction, traduction et notes réalisées en séminaire sous la direction d'Aline Canellis.
=700  1\$aCanellis, Aline,$eeditor,$etranslator.$4edt$4trl
=700  02$iContainer of (expression):$aJerome,$cSaint,$d-419 or 420.$tPrefaces.$lFrench$s(Canellis)
=700  02$iContainer of (expression):$aJerome,$cSaint,$d-419 or 420.$tPrefaces.$lLatin$s(Canellis)
----

[source,ruby]
----
[{'name'=>'Jerome, Saint, -419 or 420',
  'rel'=>['author'],
  'type'=>'creator'},
  {'name'=>'Canellis, Aline',
   'rel'=>['editor', 'translator'],
   'type'=>'editor'}
  ]
----

[NOTE]
====

* Importance of cleaning up punctuation around relators and deduplicating
* Canellis is `type`='editor' because 'editor' > 'contributor'
* 7XX with $t or $k are ignored -- they are handled as `related_work` or `included_work` fields

====

=== UNCb6030502

[source]
----
=100  1\$aRobeson, Paul,$d1898-1976.$4prf
=245  10$aPaul Robeson live at Carnegie Hall$h[sound recording].
=700  1\$aBooth, Alan,$d1924-1996.$4prf
=700  12$aAleksandrov, Anatoliĭ Nikolaevich,$d1888-1982.$tAkh ty nochka, nochen'ka.
=700  12$aClutsam, George H.,$d1866-1951.$tMa curly-headed babby.
=700  12$aFisher, William Arms,$d1861-1948.$tGoin' home.
=700  12$aKern, Jerome,$d1885-1945.$tShow boat.$pOl' man river;$oarranged.
=700  12$aMussorgsky, Modest Petrovich,$d1839-1881.$tBoris Godunov (Rimsky-Korsakov).$pMonolog Borisa;$oarranged.
=700  12$aMussorgsky, Modest Petrovich,$d1839-1881.$tSirotka.
=700  12$aBach, Johann Sebastian,$d1685-1750.$tChrist lag in Todesbanden (Chorale);$oarranged.
=700  12$aSchubert, Franz,$d1797-1828.$tWiegenlied.
=700  12$aRobinson, Earl,$d1910-1991.$tJoe Hill.
=700  12$aBeethoven, Ludwig van,$d1770-1827.$tSymphonies,$nno. 9, op. 125,$rD minor.$pFreude, schöner Götterfunken;$oarranged.
----

[source,ruby]
----
[{'name'=>'Robeson, Paul, 1898-1976',
  'rel'=>['performer'],
  'type'=>'contributor'},
  {'name'=>'Booth, Alan, 1924-1996',
   'rel'=>['performer'],
   'type'=>'contributor'}
  ]
----

[NOTE]
====

* Robeson is `type`='contributor' despite being recorded in the 100 because 'performer' maps to that category
* 7XX with $t or $k are ignored -- these will be handled as `included_work`

====
