:toc:
:toc-placement!:

= Work entry pattern

The pattern used to create fields for works (i.e. often having name/title characteristics, among others, and designed to help the user navigate to other sets of records in the catalog)

*Test records*
The UNC bib records referred to by bib number in this document are at:
todo

toc::[]

== The pattern

* `label`: Contextualizing info derived from data in field itself and/or the MARC tag or indicator values. Will not always be present.
** Display but do not index
* `author`: The author name related portion. Some works do not have an author, so will lack this part.
** indexed as `author_related`, `author_included`, or `author_series` as appropriate
** combined with `title` segment to create indexed `work_citation*` value
* `title`: The title related portion. All works must have a title, so this segment should always be present.
** indexed as `title_related`, `title_included`, `title_series`, or `title_variant_indexed` as appropriate
** if there is no separate `title_filing` element set, combined with `author` segment to create indexed `work_citation*` value for in-catalog hyperlink querying and possible use in autosuggest
** subelements of the title portion are separated with `||` to allow for adaptive hyperlinking. This delimiter is stripped out of the display.
* `title_filing` : The title related portion, minus initial article/non-filing characters, if this value would be different than what's in `title`
** indexed as `title_related`, `title_included`, `title_series`, or `title_variant_indexed` as appropriate
** if present, combined with `author` segment to create indexed `work_citation*` value for in-catalog hyperlink querying and possible use in autosuggest
** subelements of the title portion are separated with `||` to allow for adaptive hyperlinking. This delimiter is stripped out of the display.
* `title_variation` : used to index under non-uniform title when uniform title and title proper are recorded in linking fields
* `details`: other bib data about related work
** displayed after the author/title hyperlink, but not included in hyperlink
** not indexed
* `isbn`: ISBN of cited related work.
** displayed, with `ISBN:` label, at end of field display
** indexed in `isbn_related` or `isbn_included` as appropriate 
* `issn`: ISSN of cited related work.
** displayed, with `ISSN:` label, at end of field display
** indexed in `issn_related`, `issn_included`, or `issn_series` as appropriate

Display should be built as follows:
 `label` + `author` + `title` + `details` + ISBN: `isbn` + ISSN: `issn`

Clicking the `author` portion of display, if present, conducts an author phrase seach.

[CAUTION]
====
What happens when you click on author part vs. a title part is tricky, and I don't even know if it can be sanely implemented the way I describe it here.

I have said if you click the author portion, it does a regular author index search on that value.

Once you start clicking in the title portion, it's doing a search on the `work_citation` index for precision.

*The reason for this is:* Only the FIRST author should ever be included in the kind of name/title entry that will populate the `work_citation` index.

If we made clicking the author portion search the `work_citation` index instead of do a general author search, only works where that person was the first/main author will be returned, which is probably NOT what we are looking for. 
====

Clicking the `title` portion of the display conducts an adaptive-hyperlinked `work_citation` starts-with search for `author` + segment of `title` clicked on. 


== Argot fields to which this pattern applies

=== work_citation
"Authorized access point" (or approximation thereof) *for resource described by the record*.

[NOTE]
====
Record A describes Work A

Record B describes a work that has related work: Work A

The `work_citation` derived from Record A should be the same as the concatenated `author` and `title` portions of the `related_work` derived from Record B.
====

Consists of authorized access point for agent with main responsibility for creation of the work (if applicable, plus the preferred title for the work.

The authorized access point is the mechanism by which the following are accomplished in a library catalog (RDA 6.0):

* bringing together all descriptions of manifestations embodying a work when various manifestations have appeared under various titles
* identifying a work when the title by which it is known differs from a title proper of the manifestation being described
* differentiating between two or more works with the same title
* organizing hierarchical displays of descriptions for manifestations embodying different expressions of a work
* recording a relationship to a related work or a related expression

[NOTE]
====
`work_citation` won't ever include `label`, `details`, `isbn`, or `issn` subelements, but the treatment of the remaining elements in `work_citation` is identical to how they are treated in the other fields in this pattern. 
====

[NOTE]
====
*There will be no "uniform title" field in Argot.*

This is because:

* As per the definition of an authorized access point for a work, the uniform title on its own is not useful
* Patrons (and many librarians) have no clue what the heck a "uniform title" is
* "Uniform title" has been replaced by "preferred title for work" in RDA (the current content standard for library cataloging)
====

In TRLN Discovery, displaying/hyperlinking this supports:

* Navigation to records describing other expressions and manifestations of the work

Indexing this supports:

* Precision in inter-catalog hyperlink navigation features
* (?) Improvements to autosuggest

Data sources:

* 130 if present, otherwise...
* 100/110/111 if present + 240 if present, otherwise...
* 100/110/111 if present + 243 if present, otherwise

=== work_citation_uncontrolled
Basically the same as `work_citation`, but set when a preferred form of title is not recorded in 130, 240, or 243 field.

Index only.

This should not display (as `work_citation` does) in related works section ("More like this:"). Since a preferred title has not been established for useful collocation in the catalog, it is unlikely to provide a useful collocation.

Since this field is derived from the same data source as `authors_main` and `title_main`, it does not need to be displayed at all.

It is needed to make the name/title-based navigation in the catalog work properly.  *Other* records may record this item as a related or included work, and this is the form they should use to do that, according to the cataloging standards.

Data sources:

* 100/110/111 if present + 245anp (need to verify the subfields included)


=== included_work
"Authorized access point" (or approximation thereof) for *work included in the resource described by the catalog record*

Data sources:

* 700, 710, or 711 with ind2=2 and $t or $k present
** Label specifying type of relationship from $i if present
* 730 with ind2=2 (will not include author elements)
** Label specifying type of relationship from $i if present
* 740 with ind2=2 (will not include author elements)
* 774 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== issued_with_work
"Authorized access point" (or approximation thereof) for *work that is separately cataloged but that is issued with or included in the resource described by the catalog record*

Data sources:

* 777 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

=== related_work
"Authorized access point" (or approximation thereof) for *work related to the resource described by the catalog record*

Data sources:

* 700, 710, or 711 with ind2!=2 and $t or $k present
** Label specifying type of relationship from $i if present
* 730 with ind2!=2 (will not include author elements)
** Label specifying type of relationship from $i if present
* 740 with ind2!=2 (will not include author elements)
* 765 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Is a translation of:" (or "Original language version:")
* 767 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Has been translated as:"
* 770 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Has supplement:"
* 772 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Supplement to:" or "Has parent resource:", depending on ind2 value
* 773 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Is part of:"
* 775 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Other edition:"
* 786 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present, otherwise "Data source:"
* 786 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== title_former_work
"Authorized access point" (or approximation thereof) for *work that is separately cataloged, of which the resource cataloged here is a continuation*

Data sources:

* 780 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== title_later_work
"Authorized access point" (or approximation thereof) for *work that is separately cataloged, which continues the resource cataloged here*

Data sources:

* 785 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

==== series_collocating
"Authorized access point" (or approximation thereof) representing *the series of which the resouce cataloged here is a member*

Data sources:

* 800, 810, 811, or 830


[NOTE]
====
Some subject fields follow this same pattern, so we _could_ implement a `subject_work` field that'd be modeled the same way as the other fields covered here. It would be defined as:

"Authorized access point" (or approximation thereof) for *work that is a subject of the resource cataloged here*

Data sources:

* 600, 610, 611 with $t or $k
* 630

We are currently treating these the same as any other subject headings, which is fine for now. 
====

== Examples
=== this work + included work + series
==== MARC

[source]
----
100 1 _ $aLiszt, Franz,$d1811-1886.
240 1 0 $aPiano music.$kSelections
245 1 4 $aThe complete music for solo piano.$n29$h[sound recording] /$cFranz Liszt.
700 1 2 $aLiszt, Franz,$d1811-1886.$tMagyar dallok.
700 1 2 $aLiszt, Franz,$d1811-1886.$tRhapsodies hongroises.$nNo 9.
800 1 _ $aLiszt, Franz,$d1811-1886.$tPiano music (Howard) ;$v29.$x0084-4411
----

==== Argot

[source:javascript]
----
{
  "authors":{
    "main":[
      {
        "name":"Liszt, Franz, 1811-1886."
      }
    ]
  },
  "work_citation":{
    "author":"Liszt, Franz, 1811-1886.",
    "title":"Piano music.||Selections"
  },
  "title_main":{
    "value":"The complete music for solo piano. 29 [sound recording]",
    "sort":"complete music for solo piano. 29 [sound recording]"
  },
  "statement_of_responsibility":{
    "value":"Franz Liszt."
  },
  "included_work":[
    {
      "author":"Liszt, Franz, 1811-1886.",
      "title":"Magyar dallok."
    },
    {
      "author":"Liszt, Franz, 1811-1886.",
      "title":"Rhapsodies hongroises.||No 9."
    }
  ],
  "series_collocation":{
    "author":"Liszt, Franz, 1811-1886.",
    "title":"Piano music (Howard) ;",
    "details":"29.",
    "issn":"0084-4411"
  }
}
----

==== Full record display (partial)
*The complete music for solo piano. 29 [sound recording]* +
Franz Liszt. +
London : Hyperion, p1994.

*Authors, etc.* +
Author: Liszt, Franz, 1811-1886.

*This item includes* +
http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Magyar_dallok[Magyar dallok.] +
http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Rhapsodies_hongroises[Rhapsodies hongroises.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Rhapsodies_hongroises_No_9[No 9.]

*Related items* +
More like this: http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Piano_music[Piano music.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Piano_music_Selections[Selections]

Other items in series: http://www.search.com/author_search_for/Liszt,_Franz,_1811-1886[Liszt, Franz, 1811-1886.] http://www.search.com/work_citation_begins_with/Liszt,_Franz,_1811-1886_Piano_music_Howard[Piano music (Howard) ;] 29. ISSN: 0084-4411 

==== Indexed

* *authors_main* (Author, Keyword)
** Liszt, Franz, 1811-1886.
* *author_included*  (Author, Keyword)
** Liszt, Franz, 1811-1886.
* *author_series*  (Series, Author, Keyword)
** Liszt, Franz, 1811-1886.
* *statement_of_responsibility* (Author, Keyword)
** Franz Liszt.
* *work_citation* (Work Citation for intercatalog linking)
** Liszt, Franz, 1811-1886. Piano music. Selections
* *work_citation_included*
** Liszt, Franz, 1811-1886. Magyar dallok.
** Liszt, Franz, 1811-1886. Rhapsodies hongroises. No 9.
* *work_citation_series*
** Liszt, Franz, 1811-1886. Piano music (Howard)
* *title_main* (Title, Keyword)
** complete music for solo piano. 29 [sound recording]
** The complete music for solo piano. 29 [sound recording]
* *title_variants* (Title, Keyword)
** Piano music. Selections
* *title_included* (Title, Keyword)
** Magyar dallok.
** Rhapsodies hongroises. No 9.
* *title_series* (Series, Title, Keyword)
** Piano music (Howard) ;
* *issn_series* (ISBN/ISSN, Keyword)
** 0084-4411

=== Earlier/Later titles - display info from notes, index info from linking entries
==== MARC

[source]
----
210 0 _ $aActa bot. neerl.
222 _ 0 $aActa botanica neerlandica
245 0 0 $aActa botanica Neerlandica$h[serial] :$bofficial publication of the Nederlandse Botanische Vereniging.
580 _ _ $aMerger of: Nederlandsch kruidkundig archief, and: Recueil des travaux botaniques néerlandais.
580 _ _ $aMerged with: Botanica acta, to form: Plant biology (Stuttgart, Germany).
770 0 _ $tWentia$w(DLC)   86653984$w(OCoLC)1769608
776 1 _ $tActa botanica neerlandica (Online)$w(OCoLC)38089048
780 1 4 $tNederlandsch kruidkundig archief$g1858-1951$w(OCoLC)1714426
780 1 4 $tRecueil des travaux botaniques néerlandais$w(DLC)sc 82003303$w(OCoLC)1590372
785 1 7 $tBotanica acta$x0932-8629$w(DLC)   88640720$w(OCoLC)17167709
785 1 7 $tPlant biology (Stuttgart, Germany)$x1435-8603$w(DLC)sn 99047129$w(OCoLC)41000240
----

==== Argot (partial)

[source:javascript]
----
{
  "title_variant_indexed":[
    "Acta bot. neerl.",
    "Acta botanica neerlandica"
  ],
  "work_citation_uncontrolled":[
    "Acta botanica Neerlandica"
  ],
  "title_main":{
    "value":"Acta botanica Neerlandica [serial] : official publication of the Nederlandse Botanische Vereniging."
  },
  "related_work_note":[
    "Merger of: Nederlandsch kruidkundig archief, and: Recueil des travaux botaniques néerlandais.",
    "Merged with: Botanica acta, to form: Plant biology (Stuttgart, Germany)."
  ],
  "related_work":[
    {
      "label":"Has supplement:",
      "title":"Wentia"
    }
  ],
  "title_history_index_only":[
    {
      "title":"Nederlandsch kruidkundig archief"
    },
    {
      "title":"Recueil des travaux botaniques néerlandais"
    },
    {
      "title":"Botanica acta",
      "issn":"0932-8629"
    },
    {
      "title":"Plant biology (Stuttgart, Germany)",
      "issn":"1435-8603"
    }
  ]
}
----

==== Full record display (partial)
*Acta botanica Neerlandica [serial] : official publication of the Nederlandse Botanische Vereniging.* +
Amsterdam : North-Holland Pub. Co., 1952-c1998.

*Title history and variations:* +
Merger of: Nederlandsch kruidkundig archief, and: Recueil des travaux botaniques néerlandais. +
Merged with: Botanica acta, to form: Plant biology (Stuttgart, Germany).

*Related items* +
Has supplement: http://www.search.com/work_citation_begins_with/Wentia[Wentia]

==== Indexed

* *work_citation_uncontrolled* (Work Citation for intercatalog linking)
** Acta botanica Neerlandica
* *title_main* (Title, Keyword)
** Acta botanica Neerlandica [serial] : official publication of the Nederlandse Botanische Vereniging.
* *title_variants* (Title, Keyword)
** Acta bot. neerl.
** Acta botanica neerlandica
* *title_related*
** Wentia
* *title_history_index_only* (Title, Keyword)
** Nederlandsch kruidkundig archief
** Recueil des travaux botaniques néerlandais
** Botanica acta
** Plant biology (Stuttgart, Germany)
* *issn_title_history* (ISBN/ISSN, Keyword)
** 0932-8629
** 1435-8603

=== UNCb7641376 - related work 700 with $i
==== MARC

[source]
----
100 1 _ $aSabuda, Robert,$eauthor.
245 1 4 $aThe little mermaid :$ba pop-up adaptation of the classic fairy tale /$cRobert Sabuda.
250 _ _ $aFirst edition.
264 _ 1 $aNew York :$bLittle Simon, an imprint of Simon & Schuster Children's Publishing Division,$c[2013]
700 1 _ $iBased on:$aAndersen, H. C.$q(Hans Christian),$d1805-1875.$tLille havfrue.$lEnglish.
----

==== Argot

[source,javascript]
----
{
  "work_citation_uncontrolled":[
    "Sabuda, Robert. Little mermaid"
  ],
  "title_main":{
    "value":"The little mermaid : a pop-up adaptation of the classic fairy tale",
    "sort":"little mermaid : a pop-up adaptation of the classic fairy tale"
  },
  "statement_of_responsibility":[
    {
      "value":"Robert Sabuda."
    }
  ],
  "related_work":{
    "label":"Based on:",
    "author":"Andersen, H. C. (Hans Christian), 1805-1875.",
    "title":"Lille havfrue.||English."
  }
}
----

==== Full record display (partial)
*The little mermaid : a pop-up adaptation of the classic fairy tale* +
Robert Sabuda. +
New York : Little Simon, an imprint of Simon & Schuster Children's Publishing Division, [2013] +
First edition.

*Authors, etc.* +
Author: http://www.search.com/author_search_for/Sabuda,_Robert[Sabuda, Robert,] author.

*Related items* +
Based on: http://www.search.com/author_search_for/Andersen_string[Andersen, H. C. (Hans Christian), 1805-1875.] http://www.search.com/work_citation_begins_with_Andersen_string_Lille_havfrue/[Lille havfrue.] http://www.search.com/work_citation_begins_with_Andersen_string_Lille_havfrue_English[English.]

==== Indexing

* *authors_main* (Author, Keyword)
** Sabuda, Robert, author.
* *author_related*  (Author, Keyword)
** Andersen, H. C. (Hans Christian), 1805-1875.
* *statement_of_responsibility* (Author, Keyword)
** Robert Sabuda.
* *work_citation_uncontrolled* (Work Citation for intercatalog linking)
** Sabuda, Robert. Little mermaid
* *work_citation_related*
** Andersen, H. C. (Hans Christian), 1805-1875. Lille havfrue. English.
* *title_main* (Title, Keyword)
** The little mermaid : a pop-up adaptation of the classic fairy tale
** little mermaid : a pop-up adaptation of the classic fairy tale
* *title_related* (Title, Keyword)
** Lille havfrue. English

=== UNCb8993417 - related titles in 700, with $3 and $i
==== MARC
_Some fields that would be mapped to `related_name_title` are omitted from example._

[source]
----
245 0 0 $aIf this world could stop.
264 _ 1 $a[New Haven, CT] :$bBad Wolf Music Group,$c[2014]
700 1 _ $32nd work$iMusical setting of (work):$aJoyce, James,$d1882-1941.$tUlysses.
700 1 _ $33rd work$iMusical setting of (work):$aWhiteley, Opal Stanley.$tClan of the lichens.
700 1 _ $35th work$iMusical setting of (work):$aDove, Rita.$tIf this world could stop.
----

==== Argot
[source,javascript]
----
{
  "work_citation_uncontrolled":[
    "If this world could stop."
  ],
  "title_main":{
    "value":"If this world could stop."
  },
  "related_work":[
    {
      "label":"2nd work: Musical setting of:",
      "author":"Joyce, James, 1882-1941",
      "title":"Ulysses."
    },
    {
      "label":"3rd work: Musical setting of:",
      "author":"Whiteley, Opal Stanley.",
      "title":"Clan of the lichens."
    },
    {
      "label":"5th work: Musical setting of:",
      "author":"Dove, Rita.",
      "title":"If this world could stop."
    }
  ]
}
----

==== Display 
*If this world could stop.* +
[New Haven, CT] :$bBad Wolf Music Group,$c[2014] +

RELATED ITEMS:

- 2nd work: Musical setting of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Joyce%2C%20James%2C%201882-1941.&N=0[Joyce, James, 1882-1941.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Ulysses.|Joyce%2C%20James%2C%201882-1941.&N=0[Ulysses.]
- 3rd work: Musical setting of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Whiteley%2C%20Opal%20Stanley.&N=0[Whiteley, Opal Stanley.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Clan%20of%20the%20lichens.|Whiteley%2C%20Opal%20Stanley.&N=0[Clan of the lichens.]
- 5th work: Musical setting of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Dove%2C%20Rita.%20&N=0[Dove, Rita.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=If%20this%20world%20could%20stop.|Dove%2C%20Rita.%20&N=0[If this world could stop.]
  
==== Indexed

* *work_citation_uncontrolled* (Work Citation for intercatalog linking)
** If this world could stop.
* *title_main*
** If this world could stop.
* *work_citation_related*  (Work Citation for intercatalog linking)
** Joyce, James, 1882-1941. Ulysses.
** Whiteley, Opal Stanley. Clan of the lichens.
** Dove, Rita. If this world could stop.
* *author_related*
** Joyce, James, 1882-1941.
** Whiteley, Opal Stanley.
** Dove, Rita.
* *title_related*
** Ulysses.
** Clan of the lichens.
** If this world could stop.

=== UNCb1011957 - related title in 740 with nonfiling indicator
==== MARC

[source]
----
100 1 _ $aHugo, P. J.
245 1 4 $aThe Evander gas-field,$cby P. J. Hugo. Met 'n opsomming in Afrikaans onder die opskrif: Die Gasveld Evander.
260 _ _ $aPretoria,$bGovt. Printer,$c1964.
740 4 _ $aDie Gasveld Evander.
----

==== Argot
[source,javascript]
----
{
  "work_citation_uncontrolled": [
   "Hugo, P. J. Evander gas-field"
   ],
   "title_main": {
   "value": "The Evander gas-field,",
   "sort": "Evander gas-field,"
   },
   "statement_of_responsibility": {
   "value": "by P. J. Hugo. Met 'n opsomming in Afrikaans onder die opskrif: Die Gasveld Evander."
   }
  "related_work": [
  {
   "title": "Die Gasveld Evander.",
   "title_filing": "Gasveld Evander."   
  }
 ]
}
----

==== Display (partial)
*The Evander gas-field* +
by P. J. Hugo. Met 'n opsomming in Afrikaans onder die opskrif: Die Gasveld Evander.* +
Pretoria, Govt. Printer, 1964.

*Related items:*

- http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Gasveld%20Evander.&N=0[Gasveld Evander.]

==== Indexed

* *work_citation_uncontrolled* (Work Citation for intercatalog linking)
** Hugo, P. J. Evander gas-field
* *title_main*
** The Evander gas-field,
** Evander gas-field,
* *work_citation_related*  (Work Citation for intercatalog linking)
** Gasveld Evander.
* *title_related*
** Gasveld Evander.
** Die Gasveld Evander.

=== UNCb - former/later titles (with uniform title and transcribed title) from linking fields to display

==== MARC

[source]
----
110 1 _ $aMichigan.
240 1 0 $aLaws, etc. (Session laws : 1835-1874)
245 1 0 $aActs of the Legislature of the State of Michigan$h[serial].
246 1 0 $aGeneral acts and joint and concurrent resolutions of the Legislature of the state of Michigan
246 0 8 $aLaws of Michigan
260 _ _ $aLansing [etc.] :$bW. S. George [etc.], 1836-1874.
780 0 0 $aMichigan.$sLaws, etc. (Session laws : 1824-1835)$tActs passed at the special session of the Legislative Council of the territory of Michigan
785 0 6 $aMichigan.$sLaws, etc. (Session laws : 1875-1931 : Public)$tPublic acts and joint and concurrent resolutions of the Legislature of the state of Michigan$w(OCoLC)5031140
785 0 6 $aMichigan.$sLaws, etc. (Session laws : 1875-1931 : Local)$tLocal acts of the Legislature of the state of Michigan passed at the regular session$w(OCoLC)5421450
----

==== Argot (partial)

[source:javascript]
----
{
 "title_former_work": [
  {
  "label": "Continues:",
  "author": "Michigan.",
  "title": "Laws, etc. (Session laws : 1824-1835)",
  "title_variation": "Acts passed at the special session of the Legislative Council of the territory of Michigan"
  }
 ]
}
----

==== Display (partial)
*Acts of the Legislature of the State of Michigan [serial].* +
Lansing [etc.] : W. S. George [etc.], 1836-1874.


*Authors, etc.* +
http://www.search.info/author_search_on[Michigan]

*Title history and variations:* +
Portion of title: General acts and joint and concurrent resolutions of the Legislature of the state of Michigan +
Spine title: Laws of Michigan +
Continues: http://www.search.info/author_search_on[Michigan.] http://www.search.info/works_search_on[Laws, etc. (Session laws : 1824-1835)] Acts passed at the special session of the Legislative Council of the territory of Michigan + 
Split into: http://www.search.info/author_search_on[Michigan.] http://www.search.info/works_search_on[Laws, etc. (Session laws : 1875-1931 : Public)] Public acts and joint and concurrent resolutions of the Legislature of the state of Michigan + 
Split into: http://www.search.info/author_search_on[Michigan.] http://www.search.info/works_search_on[Laws, etc. (Session laws : 1875-1931 : Local)] Local acts of the Legislature of the state of Michigan passed at the regular session


*Related items* +
More like this: http://www.search.info/author_search_on[Michigan]. http://www.search.info/works_search_on[Laws, etc. (Session laws : 1835-1874)]


==== Indexed
* *author_facet*
** Michigan
* *author_main*
** Michigan
* *work_citation*
** Michigan. Laws, etc. (Session laws : 1835-1874)
* *work_citation_uncontrolled*
** Michigan. Acts of the Legislature of the State of Michigan
* *title_main*
** Acts of the Legislature of the State of Michigan [serial].
* *title_variant*
** Laws, etc. (Session laws : 1835-1874)
** General acts and joint and concurrent resolutions of the Legislature of the state of Michigan +
** Laws of Michigan +
* *title_history_index_only*
** Laws, etc. (Session laws : 1824-1835)
** Acts passed at the special session of the Legislative Council of the territory of Michigan
** Laws, etc. (Session laws : 1875-1931 : Public)
** Public acts and joint and concurrent resolutions of the Legislature of the state of Michigan
** Laws, etc. (Session laws : 1875-1931 : Local)
** Local acts of the Legislature of the state of Michigan passed at the regular session
* *title_history_work*
** Michigan. Laws, etc. (Session laws : 1824-1835)
** Michigan. Laws, etc. (Session laws : 1875-1931 : Public)
** Michigan. Laws, etc. (Session laws : 1875-1931 : Local)
* *title_history_author*
** Michigan
