:toc:
:toc-placement!:

= Work entry pattern

The pattern used to create fields for works (i.e. often having name/title characteristics, among others, and designed to help the user navigate to other sets of records in the catalog)

This pattern is used in the following Argot fields:

* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/included_work.adoc[included_work]
* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/related_work.adoc[related_work]
* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/series_work.adoc[series_work]
* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/this_work.adoc[this_work]

toc::[]

== The pattern

* `type`: type of field (i.e. this work, included work, related work, continued work, etc.)


* `label`: Contextualizing info derived from data in field itself and/or the MARC tag or indicator values. Will not always be present.
** Display but do not index
* `author`: The author name related portion. Some works do not have an author, so will lack this part.
** indexed as `author_related`, `author_included`, or `author_series` as appropriate
** combined with `title` segment to create indexed `work_citation*` value
* `title`: The title related portion. All works must have a title, so this element is required. If there is a non-filing characters indicator, the title value omits the specified number of initial characters (and the full title is mapped to `title_nonfiling`)
** indexed as `title_related`, `title_included`, `title_series`, etc. as appropriate
** combined with `author` segment to create indexed `work_citation*` value for in-catalog hyperlink querying and possible use in autosuggest
** In Argot, this element is an array. Subelements of the title portion (data in separate subfields or otherwise split) are recorded in separate elements of the array, to support adaptive hyperlinking.
** If there is a uniform title and a title proper included in the field, uniform title is mapped to `title` and title proper is mapped to `title_variation`
* `title_nonfiling` : The title related portion, including any initial article/non-filing characters, if this value would be different than what's in `title`
** indexed as `title_related`, `title_included`, `title_series`, or `title_variant_indexed` as appropriate
** if present, combined with `author` segment to create indexed `work_citation*` value for in-catalog hyperlink querying and possible use in autosuggest
** subelements of the title portion are separated with `||` to allow for adaptive hyperlinking. This delimiter is stripped out of the display.
* `title_variation` : used to index under non-uniform title when uniform title and title proper are recorded in linking fields.
* `details`: other bib data about related work
** displayed after the author/title hyperlink, but not included in hyperlink. Will include display version of any IDs other than ISBN and ISSN
** not indexed
* `isbn`: ISBN of cited related work.
** displayed, with `ISBN:` label, at end of field display
** indexed in `isbn_related` or `isbn_included` as appropriate 
* `issn`: ISSN of cited related work.
** displayed, with `ISSN:` label, at end of field display
** indexed in `issn_related`, `issn_included`, or `issn_series` as appropriate
* `other_ids` : indexed form of IDs aside from ISBN and ISSN
** repeatable
* `display`: boolean; whether data from field should be displayed; default = true

=== Abstract example, displayed field

[source,ruby]
----
[
{'type'=>'aaaa',
 'label'=>'bbbb',
 'author'=>'cccc',
 'title'=>['dd', 'dd', 'dd'],
 'title_nonfiling'=>'eeeeee',
 'title_variation'=>'ffff',
 'details'=>'gggg hhhh',
 'isbn'=>['1111'],
 'issn'=>'2222',
 'other_ids'=>['3333','ab99']}
]
----

==== Display/behavior

*#{display name configured for type aaaa}*: bbbb: http://query.info/author_search[cccc] http://query.info/work_search_author_plus_title_portion_to[dd] http://query.info/work_search_author_plus_title_portion_to[dd] http://query.info/work_search_author_plus_title_portion_to[dd] (Some editions have title: ffff) gggg hhhh ISBN: 1111. ISSN: 2222.

==== Indexing
_I don't really care if the Solr fields end up being named aaaa_author or author_aaaa. I'm just picking one here._

* aaaa_author: aaaa
* aaaa_title: dd dd dd, eeeeee, ffff
* aaaa_work: aaaa dd dd dd
* aaaa_isbn: 1111
* aaaa_issn: 2222
* aaaa_ids: 3333, ab99

=== Abstract example, field not displayed
Typically the data in such fields has also been put in a human readable note somewhere else in the record. We don't need to show this info twice, but we can't do anything useful with the info in the note, so we use this more structured data to do some useful indexing.

[source,ruby]
----
[
{'type'=>'aaaa',
 'author'=>'cccc',
 'title'=>['dd', 'dd', 'dd'],
 'title_nonfiling'=>'eeeeee',
 'title_variation'=>'ffff',
 'isbn'=>['1111'],
 'issn'=>'2222',
 'other_ids'=>['3333','ab99']
 'display'=>'false'}
]
----

==== Display/behavior

Not applicable

==== Indexing
_I don't really care if the Solr fields end up being named aaaa_author or author_aaaa. I'm just picking one here._

* aaaa_author: aaaa
* aaaa_title: dd dd dd, eeeeee, ffff
* aaaa_work: aaaa dd dd dd
* aaaa_isbn: 1111
* aaaa_issn: 2222
* aaaa_ids: 3333, ab99

