:toc:
:toc-placement!:

= MARC relator terms and codes

toc::[]

== What are they?
Values that specify the relationship between an agent (represented by name recorded in catalog record) and resource described by the catalog record. 

== Processing notes

=== watch out for X11 fields
In X00 and X10 fields the relator term is recorded in $e.

In X11 the relator term is recorded in $j. In X11, $e is the name of a subordinate unit.

=== drop if included in name/title fields
Name/title fields are always supposed to be constructed with the main creator in the name portion.

Because the name/title field should follow rules that create structured data, catalogers are not supposed to record relator terms/codes in name/title fields.

If a relator term/code is erroneously included in a name/title field, drop it from the data mapped to Argot.

=== remove comma preceding a dropped relator term

[source]
----
=700  1\$aLandis, Thomas D.,$eauthor.$tContainer tree nursery manual.
----

`author` element should be: `Landis, Thomas D.`

=== expand relator codes to relator terms

Use translation map: marc-to-argot/lib/translation_maps/shared/relator_code_to_term.yaml

=== relator categories

Relators fall into several categories, some of which are treated differently in relevance ranking or mapping values to the author facet.

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_work_entry.adoc[`names` pattern/Argot field spec] for details. 
