:toc:
:toc-placement!:

= Author fields


*Test records*
The UNC bib records referred to by bib number in this document are at:

todo

toc::[]

== UNCb8893558 - many authors (film)
=== MARC

[source]
----
100 1 _ $aAntonin, Arnold,$efilmmaker.
245 1 3 $aLe Droit à la Parole /$cUnité audiovisuelle Centre Pétion Bolivar présente ; un film de Arnold Antonin.
264 _ 1 $a[Haiti] :$bCentre Pétion Bolivar,$c[between 2000 and 2010?]
700 1 _ $aPierre, Paul, Liliane.
700 1 _ $aPhilo, Compère.
700 1 _ $aIsaac, Harold.
700 1 _ $aPierre-Paul, Jackson.
700 1 _ $aNicolas, Vivianne.
700 1 _ $aAlphonse, Henri.
700 1 _ $aDavius, Raymond.
700 1 _ $aManmannan, Zombi,$ecomposer (expression)
700 1 _ $aJean-Claude, Martha,$d1919-$eperformer (expression)
700 1 _ $aLeon, Eddy,$ecinematographer.
700 1 _ $aCassuto, Jack,$esound designer.
700 1 _ $aGarbizu, Oscar,$eeditor of moving image work,$ecinematographer.
700 1 _ $aHenríquez, Leonardo,$eeditor of moving image work.
700 1 _ $aBrito, Beatriz,$efilm producer.
710 2 _ $aCentre Pétion-Bolivar,$epresenter.
----

=== Display

Le Droit à la Parole / Unité audiovisuelle Centre Pétion Bolivar présente ; un film de Arnold Antonin. +
Antonin, Arnold, filmmaker. +
\[Haiti\] : Centre Pétion Bolivar, [between 2000 and 2010?]

Films/videos ; DVD

*Where to find it* +
...

*Authors, etc.* +
http://www.search.info/author_index_search_on_linked_value[Antonin, Arnold], filmmaker +
http://www.search.info/author_index_search_on_linked_value[Pwierre, Paul, Liliane] +
http://www.search.info/author_index_search_on_linked_value[Philo, Compère] +
http://www.search.info/author_index_search_on_linked_value[Isaac, Harold] +
http://www.search.info/author_index_search_on_linked_value[Pierre-Paul, Jackson] +
http://www.search.info/author_index_search_on_linked_value[Nicolas, Vivianne] +
http://www.search.info/author_index_search_on_linked_value[Alphonse, Henri] +
http://www.search.info/author_index_search_on_linked_value[Davius, Raymond] +
http://www.search.info/author_index_search_on_linked_value[Manmannan, Zombi], composer +
http://www.search.info/author_index_search_on_linked_value[Jean-Claude, Martha, 1919-] performer +
http://www.search.info/author_index_search_on_linked_value[Leon, Eddy], cinematographer +
http://www.search.info/author_index_search_on_linked_value[Cassuto, Jack], sound designer +
http://www.search.info/author_index_search_on_linked_value[Garbizu, Oscar], editor of moving image work, cinematographer +
http://www.search.info/author_index_search_on_linked_value[Henríquez, Leonardo], editor of moving image work +
http://www.search.info/author_index_search_on_linked_value[Brito, Beatriz], film producer +
http://www.search.info/author_index_search_on_linked_value[Centre Pétion-Bolivar], presenter

=== Indexed

* *author_facet*
** Antonin, Arnold
** Manmannan, Zombi
** Pierre, Paul, Liliane
** Philo, Compère
** Isaac, Harold
** Pierre-Paul, Jackson
** Nicolas, Vivianne
** Alphonse, Henri
** Davius, Raymond
* *author_creator*
** Antonin, Arnold
** Manmannan, Zombi
* *author_undiff*
** Pierre, Paul, Liliane
** Philo, Compère
** Isaac, Harold
** Pierre-Paul, Jackson
** Nicolas, Vivianne
** Alphonse, Henri
** Davius, Raymond
* *author_contrib*
** Jean-Claude, Martha, 1919-
** Leon, Eddy
** Garbizu, Oscar
** Henríquez, Leonardo
** Brito, Beatriz
** Centre Pétion-Bolivar
* *author_uncat*
** Cassuto, Jack
* *keyword*
** Antonin, Arnold, filmmaker
** Pierre, Paul, Liliane
** Philo, Compère
** Isaac, Harold
** Pierre-Paul, Jackson
** Nicolas, Vivianne
** Alphonse, Henri
** Davius, Raymond
** Manmannan, Zombi, composer
** Jean-Claude, Martha, 1919- performer
** Leon, Eddy, cinematographer
** Cassuto, Jack, sound designer
** Garbizu, Oscar, editor of moving image work, cinematographer
** Henríquez, Leonardo, editor of moving image work
** Brito, Beatriz, film producer
** Centre Pétion-Bolivar, presenter

== UNCb - editor
=== MARC

[source]
----
100 1 _ $aRaleigh, Walter,$cSir,$d1552?-1618.
240 1 0 $aPoems
245 1 4 $aThe poems of Sir Walter Raleigh,$cedited with an introd. by Agnes M. C. Latham.
260 _ _ $aLondon,$bRoutledge and Paul$c[1951]
300 _ _ $alxiii, 182 p.$bports.$c18 cm.
490 1 _ $aThe Muses' library
504 _ _ $a"Previous publications": p. 175-177.
700 1 _ $aLatham, Agnes M. C.$q(Agnes Mary Christabel)$4edt$4aui
----

=== Display

The poems of Sir Walter Raleigh, edited with an introd. by Agnes M. C. Latham. +
Raleigh, Walter, Sir, 1552?-1618. +
London, Routledge and Paul [1951]

Book ; Print

*Where to find it* +
...

*Authors, etc.* +
http://www.search.info/authors_index[Raleigh, Walter, Sir, 1552?-1618] +
http://www.search.info/authors_index[Latham, Agnes M. C. (Agnes Mary Christabel)], editor, author of introduction


=== Indexed

* *author_facet*
** Raleigh, Walter, Sir, 1552?-1618
** Latham, Agnes M. C. (Agnes Mary Christabel)
* *author_creator*
** Raleigh, Walter, Sir, 1552?-1618
* *editor*
** Latham, Agnes M. C. (Agnes Mary Christabel)
* *keyword*
** Raleigh, Walter, Sir, 1552?-1618
** Latham, Agnes M. C. (Agnes Mary Christabel), editor, author of introduction
