:toc:
:toc-placement!:

= `included_work` field

"Authorized access point" (or approximation thereof) for *work included in the resource described by the catalog record*

*Uses the https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_work_entry.adoc[`work_entry` Argot pattern]*

toc::[]



== Data sources

* 700, 710, or 711 with ind2=2 and $t or $k present
** Label specifying type of relationship from $i if present
* 730 with ind2=2 (will not include author elements)
** Label specifying type of relationship from $i if present
* 740 with ind2=2 (will not include author elements)
* 774 with ind1=0 and $t or $s (may or may not include author elements)
** Label specifying type of relationship from $i if present

== Processing notes

* Relator terms/codes are not supposed to be recorded in analytic added entries. Do not map them (e4 for X00 and X10; j4 for X11) if they are in the data
* Segment/subfield delimiter '||' is provided in title portion to facilitate adaptive hyperlinking
* `type` = included
* `display` = true (so it doesn't need to be set explicitly)
* In 700, $g is mapped to `author` if it precedes the first $t and/or $k. If $g follows the first $t and/or $k, $g is mapped to `details`
* In 710, $d, g, or n is mapped to `author` if it precedes the first $t and/or $k. If $d, g, or n follows the first $t and/or $k, it is mapped to `title`

== Examples

=== 700
==== UNCb5976398 -- omit relator code

[source]
----
=700  12$aSaint-Saëns, Camille,$d1835-1921.$4cmp$tQuartets,$mviolins (2), viola, cello,$nno. 2, op. 153,$rG major
----

[source]
----
[
  {'type'=>'included',
   'author'=>'Saint-Saëns, Camille, 1835-1921.',
   'title'=>'Quartets,||violins (2), viola, cello,||no. 2, op. 153,||G major'}
]
----

==== UNCb8630424 -- omit relator term

$e is preceded by ', ' and ends with a period signifying the end of the author name segment.

We want to remove the comma that precedes a $e, but keep or provide a period at the end of the author segment.

[source]
----
=700  12$aSchwenkel, Christina,$eauthor.$tArchitecture and dwelling in the 'war of destruction' in Vietnam.
----

[source]
----
[
{'type'=>'included',
 'author'=>'Schwenkel, Christina.',
 'title'=>'Architecture and dwelling in the \'war of destruction\' in Vietnam.'}
]
----

==== UNCb8069067 -- `label` from $i; `details` from $g

[source]
----
=700  12$iFacsimile of:$aFerrini, Vincent,$d1913-2007.$tTidal wave : poems of the great strikes.$f1945$g(New York : Great-Concord Publishers)
----

[source]
----
[
{'type'=>'included',
 'label'=>'Facsimile of',
 'author'=>'Ferrini, Vincent, 1913-2007.',
 'title'=>'Tidal wave : poems of the great strikes.||1945',
 'details'=>'(New York : Great-Concord Publishers)'}
]
----


*Display*

*This item includes:*

* Facsimile of: http://query.info/on_author[Ferrini, Vincent, 1913-2007.] http://query.info/on_title[Tidal wave : poems of the great strikes.] http://query.info/on_title_to_left_plus[1945] (New York : Great-Concord Publishers)


*Indexed as*

`included_author`: Ferrini, Vincent, 1913-2007.

`included_title`: Tidal wave : poems of the great strikes. 1945

`included_work`: Ferrini, Vincent, 1913-2007. Tidal wave : poems of the great strikes. 1945


==== UNCb7416515 -- label from $3 and $i; special $i processing

See sections of https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_i.adoc[$i spec] related to deleting WEMI terms and RDA terminology replacements.

[source]
----
=700  02$3Tome 1, volume 1$iContainer of (expression):$aPlotinus.$tPeri tou kalou.$lFrench$s(Achard and Narbonne)
----

[source]
----
[
{'type'=>'included',
 'label'=>'Tome 1, volume 1: Contains',
 'author'=>'Plotinus.',
 'title'=>'Peri tou kalou.||French||(Achard and Narbonne)'}
]
----

==== UNC mock -- $g as part of `author`

[source]
----
=700  12$aName, Author,$g(Test name),$d1944-.$tTest title.
----

[source]
----
[
{'type'=>'included',
 'author'=>'Name, Author, (Test name), 1944-.',
 'title'=>'Test title.'}
]
----

=== 710

==== UNCb1619280 -- no $t, but has $k

[source]
----
=710  22$aKungliga Biblioteket (Sweden).$kManuscript.$nKB787a.$lChurch Slavic.$f1966.
----

[source]
----
[
{'type'=>'included',
 'author'=>'Kungliga Biblioteket (Sweden).',
 'title'=>'Manuscript.||KB787a.||Church Slavic.||1966.'}
]
----

==== UNCb1616558 -- $n, $d part of `author`

[source]
----
=710  12$aUnited States.$bCongress$n(94th, 2nd session :$d1976).$tMemorial services held in the House of Representatives and Senate of the United States, together with remarks presented in eulogy of Jerry L. Litton, late a Representative from Missouri.$f197.
----

[source]
----
[
{'type'=>'included',
 'author'=>'United States. Congress (94th, 2nd session : 1976).',
 'title'=>'Memorial services held in the House of Representatives and Senate of the United States, together with remarks presented in eulogy of Jerry L. Litton, late a Representative from Missouri.||197.'}
]
----

==== UNCb1298659 -- $n part of `title` 

[source]
----
=710  12$aNorth Carolina.$bBuilding Code Council.$tNorth Carolina state building code.$n1,$pGeneral construction.$n11X,$pMaking buildings and facilities accessible to and usable by the physically handicapped.
----

[source]
----
[
{'type'=>'included',
 'author'=>'North Carolina. Building Code Council.',
 'title'=>'North Carolina state building code.||1,||General construction.||11X,||Making buildings and facilities accessible to and usable by the physically handicapped.'}
]
----

==== UNCb2383742

[source]
----
=710  12$aGermany (East).$tTreaties, etc.$gGermany (West),$d1990 May 18.$f1990.
----

[source]
----
[
{'type'=>'included',
 'author'=>'Germany (East).',
 'title'=>'Treaties, etc.||Germany (West),||1990 May 18.||1990.'}
]
----

==== UNCb4364438 -- has $4

[source]
----
=710  22$aCafé Tacuba (Musical group)$4prf$t12/12
----

[source]
----
[
{'type'=>'included',
 'author'=>'Café Tacuba (Musical group)',
 'title'=>'12/12'}
]
----

=== 711 -- $e kept; $d before $t or k

==== UNCb6256550
[source]
----
=711  22$aGreat Central Fair for the U.S. Sanitary Commission$d(1864 :$cPhiladelphia, Pa.).$eCommittee on Public Charities and Benevolent Institutions.$tPhiladelphia [blank] 1864. 619 Walnut Street. To [blank] ...
----

[source]
----
[
{'type'=>'included',
 'author'=>'Great Central Fair for the U.S. Sanitary Commission (1864 : Philadelphia, Pa.). Committee on Public Charities and Benevolent Institutions.',
 'title'=>'Philadelphia [blank] 1864. 619 Walnut Street. To [blank] ...'}
]
----

==== UNCb1099159 mock -- $d and $g after $t; $x

[source]
----
=711  22$aDeutsch Foundation Conference$d(1930 :$cUniversity of Chicago).$tCare of the aged.$d2000, $f1972.$gReprint.$x1234-1234
----

[source]
----
[
{'type'=>'included',
 'author'=>'Deutsch Foundation Conference (1930 : University of Chicago).',
 'title'=>'Care of the aged.||2000,||1972.',
 'details'=>'Reprint.',
 'issn'=>'1234-1234'}
]
----

=== 730 -- $x

==== UNCb7339540

[source]
----
=730  02$aCahiers de civilisation médiévale.$pBibliographie.$x0240-8678
----

[source]
----
[
{'type'=>'included',
 'title'=>'Cahiers de civilisation médiévale.||Bibliographie.',
 'issn'=>'0240-8678'}
]
----

==== UNCb4873545 mock -- $a and $t in field

[source]
----
=730  02$aJane Pickering's lute book.$tDrewries Accord's;$oarr.
----

[source]
----
[
{'type'=>'included',
 'title'=>'Jane Pickering\'s lute book.||arr.',
 'title_variation'=>'Drewries Accord\'s;'}
]
----


==== UNCb7055039 mock -- i1 not blank or 0

[source]
----
=730  02$iContains (expression):$aMagnificent Ambersons (Motion picture).$lSpanish.
=730  42$iContains (expression):$aThe magnificent Ambersons (Motion picture).$lEnglish.
----

[source]
----
[
{'type'=>'included',
 'label'=>'Contains',
 'title'=>'Magnificent Ambersons (Motion picture).||Spanish.'},
 {'type'=>'included',
 'label'=>'Contains',
 'title'=>'Magnificent Ambersons (Motion picture).||English.',
 'title_nonfiling'=>'The magnificent Ambersons (Motion picture). English.'}
]
----

==== UNCb7644390 -- both $3 and $i in label

[source]
----
=730  02$3Guide:$iBased on (expression):$aDeutsche Geschichte.$nBand 6.
----

[source]
----
[
{'type'=>'included',
 'label'=>'Guide: Based on',
 'title'=>'Deutsche Geschichte.||Band 6.'}
]
----

=== 740

==== UNCb7182040 -- i1 not blank or 0

[source]
----
=740  42$aThe English pilot.$nThe fourth book : describing the West India navigation, from Hudson's-Bay to the river Amazones ...
----

[source]
----
[
{'type'=>'included',
 'title'=>'English pilot.||The fourth book : describing the West India navigation, from Hudson\'s-Bay to the river Amazones ...',
 'title_nonfiling'=>'The English pilot. The fourth book : describing the West India navigation, from Hudson\'s-Bay to the river Amazones ...'}
]
----

==== UNCb1094156

[source]
----
=740  \2$aIndustrial sales management game$p5.
----

[source]
----
[
{'type'=>'included',
 'title'=>'Industrial sales management game||5.'}
]
----

=== 774

*MARC fields 76X-78X are defined according to a very similar pattern which should inform the code for processing data from these fields. See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/76X-78X_linking_entry_processing.adoc[spec covering these fields as a whole] for details.*

==== UNCb8928629 mock

[source]
----
=774  08$aMasson, VeNeta.$tRehab at the Florida Avenue Grill.$dWashington, DC : Sage Femme Press, 1999$z0967368804$w(DLC)   99090707$w(OCoLC)43689896
----

[source]
----
[
{'type'=>'included',
 'author'=>'Masson, VeNeta.',
 'title'=>'Rehab at the Florida Avenue Grill.',
 'details'=>'Washington, DC : Sage Femme Press, 1999',
 'isbn'=>['0967368804'],
 'other_ids'=>['99090707', '43689896']}
]
----

==== UNCb8928629

[source]
----
=774  18$aMasson, VeNeta.$tRehab at the Florida Avenue Grill.$dWashington, DC : Sage Femme Press, 1999$z0967368804$w(DLC)   99090707$w(OCoLC)43689896
----

[source]
----
[
{'type'=>'included',
 'author'=>'Masson, VeNeta.',
 'title'=>'Rehab at the Florida Avenue Grill.',
 'isbn'=>['0967368804'],
 'other_ids'=>['99090707', '43689896'],
 'display'=>'false'}
]
----

==== UNCb8772458
[source]
----
=774  08$iContainer of (manifestation):$tSports illustrated.$gDean Smith commemorative issue (Feb. 26, 2015)$w(OCoLC)1766364
----

[source]
----
[
{'type'=>'included',
 'label'=>'Contains',
 'title'=>'Sports illustrated.',
 'details'=>'Dean Smith commemorative issue (Feb. 26, 2015)',
 'other_ids'=>['1766364']}
]
----
 
==== UNCb1629451 mock

[source]
----
=774  0\$sBulletin (North Carolina Agricultural Experiment Station)$t1991 NC Agricultural Experiment Station Bulletin$w(OCoLC)1421220
----

[source]
----
[
{'type'=>'included',
 'title'=>'Bulletin (North Carolina Agricultural Experiment Station)',
 'title_variation'=>'1991 NC Agricultural Experiment Station Bulletin',
 'other_ids'=>['1421220']}
]
----
 
==== UNCb8928629

[source]
----
=774  18$tBellevue literary review :$gvol. 2, no. 1 (Spring 2002)$x1537-5048$w(DLC)  2001211888$w(OCoLC)48166959
----

[source]
----
[
{'type'=>'included',
 'title'=>'Bellevue literary review :',
 'issn'=>'1537-5048',
 'other_ids'=>['2001211888', '48166959'],
 'display'=>'false'}
]
----

==== UNCb8772458

[source]
----
=774  08$iContainer of  (manifestation):$aDean Smith, 1931-2015.$dChicago, Illinois : Triumph Books, [2015]$w(OCoLC)908583564
----

*No Argot output* because there is no title





