:toc:
:toc-placement!:

= Notes fields

*See the https://github.com/trln/data-documentation/tree/master/argot[Argot Excel file available here] or the https://github.com/trln/data-documentation/blob/master/argot/_mappings.csv[mappings.csv file] for field/subfield specific instructions.*

*Test records*
The UNC bib records referred to by bib number in this document are at:
https://github.com/trln/extract_marcxml_for_argot_unc/blob/master/output/testing/notes.xml

toc::[]

== Patterns of mapping MARC fields to Argot
=== One MARC tag-to-separate Argot field treatment
Some MARC note fields are extracted into separate, specific Argot fields. This is because:

* There is some special treatment for the field in the system; AND/OR
* We deem the data in the note to be different/important enought to set it apart from other notes, either in a separate area, or with a separate primary label.

Examples are:

* 505 Contents note (TOC from Syndetics overrides display of this field; if no Syndetics data present, show separate from other notes as Contents)
* 520 Summary note (Similar to 505) 
* 511 Participant or Performer Note (display as separate field)

=== Multiple MARC tag-to-Argot field for note category
Some MARC note fields fall into general categories that should be displayed with other data. For example:

* Notes about publication history or issuance should be displayed with publication details
* Notes about accompanying materials, physical description, or system requirements should be displayed with other physical description information
* Local copy/item specific notes need to be shown separately

=== General notes field in Argot
Other MARC notes fields are handled in a general notes field.

=== Ignored notes
Some notes are NOT displayed or indexed.

Details on all ignored notes fields below in ignored notes section.

== Behavior of notes in TRLN Discovery
=== Displayed notes
All notes extracted into Argot will be displayed.

=== Indexed note content

* Note content is searchable in the keyword index.
* *Some note fields are NOT indexed.* These fields do not appear to meaningfully contribute to discovering the item described by the record and/or would introduce noise into the index and results sets
* Note labels and other parts of notes fields that contribute more noise than discoverability are NOT indexed.

== Local notes
It will be up to individual institutions to decide how their local notes (590) field data is mapped to the Argot `note_local` field.

In Endeca, we had the option of mapping this to either the non-indexed `Notes` property (using prepipeline data label `590`) or the `Indexed Notes` property (using prepipeline data label `590_indexed`).

The `note_local` field provides the same flexibility. 

== Special patterns in notes field processing
=== Field-refers-to label (from $3) needed
See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_3.adoc[spec document for $3] for more details. 

=== Label generated from MARC tag and/or indicator value(s) and/or subfield definitions
Data in some note fields looks very weird without a label. http://search.trln.org/search?id=UNCb1240038[Here's an example record in SearchTRLN]:

NOTES

- 1943-64. 1 v.
- No earlier abstracts published?
- Title varies slightly.
- (GL)


The same MARC field is often used to record different types of data, with indicator coding controlling the meaning of the field.

Some subfields are used to record data that needs its own label in order for the data (and its relationship to the rest of the data in the field) to make sense.

We should use the coding of the MARC data to display data to end users in a meaningful way.

*Each MARC field's indicators and subfields are defined separately, so this type of processing will be very field-specific.*

==== 521 example 1

 521 2 _ $a6-12$bMorgan Reynolds Incorporated

Without generating a label using the MARC tag and indicator coding, we end up with a cryptic note displayed:

 6-12 Morgan Reynolds Incorporated

Or we can meaningfully label/display the info:

 For grade(s): 6-12. (source: Morgan Reynolds Incorporated)


==== 521 example 2
 521 1 _ $aAdult.$bBrodart

Should be displayed:

 For age(s): Adult. (source: Brodart)

=== Label created from $i

[WARNING]
.$i is not always a label
=====================================================================
In the following fields, $i is a non-label data element: 

- 514
- 542
- 552
- 583
=====================================================================

=== Something else
Of course some fields are just weird and complicated.

One example is the 518 where you have the option of putting a natural language note in the $a. OR you can bust up the information into separately coded elements where the $p sort of functions as a label.

* May need $3 label
** b7832943a: 	518 _ _ $3CD 2$oRecorded$d2004 November,$pAuditorium (Chiesa) di San Salvatore a Rodengo, Brescia, Italy.
** b7832943a: 	518 _ _ $3CD 1$oRecorded$d2001 October,$pIstituo di musica Antica Academia Monte Regalis, Mondovi, Italy.
* If $a, treat like basic textual note
** b1200040a: 	518 _ _ $a"Recorded in the formerly monastic church of St. Ottilie in Möschenfeld near Munich. Date of recording, May, 1967."
* If any subfields occur after $a, remove them and throw in a space -- these are probably mis-coded and should be cleaned up in the data, but are pretty innocuous and seem easy-ish to deal with
** b8966892a: 	518 _ _ $aBroadcast$dFriday, November 18 (10:01-11:00 p.m. Est), on ABC.
* If no $a... $o 

== Argot note pattern

[source,javascript]
----
{
  "note_field_name":[
    {
      "label":"Label for the note",
      "value":"The displayed content of the note",
      "indexed_value":"The part of above value that should be indexed, if it is different from value",
      "indexed":"Boolean: true or false",
      "lang":"Script/language code of value"
    }
  ]
}
----

* `label`: Optional. May be set from $3, $i, and/or MARC field tag + indicator values.
* `value`: *Required.* The note that will be displayed. If there is no `indexed_value` and `indexed` is not false, this is also the indexed note content.
* `indexed_value`: Optional. This should only be populated if:
** `indexed` == true; AND
** `indexed_value` needs to be different than `value`
* `indexed`: Optional. If not explicitly set, assumed to equal true. In other words, default assumption is that a note field will be indexed.
* `lang`: Script/language code for non-Roman values, to trigger special language parsing in Solr

[NOTE]
====
Only *some* Argot notes fields utilize the notes pattern.

Some notes use:

* https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_index_and_display_value.adoc[`index_and_display_value`] pattern

====

== Organization of examples

* Argot field
** MARC tag
*** Example from specific record
**** MARC
**** Argot 
**** Display (if there is anything notable to say/show)
**** Indexing/search (if there is anything notable to say/show)


== Examples: note_access_restrictions

Field is NOT indexed.

=== 506
==== UNCb4320053
===== MARC

[source]
----
506 1 _ $aAccess limited to UNC Chapel Hill-authenticated users.$fLimited to one (1) concurrent user
----

===== Argot

[source,javascript]
----
{
  "note_access_restrictions":[
    "Access limited to UNC Chapel Hill-authenticated users. Limited to one (1) concurrent user"
    ]
}
----

== Examples: note_admin_history

* Field is indexed
* Uses https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_index_and_display_value.adoc[`index_and_display_value`] pattern

=== 545 (ind1=1)
==== UNCb5251752

===== MARC
[source]
-----
545 1 _ $aSpurlock-Neal Company started out as a drug store in Nashville, Tennessee in 1868, expanding later into a wholesale distributor of products from cough medicine and sarsaparilla to candies and syrups. By 1910, the company had become one of the largest retail druggists in the South.
-----

===== Argot
[source,javascript]
----
{
  "note_admin_history":[
      { "value" => "Spurlock-Neal Company started out as a drug store in Nashville, Tennessee in 1868, expanding later into a wholesale distributor of products from cough medicine and sarsaparilla to candies and syrups. By 1910, the company had become one of the largest retail druggists in the South." }
  ]
}
----

== Examples: note_binding

* Field is indexed

=== 563

==== UNCb8681679

===== MARC

[source]
----
563 _ _ $aPerfect bound softcover. Four-color offset lithography. Illustrated paper wrappers with flaps. Housed in foldout die-cut box with gold foil origami crane inserted into cover slot. Signed and numbered by the artist on book's front cover flap -- Description from$uhttp://vampandtramp.com/finepress/s/clarissa-sligh.html
----

===== Argot

[source,javascript]
----
{
  "note_binding":[
  {
    "value":"Perfect bound softcover. Four-color offset lithography. Illustrated paper wrappers with flaps. Housed in foldout die-cut box with gold foil origami crane inserted into cover slot. Signed and numbered by the artist on book's front cover flap -- Description from http://vampandtramp.com/finepress/s/clarissa-sligh.html"
  }
 ]
}
----

==== UNCb2559560

* Do NOT extract/map based on $5 See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_5.adoc[$5 spec doc] for details.

===== MARC
[source]
----
563 _ _ $aNLM copy bound in contemporary Cambridge-style binding.$5DNLM
----

===== Argot

*NONE*

==== UNCb4254290

* Label from $3

===== MARC

[source]
----
563 _ _ $aSome pages uncut.$3(Health Sciences Library, c. 1)
----

===== Argot

[source,javascript]
----
{
  "note_binding":[
    {
      "label":"(Health Sciences Library, c. 1):",
      "value":"Some pages uncut."
    }
  ]
}
----

== Examples: note_biographical

* Field is indexed

=== 545 (ind1=~/ 0/)
==== UNCb3784489

===== MARC
[source]
-----
545 _ _ $aEllen Walters, filmmaker, teacher, and anthropologist of Laurinburg, N.C., has produced and directed several documentary films on southern culture.
-----

===== Argot
[source,javascript]
----
{
  "note_biographical":[
      "Ellen Walters, filmmaker, teacher, and anthropologist of Laurinburg, N.C., has produced and directed several documentary films on southern culture."
  ]
}
----

== Examples: note_cited_in

* Field is indexed

=== 510

==== UNCb1189165

* Provide display label for $x 

===== MARC

[source]
----
=510  2\$aChemical abstracts$x0009-2258$b1968-1986.
----

===== Argot

[source,javascript]
----
{
  "note_cited_in":[
  {
    "value":"Chemical abstracts ISSN 0009-2258 1968-1986.",
    "indexed_value":"Chemical abstracts 1968-1986."
   }
 ]
}
----

==== UNCb5157750

* Set label from $3

===== MARC

[source]
----
=510  4\$3Arcadelt, Terzo libro$aRISM A/I,$cA1374.
=510  4\$3Arcadelt, Terzo libro$aRISM B/I,$c1539-23.
=510  4\$3Arcadelt, Secondo libro$aRISM A/I,$cA1371.
=510  4\$3Arcadelt, Quinto libro$aRISM A/I,$cA1382.
=510  4\$3Arcadelt, Quinto libro$aRISM B/I,$cB1544-16.
----

===== Argot

[source,javascript]
----
{
  "note_cited_in":[
  {
    "label":"Arcadelt, Terzo libro",
    "value":"RISM A/I, A1374."
  },
  {
    "label":"Arcadelt, Terzo libro",
    "value":"RISM B/I, 1539-23."
  },
  {
    "label":"Arcadelt, Secondo libro",
    "value":"RISM A/I, A1371."
  },
  {
    "label":"Arcadelt, Quinto libro",
    "value":"RISM A/I, A1382."
  },
  {
    "label":"Arcadelt, Quinto libro",
    "value":"RISM B/I, B1544-16."
  }
 ]
}
----

== Examples: note_copy_version

* Field is not indexed

=== 562
==== UNCb7426360 mock

* Label from $3

===== MARC
[source]
-----
562 _ _ $3v. 2$aP. 140 is wrongly numbered 410.
-----

===== Argot
[source,javascript]
----
{
  "note_copy_version":[
      "v. 2: P. 140 is wrongly numbered 410."
  ]
}
----

===== Display

[NOTE]
====
I'm on the fence about where this belongs, though the `full display` column in the Argot fields.csv has it in "Other details > (item/copy-specific description cluster) > (no label)"

Separated out because I imagine this is something some institutions may want to treat differently.

It sometimes seems to be used for manifestation-level differences (i.e. all in a printing run would have same pagination error or advertisement included). However, sometimes it looks to be used for literal copy-specific notes (which would be local). 
====

== Examples: note_data_quality
=== 514
==== Complex processing rules

Produce a separate note with the label listed below for data in the given subfields.

* Attribute accuracy -- abc
* Logical consistency -- d
* Horizontal position accuracy -- fgh
* Vertical position accuracy -- ijk
* Cloud cover -- m
* Other data details -- euz

Insert ` -- ` (space hyphen hyphen space) between subfield values in all of the above *except* `Other data details`, where the subfield values should be separated by spaces only.

==== mock 1
From http://www.loc.gov/marc/bibliographic/bd514.html with a minor edit

===== MARC

[source]
----
514 _ _ $bEstimated to be 98.5%.$cVillage names compared to source map -- all match, therefore errors are possible only if source maps are incorrect.$dNode-to-line, line-to-area topological relationships maintained. Line and area attributes maintained. GRASS 4.0 program "v.support" checks topological relationships.$eAll incorporated limits shown on USGS quads were digitized.$fThe accuracy of this data is based upon the use of the source maps ... [subfield $f shortened in this example]$m8.42%
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Attribute accuracy: Estimated to be 98.5%. -- Village names compared to source map -- all match, therefore errors are possible only if source maps are incorrect.",
    "Logical consistency: Node-to-line, line-to-area topological relationships maintained. Line and area attributes maintained. GRASS 4.0 program \"v.support\" checks topological relationships.",
    "Other data details: All incorporated limits shown on USGS quads were digitized.",
    "Horizontal position accuracy: The accuracy of this data is based upon the use of the source maps ... [subfield $f shortened in this example]",
    "Cloud cover: 8.42%"
  ]
}
----

===== Suggested display
|====================
| Data quality: | Attribute accuracy: Estimated to be 98.5%. -- Village names compared to source map -- all match, therefore errors are possible only if source maps are incorrect.
| | Logical consistency: Node-to-line, line-to-area topological relationships maintained. Line and area attributes maintained. GRASS 4.0 program \"v.support\" checks topological relationships.
| | Other data details: All incorporated limits shown on USGS quads were digitized.
| | Horizontal position accuracy: The accuracy of this data is based upon the use of the source maps ... [subfield $f shortened in this example]
| | Cloud cover: 8.42%
|====================


==== mock 2
From http://www.loc.gov/marc/bibliographic/bd514.html

===== MARC

[source]
----
514 _ _ $aThe map layer that displays Special Feature Symbols shows the approximate location of small (less than 2 acres in size) areas of soils ... [subfield $a shortened in this example] $dQuarter quadrangles edited and joined internally and to surrounding quads. All known errors corrected.$eThe combination of spatial linework layer, Special Feature Symbols layer, and attribute data are considered a complete SSURGO dataset.$fThe actual on ground transition between the area represented by the Special Feature Symbol and the surrounding soils generally is very narrow with a well defined edge. The center of the feature area was compiled and digitized as a point. The same standards for compilation and digitizing used for line data were applied to the development of the Special Feature Symbols layer.
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Attribute accuracy: The map layer that displays Special Feature Symbols shows the approximate location of small (less than 2 acres in size) areas of soils ... [subfield $a shortened in this example]",
    "Logical consistency: Quarter quadrangles edited and joined internally and to surrounding quads. All known errors corrected.",
    "Other data details: The combination of spatial linework layer, Special Feature Symbols layer, and attribute data are considered a complete SSURGO dataset.",
    "Horizontal position accuracy: The actual on ground transition between the area represented by the Special Feature Symbol and the surrounding soils generally is very narrow with a well defined edge. The center of the feature area was compiled and digitized as a point. The same standards for compilation and digitizing used for line data were applied to the development of the Special Feature Symbols layer."
  ]
}
----

==== mock 3
From http://www.loc.gov/marc/bibliographic/bd514.html

===== MARC

[source]
----
514 _ _ $bApproximately 95%
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Attribute accuracy: Approximately 95%"
  ]
}
----

==== mock 4
From http://www.loc.gov/marc/bibliographic/bd514.html

===== MARC

[source]
----
514 _ _ $aHorizontal position accuracy 1-3 meters$fDifferential GPS$g3 meters$hStatic tests$iBar test$jOne foot$kBar check.
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Attribute accuracy: Horizontal position accuracy 1-3 meters",
    "Horizontal position accuracy: Differential GPS -- 3 meters -- Static tests",
    "Vertical position accuracy: Bar test -- One foot -- Bar check."
  ]
}
----

==== mock 5
From http://www.loc.gov/marc/bibliographic/bd514.html

===== MARC

[source]
----
514 _ _ $zCompleteness:$u<URI>
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Other data details: Completeness: <URI>"
  ]
}
----

==== UNCb4265192
===== MARC

[source]
----
514 _ _ $aNED has a resolution of one arc-second (approximately 30 meters) for the conterminous United States, Hawaii and a resolution of two arc-seconds for Alaska$g30 meters$uhttp://spatialnews.geocomm.com/whitepapers/sdts-demmap.pdf$zThe Spatial data and transfer standard mapping of the USGS digital elevation model.$uhttp://gisdata.usgs.net/NED/fgdcmetadata.asp$zNational elevation dataset FGDC compliant metadata.
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Attribute accuracy: NED has a resolution of one arc-second (approximately 30 meters) for the conterminous United States, Hawaii and a resolution of two arc-seconds for Alaska",
    "Horizontal position accuracy: 30 meters",    
    "Other data details: http://spatialnews.geocomm.com/whitepapers/sdts-demmap.pdf The Spatial data and transfer standard mapping of the USGS digital elevation model. http://gisdata.usgs.net/NED/fgdcmetadata.asp National elevation dataset FGDC compliant metadata."
  ]
}
----

==== UNCb8346897
===== MARC

[source]
----
514 _ _ $zConforms To:$eCombined Arms Research Library Digital Library
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Other data details: Conforms To: Combined Arms Research Library Digital Library"
  ]
}
----

==== UNCb6855640
===== MARC

[source]
----
514 _ _ $aThe attribute accuracy is unknown.$dNo duplicate features are present.$eAfter processing, the data set is checked for number of records, attribute names, and values compared with source materials.
----

===== Argot

[source,javascript]
----
{
  "note_data_quality":[
    "Attribute accuracy: The attribute accuracy is unknown.",
    "Logical consistency: No duplicate features are present.",
    "Other data details: After processing, the data set is checked for number of records, attribute names, and values compared with source materials."
  ]
}
----

== Examples: note_described_by

* This note is NOT indexed

* If ind1 is blank, prepend "Indexes: " to field (or insert it after any $3 label present)
* If ind1 = 0, prepend "Finding aids: " to field (or insert it after any $3 label present)

=== 555

==== UNCb4157517

[source]
----
=555  0\$aList of items in front of folder 39.
----

[source,javascript]
----
{
  "note_described_by":[
      'Finding aids: List of items in front of folder 39.'
  ]
}
----

==== UNCb1206579 mock

[source]
----
=555  \\$31961-1973$aAnnual index published separately each year.
=555  \\$31974-$aAnnual index published with the last issue of each year.
=555  \\$3v. 1-10, 1962-1971$aCumulative index published separately in 1 volume.
----

[source,javascript]
----
{
  "note_described_by":[
    '1961-1973: Indexes: Annual index published separately each year.',
    '1974-: Indexes: Annual index published with the last issue of each year.',
    'v. 1-10, 1962-1971: Indexes: Cumulative index published separately in 1 volume.'
  ]
}
----

==== UNCb1302201 mock

[source]
----
=555  8\$aCumulative title, document number and subject index available online with links to select online titles.
----

[source,javascript]
----
{
  "note_described_by":[
    'Cumulative title, document number and subject index available online with links to select online titles.'
  ]
}
----

== Examples: note_dissertation
=== 502
==== Complex processing rules
*See _Shift off subfield list before further processing_ section of https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_6.adoc[$6 spec sheet]*

===== Punctuation provision rules for building field value from component subfields (i.e. when there are subfields other than a present)

* Precede all non-initial subfield values except $d with `--`
* Precede non-initial $d with `, ` (comma space)

===== Logic

* If first subfield is a...
** If there are no other subfields (b,c,d,g, or o)
*** Take contents of $a.
*** See UNCb9058990 example below.
** And it is followed by subfields b,c,d,g, or o
*** Build note field from all extractable subfield elements present, following punctuation provision rules.
*** See mock example below.
* If first subfield is b or g
** Build note field from all subfield elements present, following punctuation provision rules.
** See UNCb7386333 and UNCb1511334 examples below.
* Else...
** Provide fake $b value "Thesis/dissertation" to use at beginning of field
** Build note field from all subfield elements present, following punctuation provision rules
** See UNCb6856070 example below.

==== UNC mock example
===== MARC

[source]
----
502 _ _ $aThesis$bPh.D$cUniversity of North Carolina at Chapel Hill.
----

===== Argot
[source,javascript]
----
{
  "note_dissertation":[
      "Thesis--Ph.D--University of North Carolina at Chapel Hill."
  ]
}
----

==== UNCb9058990

===== MARC
[source]
----
502 _ _ $aThesis (Ph. D.)--University of Lancaster, Lancashire, England.
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
      "Thesis (Ph. D.)--University of Lancaster, Lancashire, England."
  ]
}
----

==== UNCb7386333

===== MARC

[source]
----
502 _ _ $gRecital document$bMaster of Music in Performance and Vocal Pedagogy$cUniversity of Texas at San Antonio$d2012.
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
      "Recital document--Master of Music in Performance and Vocal Pedagogy--University of Texas at San Antonio, 2012."
  ]
}
----

==== UNCb1511334

===== MARC
[source]
----
502 _ _ $bPh. D.$cUniversity of North Carolina$d1976
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
      "Ph. D.--University of North Carolina, 1976"
  ]
}
----

==== UNCb6856070
===== MARC

[source]
----
502 _ _ $cBremen International Graduate School of Social Sciences$d2008
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
      "Thesis/dissertation--Bremen International Graduate School of Social Sciences, 2008"
  ]
}
----

== Examples: note_file_type

* Field is NOT indexed

=== 516

==== UNCb3511387

* No label provided

===== MARC

[source]
----
516 8 _ $aISO 9660 format; data files in dBase format; text files in ASCII format
----

===== Argot

[source,javascript]
----
{
  "note_file_type":[
    "ISO 9660 format; data files in dBase format; text files in ASCII format"
    ]
}
----

==== UNCb4829326

* Label provided

===== MARC

[source]
----
516 _ _ $aPDF
----

===== Argot

[source,javascript]
----
{
  "note_file_type":[
    "PDF"
    ]
}
----

== Examples: note_general
=== 500

[NOTE]
====
500 is mapped to `note_general` if it lacks a whitelisted $5 value for the institution creating the Argot.
====

==== UNCb1055018
===== MARC
[source]
----
500 _ _ $a"This edition is limited to 750 copies, and the type has been distributed."
----

===== Argot
[source,javascript]
----
{
  "note_general":[
    {
      "value":"\"This edition is limited to 750 copies, and the type has been distributed.\""
    }
  ]
}


----

==== UNCb1004068
===== MARC

[source]
----
500 _ _ $aTranslation is based on a photocopy of the original MS. in the Library of Pembroke College, Oxford.
500 _ _ $a"Published under the auspices of the Library of the New York Academy of Medicine."
500 _ _ $3c. 1$aInscribed: "Benson R. Wilcox"--Fly leaf.$5NcU-H
541 _ _ $aPresented by Benson R. Wilcox$c(Gift :$d2010 :$fHealth Sciences Library,$3c. 1)
561 _ _ $3c. 1$aBookplate: "Ex Libris Benson R. Wilcox M.D."--Inside front cover.$5NcU-H
----

===== Argot
[source,javascript]
----
{
  "note_general":[
    {
      "value":"Translation is based on a photocopy of the original MS. in the Library of Pembroke College, Oxford."
    },
    {
      "value":"\"Published under the auspices of the Library of the New York Academy of Medicine.\""
    }
    ]
    }

----

=== 504

[IMPORTANT]
====
*Processing rule*

If $b is present, prepend "Number of references: " to its value.
====

==== UNCb4706138
===== MARC

[source]
----
504 _ _ $b36 references.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"Number of references: 36 references.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb2019098
===== MARC

[source]
----
504 _ _ $aBibliography : p. 81-83.$b52.
----

===== Argot
[source,javascript]
----
{
  "note_general":[
    {
      "value":"Bibliography : p. 81-83. Number of references: 52.",
      "indexed":"false"
    }
  ]
}
----

=== 518

==== UNCb7612476

* label from $3
* content of note broken down into specific subfields

===== MARC

[source]
----
518 _ _ $31st-4th works$orecorded$d2013 January 25-27$pSt. Mary's Church, Chilham, Kent.
518 _ _ $35th work$orecorded$d2013 January 31$pNo. 2 Studio, Abbey Road, London.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"1st-4th works:",
      "value":"recorded 2013 January 25-27 St. Mary's Church, Chilham, Kent.",
      "indexed":"false"
    },
    {
      "label":"5th work:",
      "value":"recorded 2013 January 31 No. 2 Studio, Abbey Road, London.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb1818381

* no label
* full note in $a

===== MARC

[source]
----
518 _ _ $aRecorded June 11-18, 1981, Corbett Auditorium, College-Conservatory of Music, University of Cincinnati.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"Recorded June 11-18, 1981, Corbett Auditorium, College-Conservatory of Music, University of Cincinnati.",
      "indexed":"false"
    }
----

=== 521

==== Complex processing rules

*Provide label based on value of indicator 1.*

[%header,cols=2*]
|====================
| i1 value | label value
| blank | For audience(s):
| 0 | For grade(s):
| 1 | For age(s):
| 2 | For grade(s):
| 3 | For audience(s):
| 4 | For audience(s):
| 8 | LABEL NOT PROVIDED
|====================

*Separate repeated $a values with `; ` (semicolon space)* +
See UNCb3388632 below

*Create parenthetical source statement from $b value if present* +
See UNCb6569074, UNCb5764837 examples below.

*Create label from $3 value if present*

*Field is NOT indexed.*

==== UNCb1301072

* No label (i1=8)

===== MARC

[source]
----
521 8 _ $a"The professional bulletin for Army engineers."
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"\"The professional bulletin for Army engineers.\"",
      "indexed":"false"
    }
  ]
}
----

==== UNCb6569074

* Label based on indicator
* Source statement from $b

===== MARC

[source]
----
521 _ _ $aScholarly & Professional$bIEEE Computer Society Press
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"For audience(s):",
      "value":"Scholarly & Professional (source: IEEE Computer Society Press)",
      "indexed":"false"
    }
  ]
}
----

==== UNCb6424285

* Label based on indicator

===== MARC

[source]
----
521 0 _ $a4.5.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"For grade(s):",
      "value":"4.5.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb3731759 mock

* Label based on indicator

===== MARC

[source]
----
521 1 _ $a3 to 7.$3workbook:
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"Workbook: For age(s):",
      "value":"3 to 7.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb5764837

* Label based on indicator
* Source statement from $b

===== MARC

[source]
----
521 2 _ $a7-12.$bBrodart
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"For grade(s):",
      "value":"7-12. (source: Brodart)",
      "indexed":"false"
    }
  ]
}
----

==== UNCb3388632

* Label based on indicator

===== MARC

[source]
----
521 3 _ $aOlder adults$ayounger persons with disabilities.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"For audience(s):",
      "value":"Older adults; younger persons with disabilities.",
      "indexed":"false"
    }
  ]
}
----

=== 522

==== UNCb8954715

* Label not provided (i1=8)

===== MARC

[source]
----
522 8 _ $a"The non-OECD countries in this report comprise ... central and Eastern European countries (CEECs), major New Indepenent States (NIS), and China, Brazil, and India ..."
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"\"The non-OECD countries in this report comprise ... central and Eastern European countries (CEECs), major New Indepenent States (NIS), and China, Brazil, and India ...\""
    }
  ]
}
----

==== UNCb8420259

* label provided (i1=blank)

===== MARC

[source]
----
522 _ _ $aAsia-Pacific ; Africa ; Near East ; Americas ; Europe ; Argentina ; Uruguay ; Brazil ; Chile ; Peru.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"Geographic coverage:",
      "value":"Asia-Pacific ; Africa ; Near East ; Americas ; Europe ; Argentina ; Uruguay ; Brazil ; Chile ; Peru."
    }
  ]
}
----

=== 526
==== Complex processing rules
*Label set based on i1 value and $i if present*

* i1=0 : Label = "Reading program:"
* i1=8 : no label
* i1=anything else : no label (invalid/undefined values)

If i1=0 and $i present, label = "Reading program: #{$ivalue}:"

*Add punctuation between subfields*

" -- " (space hyphen hyphen space)

*Provide labels for cryptic subfields*

[%header,cols=2*]
|====================
| subfield | prepend
| a | (nothing)
| b | "Interest level: "
| c | "Reading level: "
| d | "Title points: "
| z | (nothing)
|====================

*When $a is the sole subfield*

* Do nothing special, in which case `value` and `indexed value` will be identical; OR
* Do an extra thing to omit setting `indexed_value`

I probably wouldn't do anything special. This is not THAT common of a note, and the contents of the note tend to be relatively brief.

*When there is no $a*

* Do nothing special, in which case, whatever else is in `value` will be indexed; OR
* Do an extra thing to add `indexed:false`

I probably wouldn't do anything special. This field doesn't even make sense without a $a, so I suspect any instances missing a $a need to be deleted or corrected anyway. There shouldn't be too many of them.

==== UNCb8186117 mock

* label from i1 and $i
* cryptic subfield labels and between-subfield punctuation provided

===== MARC

[source]
----
526 0 _ $aAccelerated Reader$bGrades 5-8$c4.9$d10$xSD$zQuiz 161076$zEnglish fiction.$i2017 addition to
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"Reading program: 2017 addition to:"
      "value":"Accelerated Reader -- Interest level: Grades 5-8 -- Reading level: 4.9 -- Title points: 10 --  Quiz 161076 -- English fiction.",
      "indexed_value":"Accelerated Reader"
    }
  ]
}
----

==== UNCb7402489

* no label

===== MARC

[source]
----
526 8 _ $aCE credits available from Psychotherapy.net
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"CE credits available from Psychotherapy.net"
    }
  ]
}
----

=== 536

==== UNCb3455797

* label provided (constant)

===== MARC

[source]
----
536 _ _ $aHeadquarters, U.S. Army Corps of Engineers.$d4A162784,$dAT 45,$dFF-XS5.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"Funding details:",
      "value":"Headquarters, U.S. Army Corps of Engineers. 4A162784, AT 45, FF-XS5."
    }
  ]
}
----

=== 546

==== UNCb5753246

===== MARC

[source]
----
500 _ _ $aIncludes index.
546 _ _ $3Text$aLatin
546 _ _ $3Introduction and notes$aGerman
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"Includes index."
    },
    {
      "label":"Text:",
      "value":"Latin"
    },
    {
      "label":"Introduction and notes:",
      "value":"German"
    }
  ]
}
----

=== 556

* Values from this field are NOT indexed

==== UNCb4430475

* Label provided

===== MARC

[source]
----
556 _ _ $aIPEDS peer analysis system user manual, self guided tutorials.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
     {
       "label":"Documentation:",
       "value":"IPEDS peer analysis system user manual, self guided tutorials.",
       "indexed":"false"
     }
    ]
}
----

==== UNCb3226895

* Label not provided

===== MARC

[source]
----
556 8 _ $aAccompanied by user's manual (in English and French). Title on manual: Mayer international auction records on CD-ROM.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"Accompanied by user's manual (in English and French). Title on manual: Mayer international auction records on CD-ROM.",
      "indexed":"false"
    }
  ]
}
----

=== 585

==== UNCb4794350

* Label from $3

===== MARC

[source]
----
585 _ _ $3Paintings, calligraphies, seal carvings$aExhibited: University Museum and Art Gallery, The University of Hong Kong, sponsored by Mr. Frankie W., October 29, 2004-December 9, 2004.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"Paintings, calligraphies, seal carvings:",
      "value":"Exhibited: University Museum and Art Gallery, The University of Hong Kong, sponsored by Mr. Frankie W., October 29, 2004-December 9, 2004."
    }
  ]
}
----

==== UNCb9057170

* No label

===== MARC

[source]
----
585 _ _ $a"Published in conjunction with the exhibition Wiener Werkstätte 1903-1932 : the luxury of beauty, Neue Galerie New York, October 26, 2017-January 29, 2018" (title page verso).
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"\"Published in conjunction with the exhibition Wiener Werkstätte 1903-1932 : the luxury of beauty, Neue Galerie New York, October 26, 2017-January 29, 2018\" (title page verso)."
    }
  ]
}
----

=== 586

==== UNCb4336828
===== MARC

[source]
----
586 _ _ $aAcademy Awards, 2003: Best Documentary, Features (Michael Moore, Michael Donovan)
586 _ _ $aCannes Film Festival, 2002: 55th Anniversary Prize (Michael Moore)
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"Academy Awards, 2003: Best Documentary, Features (Michael Moore, Michael Donovan)"
    },
    {
      "value":"Cannes Film Festival, 2002: 55th Anniversary Prize (Michael Moore)"
    }
  ]
}
----

==== UNCb7672018
===== MARC

[source]
----
586 _ _ $6880-05$3Ana$aDai 150-kai Akutagawa-shō, 2014
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "label":"Ana:",
      "value":"Dai 150-kai Akutagawa-shō, 2014"
    }
  ]
}
----

== Examples: note_issuance
=== 550
==== UNCb1234211
===== MARC

[source]
----
245 0 0 $aAmerican birds$h[serial].
260 _ _ $a[New York,$bNational Audubon Society]
550 _ _ $aVols. for <Feb.-June 1971> published by the National Audubon Society in collaboration with the U.S. Fish and Wildlife Service.
----

===== Argot

[source,javascript]
----
{
  "note_issuance":[
      "Vols. for <Feb.-June 1971> published by the National Audubon Society in collaboration with the U.S. Fish and Wildlife Service."
    ]
}
----

===== Display suggestion
*American birds [serial].* +
[New York, National Audubon Society] +

*OTHER DETAILS* +
[New York, National Audubon Society] +
Vols. for <Feb.-June 1971> published by the National Audubon Society in collaboration with the U.S. Fish and Wildlife Service.

== Examples: note_local
=== 500, 541, 561
*500* is mapped to `note_local` if whitelisted $5 for institution creating Argot is present.

*541* is always mapped to `note_local`. This field has many elements and their use is not well-standardized. Rules for mapping this field are assumed to be completely institution-specific. 

*561* is always mapped to `note_local` if not coded as private.

500 and 561 are very simple MARC fields, so there's a default mapping specified for these. Institutions can customize this if necessary. 

==== UNCb1004068
===== MARC

[source]
----
500 _ _ $aTranslation is based on a photocopy of the original MS. in the Library of Pembroke College, Oxford.
500 _ _ $a"Published under the auspices of the Library of the New York Academy of Medicine."
500 _ _ $3c. 1$aInscribed: "Benson R. Wilcox"--Fly leaf.$5NcU-H
541 _ _ $aPresented by Benson R. Wilcox$c(Gift :$d2010 :$fHealth Sciences Library,$3c. 1)
561 _ _ $3c. 1$aBookplate: "Ex Libris Benson R. Wilcox M.D."--Inside front cover.$5NcU-H
----

===== Argot
[source,javascript]
----
{
  "note_local":[
    {
      "label":"c. 1",
      "value":"Inscribed: \"Benson R. Wilcox\"--Fly leaf."
    },
    {
      "label":"Source of acquisition",
      "value":"Presented by Benson R. Wilcox (Gift : 2010 : Health Sciences Library, c. 1)",
      "indexed_value":"Presented by Benson R. Wilcox"
    },
    {
      "label":"Ownership history: c. 1",
      "value":"Bookplate: \"Ex Libris Benson R. Wilcox M.D.\"--Inside front cover."
    }
  ]
}
----

=== 561, 590
*561* is *never* mapped to Argot if it is coded as private.

*590* is always mapped to `note_local`. A default mapping is specified, assuming the local field use has a simple structure and the contents should be indexed.

==== UNCb5260735
_I don't know why our rare books catalogers have added what basically amount to duplicate 590 notes. I'm flagging this as a long-term data cleanup project for UNC._

===== MARC

[source]
----
561 0 _ $aGift of Ralph Falls, 6/25/97.
590 _ _ $aRBC PQ4315.58 .R7 1896 c. 1: RBC: Bound in ivory paper yapp fore-edges deckle edges notations and markings throughout.
590 _ _ $aRBC: Bound in ivory paper; yapp fore-edges; deckle edges; notations and markings throughout.
----

===== Argot
[source,javascript]
----
{
  "note_local":[
    {
      "value":"RBC PQ4315.58 .R7 1896 c. 1: RBC: Bound in ivory paper yapp fore-edges deckle edges notations and markings throughout."
    },
    {
      "value":"RBC: Bound in ivory paper; yapp fore-edges; deckle edges; notations and markings throughout."
    }
  ]
}
----

== Examples: note_methodology

=== 567
==== UNCb3616660

===== MARC

[source]
----
567 _ _ $aSamples from 319 quadrangles (1 degree x 2 degrees) beginning in 1976 and ending in 1980; four main sample types represented: stream sediment, soil, surface water, and ground water. Each sample analyzed for uranium and as many as 58 other elements including sulfate.
----

===== Argot
[source,javascript]
----
{
  "note_methodology":[
    {
      "value":"Samples from 319 quadrangles (1 degree x 2 degrees) beginning in 1976 and ending in 1980; four main sample types represented: stream sediment, soil, surface water, and ground water. Each sample analyzed for uranium and as many as 58 other elements including sulfate."
    }
  ]
}
----

== Examples: note_numbering

=== 515
==== UNCb1269140
===== MARC

[source]
----
515 _ _ $aIssues for 1863-1950 have no vol. numbering but constitute v. 1-85.
515 _ _ $aVol. 102 issued in 2 pts.
----

===== Argot

[source,javascript]
----
{
  "note_numbering":[
    "Issues for 1863-1950 have no vol. numbering but constitute v. 1-85.",
    "Vol. 102 issued in 2 pts."
    ]
}
----

== Examples: note_organization

=== 351
==== UNCb6351954
===== MARC

[source]
----
351 _ _ $3Publications and correspondence$aOrganized into two groups: Publications. Correspondence.$bChronological arrangement within group.
----

===== Argot

[source,javascript]
----
{
  "note_organization":[
    "Publications and correspondence: Organized into two groups: Publications. Correspondence. Chronological arrangement within group."
    ]
}
----

== Examples: note_performer_credits
=== 511
==== UNCb1193204
===== MARC

[source]
----
511 0 _ $aJoan Sutherland, soprano; Marilyn Horne, contralto; Joseph Rouleau, bass; with other soloists; London Symphony Orchestra; Richard Bonynge, conductor.
----

===== Argot
[source,javascript]
----
{
  "note_performer_credits":[
    {
      "value":"Joan Sutherland, soprano; Marilyn Horne, contralto; Joseph Rouleau, bass; with other soloists; London Symphony Orchestra; Richard Bonynge, conductor."
    }
  ]
}
----

==== UNCb1709125
===== MARC

[source]
----
511 1 _ $aBela Lugosi, David Manners, Helen Chandler, Edward Van Sloan, Dwight Frye, Frances Dade.
----

===== Argot
[source,javascript]
----
{
  "note_performer_credits":[
    {
      "label":"Cast",
      "value":"Bela Lugosi, David Manners, Helen Chandler, Edward Van Sloan, Dwight Frye, Frances Dade."
    }
  ]
}
----

== Examples: note_production_credits
=== 508
==== UNCb5311776
===== MARC

[source]
----
245 0 0 $aForbidden Hollywood collection.$nVol. 1$h[videorecording].
505 0 _ $aDisc one. Baby face [prerelease version] / Warner Bros. Pictures, Inc. & the Vitaphone Corp. present ; directed by Alfred E. Green ; screen play by Gene Markey & Kathryn Scola ; story by Mark Canfield ; [produced by William LeBaron, Raymond Griffith] (1933, 76 min) ; Baby face [original theatrical release] / Warner Bros. Pictures, Inc. & the Vitaphone Corp. present ; directed by Alfred E. Green ; screen play by Gene Markey & Kathryn Scola ; story by Mark Canfield (1933, 72 min) -- Disc two. Red-headed woman / Metro-Goldwyn-Mayer presents ; directed by Jack Conway ; from the book by Katharine Brush ; screen play by Anita Loos ; [produced by Albert Lewin, Irving Thalberg ; additional writing by F. Scott Fitzgerald] (1932, 79 min.) -- Waterloo bridge / Carl Laemmle presents ; produced by Carl Laemmle, Jr. ; Universal Pictures Corp. ; from the stage play by Robert E. Sherwood ; adaptation and added dialogue, Benn Levy ; screen play, Tom Reed ; directed by James Whale (1931, 81 min.).
508 _ _ $aBaby face: editing, Howard Bretherton ; photography, James Van Trees.
508 _ _ $aRed-headed woman: photography, Harold Rosson ; editing, Blanche Sewell.
508 _ _ $aWaterloo Bridge: cinematographer, Arthur Edeson ; editor, Clarence Kolster, Maurice Pivar ; music, Val Burton.
----

===== Argot
[source,javascript]
----
{
  "note_production_credits":[
    "Baby face: editing, Howard Bretherton ; photography, James Van Trees."
    "Red-headed woman: photography, Harold Rosson ; editing, Blanche Sewell."
    "Waterloo Bridge: cinematographer, Arthur Edeson ; editor, Clarence Kolster, Maurice Pivar ; music, Val Burton."
  ]
}
----

== Examples: note_related_work

=== 535
==== UNCb2415252

* Label provided based on i1 value
* Not indexed

===== MARC

[source]
----
535 1 _ $aDiocesan Library, Episcopal Diocese of Western North Carolina,$bP. O. Box 368, Black Mountain, N.C. 28711.
----

===== Argot

[source,javascript]
----
{
  "note_related_work":[
    {
      "label":"Originals held by:",
      "value":"Diocesan Library, Episcopal Diocese of Western North Carolina, P. O. Box 368, Black Mountain, N.C. 28711."
      "indexed":"false"
    }
  ]
}
----

==== UNCb4014115

* Label provided based on i1 value and $3 if present
* Not indexed

===== MARC

[source]
----
535 2 _ $aChurch of Jesus Christ of the Latter-day Saints. Family History Center, Greensboro, N.C.$3Microfilm
----

===== Argot

[source,javascript]
----
{
  "note_related_work":[
    {
      "label":"Microfilm: Duplicates held by:",
      "value":"Church of Jesus Christ of the Latter-day Saints. Family History Center, Greensboro, N.C.",
      "indexed":"false"
    }
  ]
}
----

=== 544
==== UNCb2364073

* No label provided
* Indexed portion different from display portion

===== MARC

[source]
----
544 _ _ $dSee also James Ritchie Sparkman books (#2732);$dSparkman family papers (#2791) at the$aSouthern Historical Collection, University of North Carolina at Chapel Hill.
544 _ _ $dSee also W.E. Sparkman account book at the$aSouth Caroliniana Library, University of South Carolina.
----

===== Argot

[source,javascript]
----
{
  "note_related_work":[
    {
      "value":"See also James Ritchie Sparkman books (#2732); Sparkman family papers (#2791) at the Southern Historical Collection, University of North Carolina at Chapel Hill.",
      "indexed_value":"See also James Ritchie Sparkman books (#2732); Sparkman family papers (#2791) at the"
    },
    {
      "value":"See also W.E. Sparkman account book at the South Caroliniana Library, University of South Carolina.",
      "indexed_value":"See also W.E. Sparkman account book at the"
    }
  ]
}
----

==== UNCb6466285

* Nothing from field is indexed.
* No label provided

===== MARC

[source]
----
544 _ _ $aThe North Carolina Collection Photographic Archives, University of North Carolina at Chapel Hill, holds many collections with images relating to the history of the University of North Carolina at Chapel Hill.
----

===== Argot

[source,javascript]
----
{
  "note_related_work":[
    {
      "value":"The North Carolina Collection Photographic Archives, University of North Carolina at Chapel Hill, holds many collections with images relating to the history of the University of North Carolina at Chapel Hill.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb7335781

* Label provided based on indicator value
* Indexed portion different from display portion

===== MARC

[source]
----
544 1 _ $dWilliam R. Ferris Collection, #20367 in the,$aSouthern Folklife Collection, University of North Carolina at Chapel Hill.
----

===== Argot

[source,javascript]
----
{
  "note_related_work":[
    {
      "label":"Related materials:",
      "value":"William R. Ferris Collection, #20367 in the, Southern Folklife Collection, University of North Carolina at Chapel Hill.",
      "indexed_value":"William R. Ferris Collection, #20367 in the,"
    }
  ]
}
----

==== UNCb7335781 mock

* Label provided based on indicator value AND $3 value
* Indexed portion different from display portion

===== MARC

[source]
----
544 1 _ $3Documents from 1970s$dWilliam R. Ferris Collection, #20367 in the,$aSouthern Folklife Collection, University of North Carolina at Chapel Hill.
----

===== Argot

[source,javascript]
----
{
  "note_related_work":[
    {
      "label":"Documents from 1970s: Related materials:",
      "value":"William R. Ferris Collection, #20367 in the, Southern Folklife Collection, University of North Carolina at Chapel Hill.",
      "indexed_value":"William R. Ferris Collection, #20367 in the,"
    }
  ]
}
----

=== 580
==== UNCb1285933

* No label provided
* Not indexed

===== MARC

[source]
----
580 _ _ $aMerged with: Botanica acta, to form: Plant biology (Stuttgart, Germany).
----

===== Argot

[source,javascript]
----
{
  "note_related_work":[
    {
      "value":"Merged with: Botanica acta, to form: Plant biology (Stuttgart, Germany).",
      "indexed":"false"
    }
  ]
}
----


== Examples: note_report_type, note_report_coverage
=== 513
==== UNCb3661373
===== MARC

[source]
----
245 1 0 $aTheory and modeling of atmospheric turbulence /$cC.M. Tchen ; prepared for George C. Marshall Space Flight Center.
260 _ _ $aWashington, D.C. :$bNational Aeronautics and Space Administration, Scientific and Technical Information Office ;$a[Springfield, Va. :$bFor sale by National Technical Information Service],$c1984.
300 _ _ $a2 v. :$bill. ;$c28 cm.
500 _ _ $a"February 1984"--Pt. 1.
500 _ _ $a"August 1984"--Pt. 2.
513 _ _ $aContractor report.$bSept 1, 1981-Aug 31, 1982 (pt. 1)
513 _ _ $aContractor report.$bSept 1, 1982-Aug 31, 1983 (pt. 2)
----

===== Argot

[source,javascript]
----
{
  "note_report_type":[
    "Contractor report."
    ],
  "note_report_coverage":[
    "Sept 1, 1981-Aug 31, 1982 (pt. 1)",
    "Sept 1, 1982-Aug 31, 1983 (pt. 2)"
  ]
}
----

===== Display suggestion
*Theory and modeling of atmospheric turbulence* +
C.M. Tchen ; prepared for George C. Marshall Space Flight Center. +
Washington, D.C. : National Aeronautics and Space Administration, Scientific and Technical Information Office ; [Springfield, Va. : For sale by National Technical Information Service], 1984.

*OTHER DETAILS* +
Washington, D.C. : National Aeronautics and Space Administration, Scientific and Technical Information Office ; [Springfield, Va. : For sale by National Technical Information Service], 1984. +
*Report covers:* Sept 1, 1981-Aug 31, 1982 (pt. 1) +
*Report covers:* Sept 1, 1982-Aug 31, 1983 (pt. 2)


*Physical description:* 2 v. : ill. ; 28 cm. +
*Type of report:* Contractor report.

*Notes:* +
"February 1984"--Pt. 1. +
"August 1984"--Pt. 2.

==== UNCb2372593
===== MARC

[source]
----
513 _ _ $aIn house.
----

===== Argot

[source,javascript]
----
{
  "note_report_type":[
    "In house."
    ]
}
----

==== UNCb3405558
===== MARC

[source]
----
513 _ _ $bJanuary - March 1983.
----

===== Argot

[source,javascript]
----
{
  "note_report_coverage":[
    "January - March 1983."
  ]
}
----

== Examples: note_reproduction
=== 533

==== UNCb4128950

* label from $3
* indexed

===== MARC

[source]
----
533 _ _ $aMicrofilm.$3v.3-4.$bWoodbridge, Conn. :$cPrimary Source Microfilm, an imprint of Gale Group,$d2000.$e1 reel ; 35mm.$nUnit 326.$f(The Eighteenth Century ; reel 11380, no. 01).$7s2000    ctu  b
533 _ _ $aMicrofilm.$3v.1-2.$bWoodbridge, Conn. :$cPrimary Source Microfilm, an imprint of Gale Group,$d2000.$e1 reel ; 35mm.$nUnit 326.$f(The Eighteenth Century ; reel 11379, no. 01).$7s2000    ctu  b bb
----

===== Argot

[source,javascript]
----
{
  "note_reproduction":[
    {
      "label":"v.3-4.:",
      "value":"Microfilm. Woodbridge, Conn. : Primary Source Microfilm, an imprint of Gale Group, 2000. 1 reel ; 35mm. Unit 326. (The Eighteenth Century ; reel 11380, no. 01).",
      "indexed_value":"Primary Source Microfilm, an imprint of Gale Group, (The Eighteenth Century ; reel 11380, no. 01)."
    },
    {
      "label":"v.1-2.:",
      "value":"Microfilm. Woodbridge, Conn. : Primary Source Microfilm, an imprint of Gale Group, 2000. 1 reel ; 35mm. Unit 326. (The Eighteenth Century ; reel 11379, no. 01).",
      "indexed_value":"Primary Source Microfilm, an imprint of Gale Group, (The Eighteenth Century ; reel 11379, no. 01)."
    }
  ]
}
----

==== UNCb1817196

* no label
* not indexed (no $c or $f present)

===== MARC

[source]
----
533 _ _ $aMicroopaque.$bWorcester, Mass. :$bMicro Research Corporation [for the American Antiquarian Society].$e4 opaques ; 15 x 23 cm.
----

===== Argot

[source,javascript]
----
{
  "note_reproduction":[
    {
      "value":"Microopaque. Worcester, Mass. : Micro Research Corporation [for the American Antiquarian Society]. 4 opaques ; 15 x 23 cm.",
      "indexed":"false"
    }
  ]
}
----

=== 534
==== Complex processing instructions

* $p present
** $a, $t, or $k present (UNCb6744882, UNCb4232925)
*** `label` from $p
*** `value` from other specified subfields
*** `indexed_value` from $a, $t, $k
** $a, $t, or $k NOT present (UNCb8257422)
*** `label` from $p
*** `value` from other specified subfields
*** `indexed` false
* field lacks $p (UNCb4916807)
** `label` constant value "Original version:"
** `value` from specified subfields
** `indexed` false

The above logic may seem a bit arbitrary---why not check for presence of $a, t, or k first? Without a $p, $a and other subfield coding/content becomes untrustworthy and we cannot assume $a, t, or k should be indexed. 

*Label from $3*
If $3 is present, prepend its value to label assigned via above logic (UNCb9094522)

==== UNCb6744882

===== MARC

[source]
----
534 _ _ $pElectronic reproduction. Originally published in:$kFontes rerum bohemicarum.$mT. 3.$cPrague : Nákl. N.F. Palackého, [1882]
----

===== Argot

[source,javascript]
----
{
  "note_reproduction":[
    {
      "label":"Electronic reproduction. Originally published in:",
      "value":"Fontes rerum bohemicarum. T. 3. Prague : Nákl. N.F. Palackého, [1882]",
      "indexed_value":"Fontes rerum bohemicarum."
    }
  ]
}
----

==== UNCb4232925

===== MARC

[source]
----
534 _ _ $pOriginal version in:$aBry, Theodor de, 1528-1598.$tAdmiranda narratio, fida tamen, de commodis et incolarum ritibus Virginæ ...$kAmerica.$npt. 1.$cFrancoforti ad Moenum, 1590.
----

===== Argot

[source,javascript]
----
{
  "note_reproduction":[
    {
      "label":"Original version in:",
      "value":"Bry, Theodor de, 1528-1598. Admiranda narratio, fida tamen, de commodis et incolarum ritibus Virginæ ... America. pt. 1. Francoforti ad Moenum, 1590.",
      "indexed_value":"Bry, Theodor de, 1528-1598. Admiranda narratio, fida tamen, de commodis et incolarum ritibus Virginæ ... America."
    }
  ]
}
----

==== UNCb8257422

===== MARC

[source]
----
534 _ _ $pFacsimilie reprint. Originally published:$cNew York : D. Appleton and Company, 1894.
----

===== Argot

[source,javascript]
----
{
  "note_reproduction":[
    {
      "label":"Facsimilie reprint. Originally published:",
      "value":"New York : D. Appleton and Company, 1894.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb4916807

===== MARC

[source]
----
534 _ _ $aFaksimile-uitg. van de autografen, 1786, 1787.
----

===== Argot

[source,javascript]
----
{
  "note_reproduction":[
    {
      "label":"Original version:",
      "value":"Faksimile-uitg. van de autografen, 1786, 1787.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb9094522

===== MARC

[source]
----
534 _ _ $3Works 1-12$pissued earlier as analog disc:$cArhoolie$o5036.
----

===== Argot

[source,javascript]
----
{
  "note_reproduction":[
    {
      "label":"Works 1-12: issued earlier as analog disc:",
      "value":"Arhoolie 5036.",
      "indexed":"false"
    }
  ]
}
----

== Examples: note_scale
=== 255
==== UNC1998984
===== MARC

[source]
----
255 _ _ $aScale [3 cm. per degree]$d(Zones -18⁰ to -33⁰, -31⁰ to -46⁰, -44⁰ to 59⁰, -57⁰ to -72⁰, -69⁰ to -84⁰ ;$eeq. 1875)
----

===== Argot
[source,javascript]
----
{
  "note_scale":[
      "Scale [3 cm. per degree] (Zones -18⁰ to -33⁰, -31⁰ to -46⁰, -44⁰ to 59⁰, -57⁰ to -72⁰, -69⁰ to -84⁰ ; eq. 1875)"
  ]
}
----

=== 507
==== UNCb3366168
===== MARC

[source]
----
507 _ _ $aScale 1:100,000;$b1 cm. = 1 kilometer.
----

===== Argot
[source,javascript]
----
{
  "note_scale":[
      "Scale 1:100,000; 1 cm. = 1 kilometer."
  ]
}
----

== Examples: note_serial_dates
=== 362

==== Processing notes

* Map data from subfields a and z
* Put parentheses around $z value
* In $z, replace "Cf." at beginning of field with "Data from:"

==== Behavior notes

* not indexed
* displayed beneath `imprint_main` or `imprint_multiple` data in Other details section.
* No additional label is needed for display.

==== UNCb9164892

[source]
----
=362  1\$aBegan with v. 1 in 1846; ceased in Mar. 1934.$zCf. Union list of serials.
----

[source,ruby]
----
note_serial_dates = [
  'Began with v. 1 in 1846; ceased in Mar. 1934. (Data from: Union list of serials.)'
]
----

==== UNCb9187943

[source]
----
=362  0\$aAug. 1, 1959-Aug. 1, 1965.
----

[source,ruby]
----
note_serial_dates = [
  'Aug. 1, 1959-Aug. 1, 1965.'
]
----

== Examples: note_supplement

* Field is NOT indexed

=== 525

==== UNCb1310968

===== MARC

[source]
----
525 _ _ $aSome issues accompanied by supplements.
----

===== Argot

[source,javascript]
----
{
  "note_supplement":[
    "Some issues accompanied by supplements."
    ]
}
----

== Examples: note_system_details

* Field is NOT indexed

=== 538

==== UNCb7177098

* Set label from $3 and $i values (both present)

===== MARC

[source]
----
538 _ _ $3v.1-2$iDigital master conforms to:$aBenchmark for Faithful Digital Reproductions of Monographs and Serials. Version 1. Digital Library Federation, December 2002$uhttp://www.diglib.org/standards/bmarkfin.htm
----

===== Argot

[source,javascript]
----
{
  "note_system_details":[
    "v.1-2: Digital master conforms to: Benchmark for Faithful Digital Reproductions of Monographs and Serials. Version 1. Digital Library Federation, December 2002 http://www.diglib.org/standards/bmarkfin.htm"
    ]
}
----

==== UNCb7469525

* Set label from $3

===== MARC

[source]
----
538 _ _ $3Videodisc$aDVD; stereo. or 5.1 surround.
----

===== Argot

[source,javascript]
----
{
  "note_system_details":[
    "Videodisc: DVD; stereo. or 5.1 surround."
    ]
}
----

==== UNCb3512702

* No label

===== MARC

[source]
----
538 _ _ $aSystem requirements for accompanying computer disc: IBM comatible PC; CD-ROM player and drive.
----

===== Argot

[source,javascript]
----
{
  "note_system_details":[
    "System requirements for accompanying computer disc: IBM comatible PC; CD-ROM player and drive."
    ]
}
----

== Examples: note_former_title

Field is *NOT* indexed. This field should occur with 247s that allow the titles to be indexed. The 247s should be coded as index only. 

=== 547

==== UNCb6843127

===== MARC
[source]
-----
247 0 1 $aNugents;$bthe garment weekly$fVol. 41, no. 9-v. 55, no. 10, v. 54, no. 6-v. 84, no. 4 (May 12, 1917-Sept. 3, 1921, Nov. 6, 1923-Oct. 23, 1928)
247 0 1 $aGarment weekly$fv. 55, no. 11-v. 54, no. 5 (Sept. 10, 1921-Oct. 30, 1923)
247 0 1 $aNugent's;$bthe specialty store magazine$fv. 85, no. 1-9 (Oct., 1929-June, 1930)
247 0 1 $aNugent's;$bfor buyers of fashion merchandise$fv. 85, no. 10-v. 87, no. 7 (July, 1930-April, 1932)
547 _ _ $aVol. 41, no. 9-v. 55, no. 10, v. 54, no. 6-v. 84, no. 4 (May 12, 1917-Sept. 3, 1921, Nov. 6, 1923-Oct. 23, 1928) title reads: Nugents; the garment weekly; v. 55, no. 11-v. 54, no. 5 (Sept. 10, 1921-Oct. 30, 1923) The Garment weekly; v. 85, no. 1-9 (Oct., 1929-June, 1930), Nugent's; the specialty store magazine; v. 85, no. 10-v. 87, no. 7 (July, 1930-April, 1932), Nugent's; for buyers of fashion merchandise.
-----

===== Argot
[source,javascript]
----
{
  "note_former_title":[
      "Vol. 41, no. 9-v. 55, no. 10, v. 54, no. 6-v. 84, no. 4 (May 12, 1917-Sept. 3, 1921, Nov. 6, 1923-Oct. 23, 1928) title reads: Nugents; the garment weekly; v. 55, no. 11-v. 54, no. 5 (Sept. 10, 1921-Oct. 30, 1923) The Garment weekly; v. 85, no. 1-9 (Oct., 1929-June, 1930), Nugent's; the specialty store magazine; v. 85, no. 10-v. 87, no. 7 (July, 1930-April, 1932), Nugent's; for buyers of fashion merchandise."
  ]
}
----

===== Behavior
This field is displayed, not indexed.

Indexing of the titles is based on the 247 field and is handled by the Argot `title_variant` pattern of fields described https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_title_variant.adoc[here]. 

== Examples: note_with
=== 501
==== UNCb1193620
_There are notes in this record other than the one(s) shown here_

===== MARC
[source]
-----
501 _ _ $aBound with: United States. Congress. Committee on Labor and Public Welfare. Subcommittee on Labor. Legislative history of the coverage of nonprofit hospitals under the National labor relations act, 1974, Public law 93-360 (S. 3203).
-----

===== Argot
[source,javascript]
----
{
  "note_with":[
      "Bound with: United States. Congress. Committee on Labor and Public Welfare. Subcommittee on Labor. Legislative history of the coverage of nonprofit hospitals under the National labor relations act, 1974, Public law 93-360 (S. 3203)."
  ]
}
----

===== Display

[NOTE]
====
I'm on the fence about where this belongs.

It sort of makes sense with "This item includes".

It also sort of makes sense with physical description details or general notes.

It also seems like the kind of thing that institutions might want to display in different ways, which is a main reason I pulled it out as a separate, specific note field. 
====

== Ignored notes
=== 524 - Preferred Citation of Described Materials Note
UNC catalog use = 23 fields

Field has been around since at least 2008 (and not updated since)

Users unlikely to look in full record to find out the preferred way to cite something. Also, we don't know what citation format they are being required to use.

Does not add to retrieval/discovery

=== 530 - Additional Physical Form Available Note
=== 583 - Action Note
=== 588 - Source of Description Note
b1296969a	588 _ _ $aDescription based on: Vol. 16, no. 8 (Aug. 1971); title from cover.
b1311160a	588 _ _ $aLatest issue consulted: Vol. 35, no. 1 (winter 2001) surrogate.

== Examples (to do) 

b2415252a	535 1 _ $aDiocesan Library, Episcopal Diocese of Western North Carolina,$bP. O. Box 368, Black Mountain, N.C. 28711.

b2020885a	535 1 _ $aNational Archives and Records Administration$cUSA

b4014115a	535 2 _ $aChurch of Jesus Christ of the Latter-day Saints. Family History Center, Greensboro, N.C.$3Microfilm

b3616660a	567 _ _ $aSamples from 319 quadrangles (1 degree x 2 degrees) beginning in 1976 and ending in 1980; four main sample types represented: stream sediment, soil, surface water, and ground water. Each sample analyzed for uranium and as many as 58 other elements including sulfate.

b5250152a	567 8 _ $aThe Protocol for Assessing Community Excellence in Environmental Health (PACE EH) offers local health officials guidance in conducting a community-based environmental health assessment and creating an accurate and verifiable profile of the community's environmental health status. The process is designed to improve decision making by taking a collaborative community-based approach to generating an action plan that is based on a set of priorities that reflect both an accurate assessment of local environmental health status and an understanding of public values and priorities. The methodology takes the user through a series of tasks to engage the public, collect necessary and relevant information related to community environmental health concerns, rank issues, and set local priorities for action. At the heart are three core processes: developing new relationships with community stakeholders, expanding understanding about the relationship between human health and the state of the environment, and redefining a leadership role for public health officials in environmental health.

