= Notes fields
== Overview of notes in Argot
=== Separate-field treatment
A few notes are pulled out into special fields. This is because a) there is some special treatment for the field in the systesm AND/OR b) we deem the data in the note to be different/important enought to set it apart from other notes, either in a separate area, or with a separate primary label.

Examples are:

- 505 Contents note (TOC from Syndetics overrides display of this field; if no Syndetics data present, show separate from other notes as Contents)
- 520 Summary note (Similar to 505) 
- 511 Participant or Performer Note (display as separate field)

=== Ignored notes
Some notes are NOT displayed or indexed.

Details on all ignored notes fields below in ignored notes section.

=== Displayed notes
notes_display contains all notes to be displayed (which includes some notes that are not indexed).

notes_display allows us to display notes in the order they appear in the catalog record, which is sometimes important for having them make sense.

This also allows us to generate nonindexed labels from the data, so that the displayed notes make more sense.

=== Indexed notes
notes_index contains only the main content (i.e. no labels, etc) of notes (or parts of notes) that meaningfully contribute to retrieval

=== Local notes
It will be up to individual institutions to decide how their local notes (590) field data is mapped.

In Endeca, we had the option of mapping this to either the non-indexed `Notes` property (using prepipeline data label 590) or the `Indexed Notes` property (using prepipeline data label `590_indexed`).

== Special patterns in notes field processing
=== A. Field-refers-to label (from $3) needed
b1004068a	500 _ _ $3c. 1$aInscribed: "Benson R. Wilcox"--Fly leaf.$5NcU-H

500 - General Note
=== D. Label generated from MARC tag and/or indicator value(s) needed

- 510 - Citation/References Note
- 521 - Target Audience Note
- 522 - Geographic Coverage Note

=== E. Label created from $i
[WARNING]
.$i is not always a label
=====================================================================
In the following fields, $i is a non-label data element: 

- 514
- 542
- 552
- 583
=====================================================================
=== F. Something else
==== 518 - Date/Time and Place of an Event Note

- May need $3 label
-- b7832943a	518 _ _ $3CD 2$oRecorded$d2004 November,$pAuditorium (Chiesa) di San Salvatore a Rodengo, Brescia, Italy.
-- b7832943a	518 _ _ $3CD 1$oRecorded$d2001 October,$pIstituo di musica Antica Academia Monte Regalis, Mondovi, Italy.
- If $a, treat like basic textual note
-- b1200040a	518 _ _ $a"Recorded in the formerly monastic church of St. Ottilie in Möschenfeld near Munich. Date of recording, May, 1967."
- If any subfields occur after $a, remove them and throw in a space -- these are probably mis-coded and should be cleaned up in the data, but are pretty innocuous and seem easy-ish to deal with
-- b8966892a	518 _ _ $aBroadcast$dFriday, November 18 (10:01-11:00 p.m. Est), on ABC.
- If no $a... $o 

== Separate field notes
=== 514 - Data Quality Note
b8981148a	514 _ _ $zConforms To:$eCombined Arms Research Library Digital Library.
b6855632a	514 _ _ $aThe attribute accuracy is unknown.$dNo duplicate features are present.$eAfter processing, the data set is checked for number of records, attribute names, and values compared with source materials.

=== 506 - Restrictions on Access Note
=== 508 - Creation/Production Credits Note
=== 511 - Participant or Performer Note

== Ignored notes
=== 524 - Preferred Citation of Described Materials Note
UNC catalog use = 23 fields

Field has been around since at least 2008 (and not updated since)

Users unlikely to look in full record to find out the preferred way to cite something. Also, we don't know what citation format they are being required to use.

Does not add to retrieval/discovery

=== 530 - Additional Physical Form Available Note
=== 583 - Action Note
=== 588 - Source of Description Note
b1296969a	588 _ _ $aDescription based on: Vol. 16, no. 8 (Aug. 1971); title from cover.
b1311160a	588 _ _ $aLatest issue consulted: Vol. 35, no. 1 (winter 2001) surrogate.

== Examples
b1000070a	500 _ _ $a"Sponsored by NASA Historical Staff, Office of Policy Analysis."

b2415252a	535 1 _ $aDiocesan Library, Episcopal Diocese of Western North Carolina,$bP. O. Box 368, Black Mountain, N.C. 28711.
b2020885a	535 1 _ $aNational Archives and Records Administration$cUSA
b4014115a	535 2 _ $aChurch of Jesus Christ of the Latter-day Saints. Family History Center, Greensboro, N.C.$3Microfilm

b2559560a	563 _ _ $aNLM copy bound in contemporary Cambridge-style binding.$5DNLM
b9021086a	563 _ _ $aRebacked tooled old calf, with bosses and clasps (the latter missing on upper edge). "333" written on inner cover. Front endpaper is vellum leaf from a 14th century service book; written in large gothic script with red and blue initials decorated with pen flourishes. Back doublure is part of a vellum leaf from a 14th century annotated digest; written in gothic script.
b4254290a	563 _ _ $aSome pages uncut.$3(Health Sciences Library, c. 1)

b3616660a	567 _ _ $aSamples from 319 quadrangles (1 degree x 2 degrees) beginning in 1976 and ending in 1980; four main sample types represented: stream sediment, soil, surface water, and ground water. Each sample analyzed for uranium and as many as 58 other elements including sulfate.
b5250152a	567 8 _ $aThe Protocol for Assessing Community Excellence in Environmental Health (PACE EH) offers local health officials guidance in conducting a community-based environmental health assessment and creating an accurate and verifiable profile of the community's environmental health status. The process is designed to improve decision making by taking a collaborative community-based approach to generating an action plan that is based on a set of priorities that reflect both an accurate assessment of local environmental health status and an understanding of public values and priorities. The methodology takes the user through a series of tasks to engage the public, collect necessary and relevant information related to community environmental health concerns, rank issues, and set local priorities for action. At the heart are three core processes: developing new relationships with community stakeholders, expanding understanding about the relationship between human health and the state of the environment, and redefining a leadership role for public health officials in environmental health.




