:toc:
:toc-placement!:

= Notes fields

*See the https://github.com/trln/data-documentation/tree/master/argot[Argot Excel file available here] or the https://github.com/trln/data-documentation/blob/master/argot/_mappings.csv[mappings.csv file] for field/subfield specific instructions.*

*Test records*
The UNC bib records referred to by bib number in this document are at:
https://github.com/trln/extract_marcxml_for_argot_unc/blob/master/output/testing/notes.xml

toc::[]

== Patterns of mapping MARC fields to Argot
=== One MARC tag-to-separate Argot field treatment
Some MARC note fields are extracted into separate, specific Argot fields. This is because:

* There is some special treatment for the field in the system; AND/OR
* We deem the data in the note to be different/important enought to set it apart from other notes, either in a separate area, or with a separate primary label.

Examples are:

* 505 Contents note (TOC from Syndetics overrides display of this field; if no Syndetics data present, show separate from other notes as Contents)
* 520 Summary note (Similar to 505) 
* 511 Participant or Performer Note (display as separate field)

=== Multiple MARC tag-to-Argot field for note category
Some MARC note fields fall into general categories that should be displayed with other data. For example:

* Notes about publication history or issuance should be displayed with publication details
* Notes about accompanying materials, physical description, or system requirements should be displayed with other physical description information
* Local copy/item specific notes need to be shown separately

=== General notes field in Argot
Other MARC notes fields are handled in a general notes field.

=== Ignored notes
Some notes are NOT displayed or indexed.

Details on all ignored notes fields below in ignored notes section.

== Behavior of notes in TRLN Discovery
=== Displayed notes
All notes extracted into Argot will be displayed.

=== Indexed note content

* Note content is searchable in the keyword index.
* *Some note fields are NOT indexed.* These fields do not appear to meaningfully contribute to discovering the item described by the record and/or would introduce noise into the index and results sets
* Note labels and other parts of notes fields that contribute more noise than discoverability are NOT indexed.

== Local notes
It will be up to individual institutions to decide how their local notes (590) field data is mapped to the Argot `note_local` field.

In Endeca, we had the option of mapping this to either the non-indexed `Notes` property (using prepipeline data label `590`) or the `Indexed Notes` property (using prepipeline data label `590_indexed`).

The `note_local` field provides the same flexibility. 

== Special patterns in notes field processing
=== Field-refers-to label (from $3) needed
See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_3.adoc[spec document for $3] for more details. 

=== Label generated from MARC tag and/or indicator value(s) and/or subfield definitions
Data in some note fields looks very weird without a label. http://search.trln.org/search?id=UNCb1240038[Here's an example record in SearchTRLN]:

NOTES

- 1943-64. 1 v.
- No earlier abstracts published?
- Title varies slightly.
- (GL)


The same MARC field is often used to record different types of data, with indicator coding controlling the meaning of the field.

Some subfields are used to record data that needs its own label in order for the data (and its relationship to the rest of the data in the field) to make sense.

We should use the coding of the MARC data to display data to end users in a meaningful way.

*Each MARC field's indicators and subfields are defined separately, so this type of processing will be very field-specific.*

==== 521 example 1

 521 2 _ $a6-12$bMorgan Reynolds Incorporated

Without generating a label using the MARC tag and indicator coding, we end up with a cryptic note displayed:

 6-12 Morgan Reynolds Incorporated

Or we can meaningfully label/display the info:

 For grade(s): 6-12. (as determined by Morgan Reynolds Incorporated)


==== 521 example 2
 521 1 _ $aAdult.$bBrodart

Should be displayed:

 For age(s): Adult. (as determined by Brodart)

=== Label created from $i

[WARNING]
.$i is not always a label
=====================================================================
In the following fields, $i is a non-label data element: 

- 514
- 542
- 552
- 583
=====================================================================

=== Something else
Of course some fields are just weird and complicated.

One example is the 518 where you have the option of putting a natural language note in the $a. OR you can bust up the information into separately coded elements where the $p sort of functions as a label.

* May need $3 label
** b7832943a	518 _ _ $3CD 2$oRecorded$d2004 November,$pAuditorium (Chiesa) di San Salvatore a Rodengo, Brescia, Italy.
** b7832943a	518 _ _ $3CD 1$oRecorded$d2001 October,$pIstituo di musica Antica Academia Monte Regalis, Mondovi, Italy.
* If $a, treat like basic textual note
** b1200040a	518 _ _ $a"Recorded in the formerly monastic church of St. Ottilie in Möschenfeld near Munich. Date of recording, May, 1967."
* If any subfields occur after $a, remove them and throw in a space -- these are probably mis-coded and should be cleaned up in the data, but are pretty innocuous and seem easy-ish to deal with
** b8966892a	518 _ _ $aBroadcast$dFriday, November 18 (10:01-11:00 p.m. Est), on ABC.
* If no $a... $o 

== Argot note pattern

[source:javascript]
----
{
  "note_field_name":[
    {
      "label":"Label for the note",
      "value":"The displayed content of the note",
      "indexed_value":"The part of above value that should be indexed, if it is different from value",
      "indexed":"Boolean: true or false"
    }
  ]
}
----

* `label`: Optional. May be set from $3, $i, and/or MARC field tag + indicator values.
* `value`: *Required.* The note that will be displayed. If there is no `indexed_value` and `indexed` is not false, this is also the indexed note content.
* `indexed_value`: Optional. This should only be populated if:
** `indexed` == true; AND
** `indexed_value` needs to be different than `value`
* `indexed`: Optional. If not explicitly set, assumed to equal true. In other words, default assumption is that a note field will be indexed.

== Organization of examples

* Argot field
** MARC tag
*** Example from specific record
**** MARC
**** Argot 
**** Display (if there is anything notable to say/show)
**** Indexing/search (if there is anything notable to say/show)

== Examples: note_general
=== 500
500 is mapped to `note_general` if it lacks a whitelisted $5 value for the institution creating the Argot.

==== UNCb1055018
===== MARC
[source]
----
500 _ _ $a"This edition is limited to 750 copies, and the type has been distributed."
----

===== Argot
[source,javascript]
----
{
  "note_general":[
    {
      "value":"\"This edition is limited to 750 copies, and the type has been distributed.\""
    }
  ]
}


----

==== UNCb1004068
===== MARC

[source]
----
500 _ _ $aTranslation is based on a photocopy of the original MS. in the Library of Pembroke College, Oxford.
500 _ _ $a"Published under the auspices of the Library of the New York Academy of Medicine."
500 _ _ $3c. 1$aInscribed: "Benson R. Wilcox"--Fly leaf.$5NcU-H
541 _ _ $aPresented by Benson R. Wilcox$c(Gift :$d2010 :$fHealth Sciences Library,$3c. 1)
561 _ _ $3c. 1$aBookplate: "Ex Libris Benson R. Wilcox M.D."--Inside front cover.$5NcU-H
----

===== Argot
[source,javascript]
----
{
  "note_general":[
    {
      "value":"Translation is based on a photocopy of the original MS. in the Library of Pembroke College, Oxford."
    },
    {
      "value":"\"Published under the auspices of the Library of the New York Academy of Medicine.\""
    }
    ]
    }

----

=== 504

[IMPORTANT]
====
*Processing rule*

If $b is present, prepend "Number of references: " to its value.
====

==== UNCb4706138
===== MARC

[source]
----
504 _ _ $b36 references.
----

===== Argot

[source,javascript]
----
{
  "note_general":[
    {
      "value":"Number of references: 36 references.",
      "indexed":"false"
    }
  ]
}
----

==== UNCb2019098
===== MARC

[source]
----
504 _ _ $aBibliography : p. 81-83.$b52.
----

===== Argot
[source,javascript]
----
{
  "note_general":[
    {
      "value":"Bibliography : p. 81-83. Number of references: 52.",
      "indexed":"false"
    }
  ]
}
----


== Examples: note_local
=== 500, 541, 561
*500* is mapped to `note_local` if whitelisted $5 for institution creating Argot is present.

*541* is always mapped to `note_local`. This field has many elements and their use is not well-standardized. Rules for mapping this field are assumed to be completely institution-specific. 

*561* is always mapped to `note_local` if not coded as private.

500 and 561 are very simple MARC fields, so there's a default mapping specified for these. Institutions can customize this if necessary. 

==== UNCb1004068
===== MARC

[source]
----
500 _ _ $aTranslation is based on a photocopy of the original MS. in the Library of Pembroke College, Oxford.
500 _ _ $a"Published under the auspices of the Library of the New York Academy of Medicine."
500 _ _ $3c. 1$aInscribed: "Benson R. Wilcox"--Fly leaf.$5NcU-H
541 _ _ $aPresented by Benson R. Wilcox$c(Gift :$d2010 :$fHealth Sciences Library,$3c. 1)
561 _ _ $3c. 1$aBookplate: "Ex Libris Benson R. Wilcox M.D."--Inside front cover.$5NcU-H
----

===== Argot
[source,javascript]
----
{
  "note_local":[
    {
      "label":"c. 1",
      "value":"Inscribed: \"Benson R. Wilcox\"--Fly leaf."
    },
    {
      "label:"Source of acquisition",
      "value":"Presented by Benson R. Wilcox (Gift : 2010 : Health Sciences Library, c. 1)",
      "indexed_value":"Presented by Benson R. Wilcox"
    },
    {
      "label":"Ownership history: c. 1",
      "value":"Bookplate: \"Ex Libris Benson R. Wilcox M.D.\"--Inside front cover."
    }
  ]
}
----

=== 561, 590
*561* is *never* mapped to Argot if it is coded as private.

*590* is always mapped to `note_local`. A default mapping is specified, assuming the local field use has a simple structure and the contents should be indexed.

==== UNCb5260735
_I don't know why our rare books catalogers have added what basically amount to duplicate 590 notes. I'm flagging this as a long-term data cleanup project for UNC._
===== MARC

[source]
----
561 0 _ $aGift of Ralph Falls, 6/25/97.
590 _ _ $aRBC PQ4315.58 .R7 1896 c. 1: RBC: Bound in ivory paper yapp fore-edges deckle edges notations and markings throughout.
590 _ _ $aRBC: Bound in ivory paper; yapp fore-edges; deckle edges; notations and markings throughout.
----

===== Argot
[source,javascript]
----
{
  "note_local":[
    {
      "value":"RBC PQ4315.58 .R7 1896 c. 1: RBC: Bound in ivory paper yapp fore-edges deckle edges notations and markings throughout."
    },
    {
      "value":"RBC: Bound in ivory paper; yapp fore-edges; deckle edges; notations and markings throughout."
    }
  ]
}
----

== Examples: note_with
=== 501
==== UNCb1193620
_There are notes in this record other than the one(s) shown here_

===== MARC
[source]
-----
501 _ _ $aBound with: United States. Congress. Committee on Labor and Public Welfare. Subcommittee on Labor. Legislative history of the coverage of nonprofit hospitals under the National labor relations act, 1974, Public law 93-360 (S. 3203).
-----

===== Argot
[source,javascript]
----
{
  "note_with":[
      "Bound with: United States. Congress. Committee on Labor and Public Welfare. Subcommittee on Labor. Legislative history of the coverage of nonprofit hospitals under the National labor relations act, 1974, Public law 93-360 (S. 3203)."
  ]
}
----

===== Display

[NOTE]
====
I'm on the fence about where this belongs.

It sort of makes sense with "This item includes".

It also sort of makes sense with physical description details or general notes.

It also seems like the kind of thing that institutions might want to display in different ways, which is a main reason I pulled it out as a separate, specific note field. 
====

== Examples: note_dissertation
=== 502
==== Complex processing rules
*See _Shift off subfield list before further processing_ section of https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_6.adoc[$6 spec sheet]*

===== Punctuation provision rules for building field value from component subfields (i.e. when there are subfields other than a present)

* Precede all non-initial subfield values except $d with `--`
* Precede non-initial $d with `, ` (comma space)

===== Logic

* If first subfield is a...
** If there are no other subfields (b,c,d,g, or o)
*** Take contents of $a.
*** See UNCb9058990 example below.
** And it is followed by subfields b,c,d,g, or o
*** Build note field from all extractable subfield elements present, following punctuation provision rules.
*** See mock example below.
* If first subfield is b or g
** Build note field from all subfield elements present, following punctuation provision rules.
** See UNCb7386333 and UNCb1511334 examples below.
* Else...
** Provide fake $b value "Thesis/dissertation" to use at beginning of field
** Build note field from all subfield elements present, following punctuation provision rules
** See UNCb6856070 example below.

==== UNC mock example
===== MARC

[source]
----
502 _ _ $aThesis$bPh.D$cUniversity of North Carolina at Chapel Hill.
----

===== Argot
[source,javascript]
----
{
  "note_dissertation":[
    {
      "value":"Thesis--Ph.D--University of North Carolina at Chapel Hill."
    }
  ]
}
----

==== UNCb9058990

===== MARC
[source]
----
502 _ _ $aThesis (Ph. D.)--University of Lancaster, Lancashire, England.
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
    {
      "value":"Thesis (Ph. D.)--University of Lancaster, Lancashire, England."
    }
  ]
}
----

==== UNCb7386333

===== MARC

[source]
----
502 _ _ $gRecital document$bMaster of Music in Performance and Vocal Pedagogy$cUniversity of Texas at San Antonio$d2012.
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
    {
      "value":"Recital document--Master of Music in Performance and Vocal Pedagogy--University of Texas at San Antonio, 2012."
    }
  ]
}
----

==== UNCb1511334

===== MARC
[source]
----
502 _ _ $bPh. D.$cUniversity of North Carolina$d1976
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
    {
      "value":"Ph. D.--University of North Carolina, 1976"
    }
  ]
}
----

==== UNCb6856070
===== MARC

[source]
----
502 _ _ $cBremen International Graduate School of Social Sciences$d2008
----

===== Argot

[source,javascript]
----
{
  "note_dissertation":[
    {
      "value":"Thesis/dissertation--Bremen International Graduate School of Social Sciences, 2008"
    }
  ]
}
----

== Examples: note_scale
=== 255
==== UNC1998984
===== MARC

[source]
----
255 _ _ $aScale [3 cm. per degree]$d(Zones -18⁰ to -33⁰, -31⁰ to -46⁰, -44⁰ to 59⁰, -57⁰ to -72⁰, -69⁰ to -84⁰ ;$eeq. 1875)
----

===== Argot
[source,javascript]
----
{
  "note_scale":[
    {
      "value":"Scale [3 cm. per degree] (Zones -18⁰ to -33⁰, -31⁰ to -46⁰, -44⁰ to 59⁰, -57⁰ to -72⁰, -69⁰ to -84⁰ ; eq. 1875)"
    }
  ]
}
----

=== 507
==== UNCb3366168
===== MARC

[source]
----
507 _ _ $aScale 1:100,000;$b1 cm. = 1 kilometer.
----

===== Argot
[source,javascript]
----
{
  "note_scale":[
    {
      "value":"Scale 1:100,000; 1 cm. = 1 kilometer."
    }
  ]
}
----

== Examples: note_performer_credits
=== 511
==== UNCb1193204
===== MARC

[source]
----
511 0 _ $aJoan Sutherland, soprano; Marilyn Horne, contralto; Joseph Rouleau, bass; with other soloists; London Symphony Orchestra; Richard Bonynge, conductor.
----

===== Argot
[source,javascript]
----
{
  "note_performer_credits":[
    {
      "value":"Joan Sutherland, soprano; Marilyn Horne, contralto; Joseph Rouleau, bass; with other soloists; London Symphony Orchestra; Richard Bonynge, conductor."
    }
  ]
}
----

==== UNCb1709125
===== MARC

[source]
----
511 1 _ $aBela Lugosi, David Manners, Helen Chandler, Edward Van Sloan, Dwight Frye, Frances Dade.
----

===== Argot
[source,javascript]
----
{
  "note_performer_credits":[
    {
      "label":"Cast",
      "value":"Bela Lugosi, David Manners, Helen Chandler, Edward Van Sloan, Dwight Frye, Frances Dade."
    }
  ]
}
----

== Examples: note_production_credits
=== 508
==== UNCb5311776
===== MARC

[source]
----
245 0 0 $aForbidden Hollywood collection.$nVol. 1$h[videorecording].
505 0 _ $aDisc one. Baby face [prerelease version] / Warner Bros. Pictures, Inc. & the Vitaphone Corp. present ; directed by Alfred E. Green ; screen play by Gene Markey & Kathryn Scola ; story by Mark Canfield ; [produced by William LeBaron, Raymond Griffith] (1933, 76 min) ; Baby face [original theatrical release] / Warner Bros. Pictures, Inc. & the Vitaphone Corp. present ; directed by Alfred E. Green ; screen play by Gene Markey & Kathryn Scola ; story by Mark Canfield (1933, 72 min) -- Disc two. Red-headed woman / Metro-Goldwyn-Mayer presents ; directed by Jack Conway ; from the book by Katharine Brush ; screen play by Anita Loos ; [produced by Albert Lewin, Irving Thalberg ; additional writing by F. Scott Fitzgerald] (1932, 79 min.) -- Waterloo bridge / Carl Laemmle presents ; produced by Carl Laemmle, Jr. ; Universal Pictures Corp. ; from the stage play by Robert E. Sherwood ; adaptation and added dialogue, Benn Levy ; screen play, Tom Reed ; directed by James Whale (1931, 81 min.).
508 _ _ $aBaby face: editing, Howard Bretherton ; photography, James Van Trees.
508 _ _ $aRed-headed woman: photography, Harold Rosson ; editing, Blanche Sewell.
508 _ _ $aWaterloo Bridge: cinematographer, Arthur Edeson ; editor, Clarence Kolster, Maurice Pivar ; music, Val Burton.
----

===== Argot
[source,javascript]
----
{
  "note_production_credits":[
    "Baby face: editing, Howard Bretherton ; photography, James Van Trees."
    "Red-headed woman: photography, Harold Rosson ; editing, Blanche Sewell."
    "Waterloo Bridge: cinematographer, Arthur Edeson ; editor, Clarence Kolster, Maurice Pivar ; music, Val Burton."
  ]
}
----

== Examples: note_report_type, note_report_coverage
=== 513
==== UNCb3661373
===== MARC

[source]
----
245 1 0 $aTheory and modeling of atmospheric turbulence /$cC.M. Tchen ; prepared for George C. Marshall Space Flight Center.
260 _ _ $aWashington, D.C. :$bNational Aeronautics and Space Administration, Scientific and Technical Information Office ;$a[Springfield, Va. :$bFor sale by National Technical Information Service],$c1984.
300 _ _ $a2 v. :$bill. ;$c28 cm.
500 _ _ $a"February 1984"--Pt. 1.
500 _ _ $a"August 1984"--Pt. 2.
513 _ _ $aContractor report.$bSept 1, 1981-Aug 31, 1982 (pt. 1)
513 _ _ $aContractor report.$bSept 1, 1982-Aug 31, 1983 (pt. 2)
----

===== Argot

[source,javascript]
----
{
  "note_report_type":[
    "Contractor report."
    ],
  "note_report_coverage":[
    "Sept 1, 1981-Aug 31, 1982 (pt. 1)",
    "Sept 1, 1982-Aug 31, 1983 (pt. 2)"
  ]
}
----

===== Display suggestion
*Theory and modeling of atmospheric turbulence* +
C.M. Tchen ; prepared for George C. Marshall Space Flight Center. +
Washington, D.C. : National Aeronautics and Space Administration, Scientific and Technical Information Office ; [Springfield, Va. : For sale by National Technical Information Service], 1984.

*OTHER DETAILS* +
Washington, D.C. : National Aeronautics and Space Administration, Scientific and Technical Information Office ; [Springfield, Va. : For sale by National Technical Information Service], 1984. +
*Report covers:* Sept 1, 1981-Aug 31, 1982 (pt. 1) +
*Report covers:* Sept 1, 1982-Aug 31, 1983 (pt. 2)


*Physical description:* 2 v. : ill. ; 28 cm. +
*Type of report:* Contractor report.

*Notes:* +
"February 1984"--Pt. 1. +
"August 1984"--Pt. 2.

==== UNCb2372593
===== MARC

[source]
----
513 _ _ $aIn house.
----

===== Argot

[source,javascript]
----
{
  "note_report_type":[
    "In house."
    ]
}
----

==== UNCb3405558
===== MARC

[source]
----
513 _ _ $bJanuary - March 1983.
----

===== Argot

[source,javascript]
----
{
  "note_report_coverage":[
    "January - March 1983."
  ]
}
----

== Examples: note_issuance
=== 550
==== UNCb234211
===== MARC

[source]
----
245 0 0 $aAmerican birds$h[serial].
260 _ _ $a[New York,$bNational Audubon Society]
550 _ _ $aVols. for <Feb.-June 1971> published by the National Audubon Society in collaboration with the U.S. Fish and Wildlife Service.
----

===== Argot

[source,javascript]
----
{
  "note_issuance":[
      "Vols. for <Feb.-June 1971> published by the National Audubon Society in collaboration with the U.S. Fish and Wildlife Service."
    ]
}
----

===== Display suggestion
*American birds [serial].* +
[New York, National Audubon Society] +

*OTHER DETAILS* +
[New York, National Audubon Society] +
Vols. for <Feb.-June 1971> published by the National Audubon Society in collaboration with the U.S. Fish and Wildlife Service.

== Examples: note_organization

=== 351
==== UNCb6351954
===== MARC

[source]
----
351 _ _ $3Publications and correspondence$aOrganized into two groups: Publications. Correspondence.$bChronological arrangement within group.
----

===== Argot

[source,javascript]
----
{
  "note_organization":[
    "Publications and correspondence: Organized into two groups: Publications. Correspondence. Chronological arrangement within group."
    ]
}
----


== Complex processing instructions
=== 538

Replacements (case insensitive):

* Adobe Acrobat reader -> PDF reader
* Adobe [Acrobat] Reader -> PDF reader

Omissions (case insensitive):

* Fields starting with:
** Mode of access: World Wide Web
** Mode of access: Internet
** System requirements: WWW browser



== Separate field notes



=== 514 - Data Quality Note
b8981148a	514 _ _ $zConforms To:$eCombined Arms Research Library Digital Library.

b6855632a	514 _ _ $aThe attribute accuracy is unknown.$dNo duplicate features are present.$eAfter processing, the data set is checked for number of records, attribute names, and values compared with source materials.


== Ignored notes
=== 524 - Preferred Citation of Described Materials Note
UNC catalog use = 23 fields

Field has been around since at least 2008 (and not updated since)

Users unlikely to look in full record to find out the preferred way to cite something. Also, we don't know what citation format they are being required to use.

Does not add to retrieval/discovery

=== 530 - Additional Physical Form Available Note
=== 583 - Action Note
=== 588 - Source of Description Note
b1296969a	588 _ _ $aDescription based on: Vol. 16, no. 8 (Aug. 1971); title from cover.
b1311160a	588 _ _ $aLatest issue consulted: Vol. 35, no. 1 (winter 2001) surrogate.

== Examples (to do) 

b2415252a	535 1 _ $aDiocesan Library, Episcopal Diocese of Western North Carolina,$bP. O. Box 368, Black Mountain, N.C. 28711.

b2020885a	535 1 _ $aNational Archives and Records Administration$cUSA

b4014115a	535 2 _ $aChurch of Jesus Christ of the Latter-day Saints. Family History Center, Greensboro, N.C.$3Microfilm


b2559560a	563 _ _ $aNLM copy bound in contemporary Cambridge-style binding.$5DNLM

b9021086a	563 _ _ $aRebacked tooled old calf, with bosses and clasps (the latter missing on upper edge). "333" written on inner cover. Front endpaper is vellum leaf from a 14th century service book; written in large gothic script with red and blue initials decorated with pen flourishes. Back doublure is part of a vellum leaf from a 14th century annotated digest; written in gothic script.

b4254290a	563 _ _ $aSome pages uncut.$3(Health Sciences Library, c. 1)

b3616660a	567 _ _ $aSamples from 319 quadrangles (1 degree x 2 degrees) beginning in 1976 and ending in 1980; four main sample types represented: stream sediment, soil, surface water, and ground water. Each sample analyzed for uranium and as many as 58 other elements including sulfate.

b5250152a	567 8 _ $aThe Protocol for Assessing Community Excellence in Environmental Health (PACE EH) offers local health officials guidance in conducting a community-based environmental health assessment and creating an accurate and verifiable profile of the community's environmental health status. The process is designed to improve decision making by taking a collaborative community-based approach to generating an action plan that is based on a set of priorities that reflect both an accurate assessment of local environmental health status and an understanding of public values and priorities. The methodology takes the user through a series of tasks to engage the public, collect necessary and relevant information related to community environmental health concerns, rank issues, and set local priorities for action. At the heart are three core processes: developing new relationships with community stakeholders, expanding understanding about the relationship between human health and the state of the environment, and redefining a leadership role for public health officials in environmental health.

