:toc:
:toc-placement!:

= Other Argot fields
Documentation of miscellaneous simpler Argot fields.

toc::[]

== `creator_main`


== `donor`
Follows https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_index_only_value.adoc[`index_only_value`] Argot pattern.

Indexed field used to power electronic bookplates or other institution-specific donor-related features.

Does *not* display.

[NOTE]
====
*Data mapping to the `donor` field is completely institution-specific.* 

Donor names for display should be mapped to `names` or `note_local` field as appropriate to the data in the field.

541 notes are already mapped to `note_local`.

7XX name fields with relator term or code for donor are already mapped to `names`.
====


== `edition`

Follows https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_labeled_indexed_value.adoc[`labeled_indexed_value`] Argot pattern.

Displayed with record summary data, as it is very important for identifying/selecting desired items.

MARC 254 is mapped here along with the expected 250 field data because it functions as a specific type of edition-like statement for printed music. 

=== UNCb6995648 -- 250 with $3 label
[source]
----
=245  12$aL'equitazione nell'antica Roma /$cAntonio Sestili.
=250  \\$3Vol. 2:$a1a ed.
----

[source,ruby]
----
[
 {'label' => 'Vol. 2', 'value' => '1a ed.'}
]
----

=== UNCb8862222 -- 250 and 254

[source]
----
=245  00$aGather /$c[Kelly Dobbs Mickus, executive editor ; Kathryn R. Cuddy, Diana Macalintal, Dominic Trumfio, editors].
=250  \\$a3rd ed.
=254  \\$aChoir edition.
----

[source,ruby]
----
[
 {'value' => '3rd ed.'},
 {'value' => 'Choir edition.'}
]
----

=== UNCb9060153 -- 254 alone

[source]
----
=245  10$aViolin concerto :$bthe bulls of Bashan : 2000 /$cGavin Bryars.
=254  \\$aStudy score.
----

[source,ruby]
----
[
 {'value' => 'Study score.'}
]
----

=== UNCb9163893 -- 250 with $b

[source]
----
=245  00$aPravāsī Bhāratīya Hindī sāhitya :$bPhījī, Sūrīnāma, Dakshiṇa Aprīkā, aura Môriśasa /$csampādaka, Vimaleśa Kānti Varmā ; saha-sampādaka, Dhīrā Varmā, Bhāvanā Saksainā, Sunandā Vī. Asthānā, Alakā Dhanapata = Pravasi Bharatiya Hindi sahitya : an anthology of creative Hindi writings of Indian diaspora / edited by Dr. Vimlesh Kanit Verma.
=250  \\$aPrathama saṃskaraṇa =$bFirst edition.
----

[source,ruby]
----
[
 {'value' => 'Prathama saṃskaraṇa = First edition.'}
]
----

=== UNCb1513078 -- 250 with linked 880

[source]
----
=250  \\$6880-04$a︠I︡Ubileĭnoe izd.
=880  \\$6250-04/(N$aЮбилейное изд.
----

[source,ruby]
----
'edition' => [
  { 'value' => '︠I︡Ubileĭnoe izd.' },
  { 'value' => 'Юбилейное изд.',
    'lang' => 'rus' }
]
----

=== UNCb8679039 -- non-Roman characters in 250

[source]
----
=250  \\$a2015年デジタル版
----

[source,ruby]
----
'edition' => [
  { 'value' => '2015年デジタル版',
    'lang' => 'cjk' }
]
----


== `issn`

[NOTE]
====
If starting from scratch, I would NOT model ISSN this way. This is how it was initially structured by Luke based on Endeca treatment. Given that we are currently in crunch time for 2018-08-01 release, I am leaving it structured as is.
====

The `issn` field has two sub-elements:

* primary
** the primary ISSN referring specifically to the format/media version described by this record
** displayed
** indexed

* linking
** the ISSN used to link/gather multiple format/media versions of the title
** NOT displayed (will often be recorded in the MARC record in fields where this ISSN will be displayed/indexed as part of a related work
** indexed

=== UNCb1323841

[source]
----
=022  \\$a0140-6736$z0023-7507
=022  \\$a0099-5355
----

[source,ruby]
----
'issn' => {'primary' = ['0140-6736', '0099-5355'] }
----

=== UNCb7821842

[source]
----
=022  \\$a2213-9109$l2213-9095
----

[source,ruby]
----
'issn' => {'primary' = ['2213-9109'],
           'linking' = ['2213-9095']}
----

== `statement_of_responsibility`

Follows https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_index_and_display_value.adoc[`index_and_display_value`] Argot pattern.

=== UNCb1000019

[source]
----
=245  04$aThe Philosophy of C. I. Lewis.$cEdited by Paul Arthur Schilpp.
----

[source,ruby]
----
'statement_of_responsibility' => [
   { 'value' => 'Edited by Paul Arthur Schilpp.' }
 ]
----

=== UNCb1042217

[source]
----
=245  10$6880-02$aNachalo veka =$bBeginning of the century /$cAndreĭ Belyĭ.
=880  10$6245-02/(N$aНачало века =$bBeginning of the century /$cАндрей Белый.
----

[source,ruby]
----
'statement_of_responsibility' => [
   { 'value' => 'Andreĭ Belyĭ.' },
   { 'value' => 'Андрей Белый.',
     'lang' => 'rus' }
 ]
----

=== UNCb8453596

[source]
----
=245  10$aShirley$h[electronic resource] :$bA Tale /$c杨丹.
----

[source,ruby]
----
'statement_of_responsibility' => [
   { 'value' => '杨丹.',
     'lang' => 'cjk' }
 ]
----


== `title_main`

* Array because there may be one or more vernacular versions of the title in 245

[NOTE]
====
$h omitted because:

* It's not actually part of the title
** Which means inclusion of $h in main title can mess up known item searching/relevance ranking
* $h is no longer added to the 245 in RDA.
** This means it's there in a lot of older records, but NOT there in many/most new records.
** Displaying it gives users a false signal to latch onto to determine the format of items, since not all e-resources will have '[electronic resource]' in the title, and not all serials will have '[serial]' in the title, etc.

====

=== UNCb7371039

[source]
----
=245  04$aThe Whitechapel murders papers$h[electronic resource] :$bletters relating to the "Jack the Ripper" killings,$f1888-1889.
----

[source,ruby]
----
[
 {'value' => 'The Whitechapel murders papers : letters relating to the "Jack the Ripper" killings, 1888-1889.'}
]
----

[NOTE]
====
Ideally, retain non-']' punctuation/symbols at the end of $h. More details on this https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_punctuation_preceding_subfield.adoc[here].

If this is too complicated, skip it for now and accept result with ':' missing.
====

=== UNCb1142419

[NOTE]
====
This is an example to show why this field is structured as it is.

It doesn't need to be included in the MARC-to-Argot spec/tests.

There will be separate tests written for vernacular processing.
====

[source]
----
=245  10$6880-02$aP︠i︡ata︠i︡a ︠i︡azva =$bThe fifth pestilence /$cAlekseĭ Remizov = A.M. Remizov ; introduction by J.D. West.
=880  10$6245-02/(N$aПятая язва =$bThe fifth pestilence /$cАлексей Ремизов = A.M. Remizov ; introduction by J.D. West.
----

[source,ruby]
----
[
 {'value' => 'P︠i︡ata︠i︡a ︠i︡azva = The fifth pestilence'},
 {'value' => 'Пятая язва = The fifth pestilence',
  'lang' => 'rus'} 
]
----

== `title_sort`

The value used to sort results by title.

Limit to only one value.

Value should be the title portion of 245 field with the following transformations/normalizations applied:

* non-filing characters removed
* entire value downcased
* NFKD normalization applied -- See http://www.unicode.org/reports/tr15/tr15-29.html
* Replace '&' with 'and'
* Replace common ligatures with separate letters
* Normalize punctuation and spaces

For the full details, search for "def normalize_string_for_sorting(str)" in https://github.com/trln/marc-to-argot/blob/master/lib/marc_to_argot/macros/shared/title.rb

=== UNCb7371039

[source]
----
=245  04$aThe Whitechapel murders papers$h[electronic resource] :$bletters relating to the "Jack the Ripper" killings,$f1888-1889.
----

[source,ruby]
----
'whitechapel murders papers letters relating to the jack the ripper killings 1888 1889'
----

