:toc:
:toc-placement!:

= Other Argot fields
Documentation of miscellaneous simpler Argot fields.

toc::[]

== `donor`
Follows `index_and_display_value` Argot pattern.

Indexed field used to power electronic bookplates or other institution-specific donor-related features.

Does *not* display.

[NOTE]
====
*Data mapping to the `donor` field is completely institution-specific.* 

Donor names for display should be mapped to `names` or `note_local` field as appropriate to the data in the field.

541 notes are already mapped to `note_local`.

7XX name fields with relator term or code for donor are already mapped to `names`.
====

== `edition`

Follows `labeled_value` Argot pattern.

Displayed with record summary data, as it is very important for identifying/selecting desired items.

MARC 254 is mapped here because it functions as a specific type of edition-like statement for printed music. 

=== UNCb6995648 -- 250 with $3 label
[source]
----
=245  12$aL'equitazione nell'antica Roma /$cAntonio Sestili.
=250  \\$3Vol. 2:$a1a ed.
----

[source,ruby]
----
[
 {'label' => 'Vol. 2', 'value' => '1a ed.'}
]
----

=== UNCb8862222 -- 250 and 254

[source]
----
=245  00$aGather /$c[Kelly Dobbs Mickus, executive editor ; Kathryn R. Cuddy, Diana Macalintal, Dominic Trumfio, editors].
=250  \\$a3rd ed.
=254  \\$aChoir edition.
----

[source,ruby]
----
[
 {'value' => '3rd ed.'},
 {'value' => 'Choir edition.'}
]
----

=== UNCb9060153 -- 254 alone

[source]
----
=245  10$aViolin concerto :$bthe bulls of Bashan : 2000 /$cGavin Bryars.
=254  \\$aStudy score.
----

[source,ruby]
----
[
 {'value' => 'Study score.'}
]
----

=== UNCb9163893 -- 250 with $b

[source]
----
=245  00$aPravāsī Bhāratīya Hindī sāhitya :$bPhījī, Sūrīnāma, Dakshiṇa Aprīkā, aura Môriśasa /$csampādaka, Vimaleśa Kānti Varmā ; saha-sampādaka, Dhīrā Varmā, Bhāvanā Saksainā, Sunandā Vī. Asthānā, Alakā Dhanapata = Pravasi Bharatiya Hindi sahitya : an anthology of creative Hindi writings of Indian diaspora / edited by Dr. Vimlesh Kanit Verma.
=250  \\$aPrathama saṃskaraṇa =$bFirst edition.
----

[source,ruby]
----
[
 {'value' => 'Prathama saṃskaraṇa = First edition.'}
]
----

== `title_main`

* Array because there may be one or more vernacular versions of the title in 245

[NOTE]
====
$h omitted because:

* It's not actually part of the title
** Which means inclusion of $h in main title can mess up known item searching/relevance ranking
* $h is no longer added to the 245 in RDA.
** This means it's there in a lot of older records, but NOT there in many/most new records.
** Displaying it gives users a false signal to latch onto to determine the format of items, since not all e-resources will have '[electronic resource]' in the title, and not all serials will have '[serial]' in the title, etc.

====

=== UNCb7371039

[source]
----
=245  04$aThe Whitechapel murders papers$h[electronic resource] :$bletters relating to the "Jack the Ripper" killings,$f1888-1889.
----

[source,ruby]
----
[
 {'value' => 'The Whitechapel murders papers : letters relating to the "Jack the Ripper" killings, 1888-1889.'}
]
----

[NOTE]
====
Ideally, retain non-']' punctuation/symbols at the end of $h. More details on this https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_punctuation_preceding_subfield.adoc[here].

If this is too complicated, skip it for now and accept result with ':' missing.
====

=== UNCb1142419

[NOTE]
====
This is an example to show why this field is structured as it is.

It doesn't need to be included in the MARC-to-Argot spec/tests.

There will be separate tests written for vernacular processing.
====

[source]
----
=245  10$6880-02$aP︠i︡ata︠i︡a ︠i︡azva =$bThe fifth pestilence /$cAlekseĭ Remizov = A.M. Remizov ; introduction by J.D. West.
=880  10$6245-02/(N$aПятая язва =$bThe fifth pestilence /$cАлексей Ремизов = A.M. Remizov ; introduction by J.D. West.
----

[source,ruby]
----
[
 {'value' => 'P︠i︡ata︠i︡a ︠i︡azva = The fifth pestilence'},
 {'value' => 'Пятая язва =$bThe fifth pestilence',
  'lang' => 'rus'} 
]
----

== `title_sort`

The value used to sort results by title.

Limit to only one value.

Value should be the title portion of 245 field with non-filing characters removed

=== UNCb7371039

[source]
----
=245  04$aThe Whitechapel murders papers$h[electronic resource] :$bletters relating to the "Jack the Ripper" killings,$f1888-1889.
----

[source,ruby]
----
'Whitechapel murders papers : letters relating to the "Jack the Ripper" killings, 1888-1889.'
----

