:toc:
:toc-placement!:

= Argot fields related to physical description
== MARC source fields

* 342 physical description details
* 344 physical description details
* 345 physical description details
* 346 physical description details
* 347 physical description details
* 352 physical description details

* 340 physical description details
* 342 physical description details
* 344 physical description details
* 345 physical description details
* 346 physical description details
* 347 physical description details
* 352 physical description details



* 382 - medium of performance -- map to genre
* 383 - map $c, $d to misc_id as Thematic Index Number
* 384 - map to genre



toc::[]

== `physical_description`

=== processing details

* Array

* Follows the `labeled_value` pattern, where:
** The value should be indexed
** label + value should be displayed

* `label` = $3 if present
* `value` = $a, b, c, e, f, g (concatenate subfield values)

* `value` is keyword indexed

=== UNCb9007512

[source]
----
=300  \\$3videodiscs$a1 videodisc (107 min.) :$bsound, color ;$c4 3/4 in.
=300  \\$3volumes$a286 pages :$billustrations ;$c21 cm.
----

[source,ruby]
----
{'label' => 'videodiscs',
 'value' => '1 videodisc (107 min.) : sound, color ; 4 3/4 in.'},
{'label' => 'volumes',
 'value' => '286 pages : illustrations ; 21 cm.'}
----

=== UNCb8511611

[source]
----
=300  \\$a1 reel of 1 (18 min., 30 sec.) (656 ft.) :$bopt sd., b&w ;$c16 mm.$3print +$ewith study guide.
----

[source,ruby]
----
{'label' => 'print',
'value' => '1 reel of 1 (18 min., 30 sec.) (656 ft.) : opt sd., b&w ; 16 mm. + with study guide.'}
----
			   
== `physical_description_details`

=== processing details

* Array

* Follows the `labeled_value` pattern, where:
** The value should be indexed
** label + value should be displayed


* `value` - one element added to field array per unique subfield delimiter. If the same subfield is repeated, the values are concatenated. Subfields defined differ per MARC field below
* `label` - label is based on subfield value (see table below for each MARC field) and, where present, $3. 

* `value` is keyword indexed

=== 340

*Subfield-to-label translation*

[cols=2*,options=header]
|===
|Subfield delimiter
|Label value

|a
|Base/substrate material

|b
|Dimensions

|c
|Medium

|d
|Technique

|e
|Support material

|f
|Production rate/ratio

|g
|Color characteristics

|h
|Found in/on

|i
|Use requires

|j
|Generation of reproduction

|k
|Layout

|m
|Book format

|n
|Font size

|o
|Polarity
|===

==== UNCb7791362

[source]
----
=340  \\$3shell pin$awood$b3 x 4 cm$dcarved
----

[source,ruby]
----
[
  {'label' => 'Shell pin: Base/substrate material',
   'value' => 'wood'},
  {'label' => 'Shell pin: Dimensions',
   'value' => '3 x 4 cm'},
  {'label' => 'Shell pin: Technique',
   'value' => 'carved'}
]
----

==== UNCb7641857

[source]
----
=340  \\$avinyl$aplastic$b35 x 23 x 13 cm$cpaint$ewood$2rda
----

[source,ruby]
----
[
  {'label' => 'Base/substrate material',
   'value' => 'vinyl; plastic'},
  {'label' => 'Dimensions',
   'value' => '35 x 23 x 13 cm'},
  {'label' => 'Medium',
   'value' => 'paint'},
  {'label' => 'Support material',
   'value' => 'wood'}
]
----

==== mock

[source]
----
=340  \\$aplastic$ametal$b4 3/4 in.$f1.4 m/s$gpolychrome$gblack and white$hfront cover pocket$joriginal
=340  \\$apaper tape$dpunched$iIbord Model 74 tape reader
=340  \\$apaper$dprinted$kdouble sided$kvertical score$mfolio$nlarge print
=340  \\$aacetate$onegative
----

[source,ruby]
----
{'label' => 'Base/substrate material',
 'value' => 'plastic; metal'},
{'label' => 'Dimensions',
 'value' => '4 3/4 in.'},
{'label' => 'Production rate/ratio',
 'value' => '1.4 m/s'},
{'label' => 'Color characteristics',
 'value' => 'polychrome; black and white'},
{'label' => 'Found in/on',
 'value' => 'front cover pocket'},
{'label' => 'Generation of reproduction',
 'value' => 'original'},
{'label' => 'Base/substrate material',
 'value' => 'paper tape'},
{'label' => 'Technique',
 'value' => 'punched'},
{'label' => 'Use requires',
 'value' => 'Ibord Model 74 tape reader'},
{'label' => 'Base/substrate material',
 'value' => 'paper'},
{'label' => 'Technique',
 'value' => 'printed'},
{'label' => 'Layout',
 'value' => 'double sided; vertical score'},
{'label' => 'Book format',
 'value' => 'folio'},
{'label' => 'Font size',
 'value' => 'large print'},
{'label' => 'Base/substrate material',
 'value' => 'acetate'},
{'label' => 'Polarity',
 'value' => 'negative'}
----
