:toc:
:toc-placement!:

= Related works, authors, titles, ids

*Test records*
The UNC bib records referred to by bib number in this document are at:
todo

toc::[]

== Overview of 'related' fields in Argot
=== related_work
Complex, structured data field containing information about works related to the work described in the record, for which a more specific related_work_* field  has not been defined.

It must always include a title, but may lack an author (in the case of diffuse or unknown authorship).

An imperfect aspect of this is:

 - Some of the MARC source fields for `related_work` are themselves specified so that well-formed 'uniform work identifiers' are the result (main entry + title proper).
 - Other MARC source fields for `related_work` have been less clearly specified, so that they may include
 -- title data beyond title proper (other title info, parallel title, alternative title)
 -- author name that would not be recorded as main entry (or that would be recorded as main entry, but in a different form)
 -- other bib data about related work: publication, extent, ISBNs, ISSNs, etc
 
==== `related_work` subelements
 - `label`: Contextualizing info derived from data in field itself and/or the MARC tag or indicator values. Will not always be present.
 -- Display but do not index
 - `author`: The author name related portion. Some works do not have an author, so will lack this part.
 -- indexed as `author_related`
 -- combined with `title` segment to create indexed `work_citation_related` value 
 - `title`: The title related portion. All works must have a title, so this segment should always be present.
 -- indexed as `title_related`
 -- combined with `author` segment to create indexed `work_citation_related` value for in-catalog hyperlink querying and possible use in autosuggest
 -- subelements of the title portion are separated with `||` to allow for adaptive hyperlinking. This delimiter is stripped out of the display.
 - `details`: other bib data about related work
 -- displayed after the author/title hyperlink, but not included in hyperlink
 -- not indexed
 - `isbn`: ISBN of cited related work.
 -- displayed, with `ISBN:` label, at end of field display
 -- indexed in `isbn_related`
 - `issn`: ISSN of cited related work.
 -- displayed, with `ISSN:` label, at end of field display
 -- indexed in `issn_related`


==== Source data
`related_work` gets populated from fields where it is possible to record name-title entries, *if a title is recorded in the field*.

- 700, 710, or 711 with i2 = blank and including a $t

=== related_title

==== Source data

- 740 with i2 = blank

== Overview of derivative fields

- `work_citation_related`: indexed value for in-catalog hyperlink querying and possible use in autosuggest. Keyword search should include these values.
- `author_related`: will be retrieved, but relranked low, in an author search
- `title_related`: will be retrieved, but relranked low, in a title search

== Examples
=== UNCb7641376 - 700 with $i
==== MARC
 100 1 _ $aSabuda, Robert,$eauthor.
 245 1 4 $aThe little mermaid :$ba pop-up adaptation of the classic fairy tale /$cRobert Sabuda.
 700 1 _ $iBased on:$aAndersen, H. C.$q(Hans Christian),$d1805-1875.$tLille havfrue.$lEnglish.

==== Argot
[source,javascript]
----
{
 "related_work": {
  "label": "Based on:",
  "author": "Andersen, H. C. (Hans Christian), 1805-1875.",
  "title": "Lille havfrue.||English."
 }
}
----

==== Behavior

*Displayed:*

Based on: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Andersen%2C%20H.%20C.%20(Hans%20Christian)%2C%201805-1875&N=0[Andersen, H. C. (Hans Christian), 1805-1875.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Lille%20havfrue|Andersen%2C%20H.%20C.%20(Hans%20Christian)%2C%201805-1875&N=0[Lille havfrue.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Lille%20havfrue.%20English|Andersen%2C%20H.%20C.%20(Hans%20Christian)%2C%201805-1875&N=0[English.]

*Combined `work_citation_related` index entry for intracatalog linking (and autosuggest?):*

- Andersen, H. C. (Hans Christian), 1805-1875. Lille havfrue. English.


*`author_related` index entry:*

- Andersen, H. C. (Hans Christian), 1805-1875.

*`title_related` index entry:*

- Lille havfrue. English

=== UNCb8993417 - 700, with $3 and $i
==== MARC
_Some fields that would be mapped to `related_work` are omitted from example._

 245 0 0 $aIf this world could stop.
 264 _ 1 $a[New Haven, CT] :$bBad Wolf Music Group,$c[2014]
 700 1 _ $32nd work$iMusical setting of (work):$aJoyce, James,$d1882-1941.$tUlysses.
 700 1 _ $33rd work$iMusical setting of (work):$aWhiteley, Opal Stanley.$tClan of the lichens.
 700 1 _ $35th work$iMusical setting of (work):$aDove, Rita.$tIf this world could stop.

==== Argot
[source,javascript]
----
{
 "related_work": {
  "label": "2nd work: Musical setting of:",
  "author": "Joyce, James, 1882-1941",
  "title": "Ulysses."
 },
 "related_work": {
  "label": "3rd work: Musical setting of:",
  "author": "Whiteley, Opal Stanley.",
  "title": "Clan of the lichens."
 },
  "related_work": {
  "label": "5th work: Musical setting of:",
  "author": "Dove, Rita.",
  "title": "If this world could stop."
 }
}
----

==== Behavior

*Displayed:*

- 2nd work: Musical setting of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Joyce%2C%20James%2C%201882-1941.&N=0[Joyce, James, 1882-1941.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Ulysses.|Joyce%2C%20James%2C%201882-1941.&N=0[Ulysses.]
- 3rd work: Musical setting of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Whiteley%2C%20Opal%20Stanley.&N=0[Whiteley, Opal Stanley.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Clan%20of%20the%20lichens.|Whiteley%2C%20Opal%20Stanley.&N=0[Clan of the lichens.]
- 5th work: Musical setting of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Dove%2C%20Rita.%20&N=0[Dove, Rita.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=If%20this%20world%20could%20stop.|Dove%2C%20Rita.%20&N=0[If this world could stop.]
  
*Combined `work_citation_related` index entry for intracatalog linking (and autosuggest?):*

- Joyce, James, 1882-1941. Ulysses.
- Whiteley, Opal Stanley. Clan of the lichens.
- Dove, Rita. If this world could stop.

*`author_related` index entry:*

- Joyce, James, 1882-1941.
- Whiteley, Opal Stanley.
- Dove, Rita.

*`title_related` index entry:*

- Ulysses.
- Clan of the lichens.
- If this world could stop.

=== UNCb8843477 - 710 with $i
==== MARC
 100 1 _ $aJacobson, Sidney,$eauthor.
 245 1 4 $aThe torture report :$ba graphic adaptation /$cSid Jacobson and Ernie Colón ; introduction by Jane Mayer ; afterword by Scott Horton.
 710 1 _ $iGraphic novelization of (work):$aUnited States.$bCongress.$bSenate.$bSelect Committee on Intelligence.$tSenate Intelligence Committee report on torture.

==== Argot
[source,javascript]
----
{
 "related_work": {
  "label": "Graphic novelization of:",
  "author": "United States. Congress. Senate. Select Committee on Intelligence.",
  "title": "Senate Intelligence Committee report on torture."
 }
}
----

==== Behavior

*Displayed:*

Graphic novelization of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=United%20States.%20Congress.%20Senate.%20Select%20Committee%20on%20Intelligence.&N=0[United States. Congress. Senate. Select Committee on Intelligence.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Senate%20Intelligence%20Committee%20report%20on%20torture.|United%20States.%20Congress.%20Senate.%20Select%20Committee%20on%20Intelligence.&N=0[Senate Intelligence Committee report on torture.]
  


*Combined `work_citation_related` index entry for intracatalog linking (and autosuggest?):*

- United States. Congress. Senate. Select Committee on Intelligence. Senate Intelligence Committee report on torture.

*`author_related` index entry:*

- United States. Congress. Senate. Select Committee on Intelligence.

*`title_related` index entry:*

- Senate Intelligence Committee report on torture.

=== UNCb8843477 - 710 with $i
==== MARC
 100 1 _ $aEmerson, Joseph,$d1777-1833.
 245 1 4 $aThe Evangelical primer$h[microform].
 711 2 _ $aWestminster Assembly$d(1643-1652).$tShorter catechism.$f1809.

==== Argot
[source,javascript]
----
{
 "related_work": {
  "author": "Westminster Assembly (1643-1652).",
  "title": "Shorter catechism.||1809."
 }
}
----

==== Behavior

*Displayed:*

http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Westminster%20Assembly%20(1643-1652).&N=0[Westminster Assembly (1643-1652).] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Shorter%20catechism.|Westminster%20Assembly%20(1643-1652).&N=0[Shorter catechism.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Shorter%20catechism.%201809.|Westminster%20Assembly%20(1643-1652).&N=0[1809.]
  
*Combined `work_citation_related` index entry for intracatalog linking (and autosuggest?):*

- Westminster Assembly (1643-1652). Shorter catechism. 1809.

*`author_related` index entry:*

- Westminster Assembly (1643-1652).

*`title_related` index entry:*

- Shorter catechism. 1809.

=== UNCb6869637 - 740 and 786, somewhat duplicated data
In general, fields that map to `related_work` are likely to have fuller, richer info than fields that map to `related_title`

Because of system limitations for displaying MARC 76X-78X (Linking Entries), the data recorded in them is often duplicated in less informative fields.

*Ideally we could figure out some way to minimize display of duplicated data.* One idea for this could be:

- Process `related_work` first.
- When its processing is complete, grab array of all the `title` subelements that were set for `related_works` and send to Traject context clipboard
- When processing fields that map to `related title`, skip any where the title already exists in the context clipboard array


==== MARC
 245 0 4 $aThe international plant names index$h[electronic resource].
 500 _ _ $a"The records in IPNI come from three sources: the Index Kewensis (IK), the Gray Card Index (GCI) and the Australian Plant Names Index (APNI)." --"About the index" page (viewed Nov. 10, 2011).
 740 0 _ $aIndex Kewensis.
 740 0 _ $aGray card index.
 740 0 _ $aAustralian plant name index.
 786 0 _ $tAustralian plant name index.$d[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium$w(DLC)  2009252503$w(OCoLC)64343431
 786 0 _ $tIndex Kewensis plantarum phanerogamarum. Supplementum$w(DLC)   89659069$w(OCoLC)2992677
 786 0 _ $tIndex Kewensis. Supplement$w(DLC)sn 88021550$w(OCoLC)16733857
 786 0 _ $tGray card index.$dCambridge, Mass. : Harvard University Herbraria, [c1992-]$w(OCoLC)43851144

==== Argot (without deduplication)
[source,javascript]
----
{
 "related_work": [
 {
  "label": "Data source:",
  "title": "Australian plant name index.",
  "details": "[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium"
 },
 {
  "label": "Data source:",
  "title": "Index Kewensis plantarum phanerogamarum. Supplementum"
 },
  {
  "label": "Data source:",
  "title": "Index Kewensis. Supplement"
 },
 {
  "label": "Data source:",
  "title": "Gray card index.",
  "details": "Cambridge, Mass. : Harvard University Herbraria, [c1992-]"
 }
 ],
 "related_title": [
  {"title": "Index Kewensis."},
  {"title": "Gray card index."},
  {"title": "Australian plant name index."} 
 ]
}
----

==== Argot (ideal, deduplicated)
[source,javascript]
----
{
 "related_work": [
 {
  "label": "Data source:",
  "title": "Australian plant name index.",
  "details": "[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium"
 },
 {
  "label": "Data source:",
  "title": "Index Kewensis plantarum phanerogamarum. Supplementum"
 },
  {
  "label": "Data source:",
  "title": "Index Kewensis. Supplement"
 },
 {
  "label": "Data source:",
  "title": "Gray card index.",
  "details": "Cambridge, Mass. : Harvard University Herbraria, [c1992-]"
 }
 ],
  "related_title": [
  {"title": "Index Kewensis."}
 ]
}
----

==== Behavior (based on deduplicated Argot)
*Displayed:*
RELATED WORKS:

- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Australian%20plant%20name%20index.&N=0[Australian plant name index.] [Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium
- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Index%20Kewensis%20plantarum%20phanerogamarum.%20Supplementum&N=0[Index Kewensis plantarum phanerogamarum. Supplementum]
- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Index%20Kewensis.%20Supplement&N=0[Index Kewensis. Supplement]
- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Gray%20card%20index.&N=0[Gray card index.] Cambridge, Mass. : Harvard University Herbraria, [c1992-]
- http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Index%20Kewensis.&N=0[Index Kewensis.]
  
*Combined `work_citation_related` index entry for intracatalog linking (and autosuggest?):*

- Australian plant name index.
- Index Kewensis plantarum phanerogamarum. Supplementum
- Index Kewensis. Supplement
- Gray card index.
- Index Kewensis.

*`author_related` index entry:*

na

*`title_related` index entry:*

- Australian plant name index.
- Index Kewensis plantarum phanerogamarum. Supplementum
- Index Kewensis. Supplement
- Gray card index.
- Index Kewensis.

== Field-specific processing notes
=== 786

- Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/76X-78X_linking_entry_processing.adoc[76X-78X linking entry processing procedures].
- If no $i, `label`  =  `Data source:`

