:toc:
:toc-placement!:

= `related_work` field

"Authorized access point" (or approximation thereof) for *work related to the resource described by the catalog record*

*Uses the https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_work_entry.adoc[`work_entry` Argot pattern]*

toc::[]

== Processing notes

* Segment/subfield delimiter '||' is provided in title portion to facilitate adaptive hyperlinking
* `display` = defaults to true (so it doesn't need to be set explicitly)
* `type` = varies by source MARC field, as shown in table below

[cols=2*,options=header]
|===
|Source MARC
|`type` value

|700
|related

|710
|related

|711
|related

|730
|related

|740
|related

|765
|translation_of

|767
|translated_as

|770
|has_supplement

|772
|supplement_to

|773
|host_item

|775
|alt_edition

|777
|issued_with

|780
|earlier

|785
|later

|786
|data_source

|787
|related
|===

== Examples (parallel with `included_work`-- READY TO IMPLEMENT)
The examples in the section below demonstrate how, for these fields, the processing for `related_work` is nearly identical to that for `included_work`.

The differences are:

* In the MARC, the i2 here is blank instead of 2
* In the Argot, `type` is 'related' instead of 'included'


=== 700

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X00.adoc[general spec on processing X00 fields]

==== UNCb5976398 mock -- omit relator code

[source]
----
=700  1\$aSaint-Saëns, Camille,$d1835-1921.$4cmp$tQuartets,$mviolins (2), viola, cello,$nno. 2, op. 153,$rG major
----

[source,ruby]
----
[
  {'type'=>'related',
   'author'=>'Saint-Saëns, Camille, 1835-1921.',
   'title'=>'Quartets,||violins (2), viola, cello,||no. 2, op. 153,||G major'}
]
----

==== UNCb8630424 mock -- omit relator term

$e is preceded by ', ' and ends with a period signifying the end of the author name segment.

We want to remove the comma that precedes a $e, but keep or provide a period at the end of the author segment.

[source]
----
=700  1\$aSchwenkel, Christina,$eauthor.$tArchitecture and dwelling in the 'war of destruction' in Vietnam.
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Schwenkel, Christina.',
 'title'=>'Architecture and dwelling in the \'war of destruction\' in Vietnam.'}
]
----

==== UNCb8069067 mock -- `label` from $i; `details` from $g

[source]
----
=700  1\$iFacsimile of:$aFerrini, Vincent,$d1913-2007.$tTidal wave : poems of the great strikes.$f1945$g(New York : Great-Concord Publishers)
----

[source,ruby]
----
[
{'type'=>'related',
 'label'=>'Facsimile of',
 'author'=>'Ferrini, Vincent, 1913-2007.',
 'title'=>'Tidal wave : poems of the great strikes.||1945',
 'details'=>'(New York : Great-Concord Publishers)'}
]
----


*Display*

*Related items:*

* Facsimile of: http://query.info/on_author[Ferrini, Vincent, 1913-2007.] http://query.info/on_title[Tidal wave : poems of the great strikes.] http://query.info/on_title_to_left_plus[1945] (New York : Great-Concord Publishers)


*Indexed as*

`related_author`: Ferrini, Vincent, 1913-2007.

`related_title`: Tidal wave : poems of the great strikes. 1945

`related_work`: Ferrini, Vincent, 1913-2007. Tidal wave : poems of the great strikes. 1945


==== UNCb7416515 mock -- label from $3 and $i; special $i processing

See sections of https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_i.adoc[$i spec] related to deleting WEMI terms and RDA terminology replacements.

[source]
----
=700  0\$3Tome 1, volume 1$iContainer of (expression):$aPlotinus.$tPeri tou kalou.$lFrench$s(Achard and Narbonne)
----

[source,ruby]
----
[
{'type'=>'related',
 'label'=>'Tome 1, volume 1: Contains',
 'author'=>'Plotinus.',
 'title'=>'Peri tou kalou.||French||(Achard and Narbonne)'}
]
----

==== UNC mock -- $g as part of `author`

[source]
----
=700  1\$aName, Author,$g(Test name),$d1944-.$tTest title.
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Name, Author, (Test name), 1944-.',
 'title'=>'Test title.'}
]
----

=== 710

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X10.adoc[general spec on processing X10 fields]

==== UNCb1619280 mock -- no $t, but has $k

[source]
----
=710  2\$aKungliga Biblioteket (Sweden).$kManuscript.$nKB787a.$lChurch Slavic.$f1966.
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Kungliga Biblioteket (Sweden).',
 'title'=>'Manuscript.||KB787a.||Church Slavic.||1966.'}
]
----

==== UNCb1616558 mock -- $n, $d part of `author`

[source]
----
=710  1\$aUnited States.$bCongress$n(94th, 2nd session :$d1976).$tMemorial services held in the House of Representatives and Senate of the United States, together with remarks presented in eulogy of Jerry L. Litton, late a Representative from Missouri.$f197.
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'United States. Congress (94th, 2nd session : 1976).',
 'title'=>'Memorial services held in the House of Representatives and Senate of the United States, together with remarks presented in eulogy of Jerry L. Litton, late a Representative from Missouri.||197.'}
]
----

==== UNCb1298659 mock -- $n part of `title` 

[source]
----
=710  1\$aNorth Carolina.$bBuilding Code Council.$tNorth Carolina state building code.$n1,$pGeneral construction.$n11X,$pMaking buildings and facilities accessible to and usable by the physically handicapped.
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'North Carolina. Building Code Council.',
 'title'=>'North Carolina state building code.||1,||General construction.||11X,||Making buildings and facilities accessible to and usable by the physically handicapped.'}
]
----

==== UNCb2383742

[source]
----
=710  1\$aGermany (East).$tTreaties, etc.$gGermany (West),$d1990 May 18.$f1990.
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Germany (East).',
 'title'=>'Treaties, etc.||Germany (West),||1990 May 18.||1990.'}
]
----

==== UNCb4364438 mock -- has $4

[source]
----
=710  2\$aCafé Tacuba (Musical group)$4prf$t12/12
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Café Tacuba (Musical group)',
 'title'=>'12/12'}
]
----

=== 711

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X11.adoc[general spec on processing X11 fields]

==== UNCb6256550 mock -- $e kept; $d before $t or k
[source]
----
=711  2\$aGreat Central Fair for the U.S. Sanitary Commission$d(1864 :$cPhiladelphia, Pa.).$eCommittee on Public Charities and Benevolent Institutions.$tPhiladelphia [blank] 1864. 619 Walnut Street. To [blank] ...
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Great Central Fair for the U.S. Sanitary Commission (1864 : Philadelphia, Pa.). Committee on Public Charities and Benevolent Institutions.',
 'title'=>'Philadelphia [blank] 1864. 619 Walnut Street. To [blank] ...'}
]
----

==== UNCb1099159 mock -- $d and $g after $t; $x

[source]
----
=711  2\$aDeutsch Foundation Conference$d(1930 :$cUniversity of Chicago).$tCare of the aged.$d2000, $f1972.$gReprint.$x1234-1234
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Deutsch Foundation Conference (1930 : University of Chicago).',
 'title'=>'Care of the aged.||2000,||1972.',
 'details'=>'Reprint.',
 'issn'=>'1234-1234'}
]
----

=== 730

==== UNCb7339540 mock -- $x

[source]
----
=730  0\$aCahiers de civilisation médiévale.$pBibliographie.$x0240-8678
----

[source,ruby]
----
[
{'type'=>'related',
 'title'=>'Cahiers de civilisation médiévale.||Bibliographie.',
 'issn'=>'0240-8678'}
]
----

==== UNCb4873545 mock -- $a and $t in field

[source]
----
=730  0\$aJane Pickering's lute book.$tDrewries Accord's;$oarr.
----

[source,ruby]
----
[
{'type'=>'related',
 'title'=>'Jane Pickering\'s lute book.||arr.',
 'title_variation'=>'Drewries Accord\'s;'}
]
----


==== UNCb7055039 mock -- i1 not blank or 0

[source]
----
=730  4\$iBlah (expression):$aThe magnificent Ambersons (Motion picture).$lEnglish.
----

[source,ruby]
----
[
 {'type'=>'related',
 'label'=>'Blah',
 'title'=>'Magnificent Ambersons (Motion picture).||English.',
 'title_nonfiling'=>'The magnificent Ambersons (Motion picture). English.'}
]
----

==== UNCb7644390 mock -- both $3 and $i in label

[source]
----
=730  0\$3Guide:$iBased on (expression):$aDeutsche Geschichte.$nBand 6.
----

[source,ruby]
----
[
{'type'=>'related',
 'label'=>'Guide: Based on',
 'title'=>'Deutsche Geschichte.||Band 6.'}
]
----

=== 740

==== UNCb7182040 mock -- i1 not blank or 0

[source]
----
=740  4\$aThe English pilot.$nThe fourth book : describing the West India navigation, from Hudson's-Bay to the river Amazones ...
----

[source,ruby]
----
[
{'type'=>'related',
 'title'=>'English pilot.||The fourth book : describing the West India navigation, from Hudson\'s-Bay to the river Amazones ...',
 'title_nonfiling'=>'The English pilot. The fourth book : describing the West India navigation, from Hudson\'s-Bay to the river Amazones ...'}
]
----

==== UNCb1094156

[source]
----
=740  \\$aIndustrial sales management game$p5.
----

[source,ruby]
----
[
{'type'=>'related',
 'title'=>'Industrial sales management game||5.'}
]
----

== Examples (7XX additional -- NOT YET READY)
=== 700
==== UNCb8529982 mock -- $i present; complex uniform title; $g in title

[source]
----
=700  1\$iFacsimile of (work):$aMozart, Wolfgang Amadeus,$d1756-1791.$tConcertos,$mviolin, orchestra,$nK. 219,$rA major.$gLibrary of Congress. Music Division : ML30.8b .M8 K. 219 Case.
----

[source,ruby]
----
[
{'type'=>'related',
 'label'=>'Facsimile of',
 'author'=>'Mozart, Wolfgang Amadeus, 1756-1791.',
 'title'=>'Concertos,||violin, orchestra,||K. 219,||A major.',
 'details'=>'Library of Congress. Music Division : ML30.8b .M8 K. 219 Case.'}
]
----

=== 710
==== UNCb4914240 - $i present; $g in title

[source]
----
=710  2\$iFacsimilie of (manifestation):$aConservatoire royal de musique de Bruxelles.$bBibliothèque.$kManuscript.$g16.662.
=710  2\$iFacsimilie of (manifestation):$aConservatoire royal de musique de Bruxelles.$bBibliothèque.$kManuscript.$g16.663.
----

[source,ruby]
----
[
{'type'=>'related',
 'label'=>'Facsimile of',
 'author'=>'Conservatoire royal de musique de Bruxelles. Bibliothèque.',
 'title'=>'Manuscript.',
 'details'=>'16.662.'},
{'type'=>'related',
 'label'=>'Facsimile of',
 'author'=>'Conservatoire royal de musique de Bruxelles. Bibliothèque.',
 'title'=>'Manuscript.',
 'details'=>'16.663.'}
]
----

=== 711

==== UNCb8843477 - $i not present

[source]
----
=711  2\$aWestminster Assembly$d(1643-1652).$tShorter catechism.$f1809.
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Westminster Assembly (1643-1652).',
 'title'=>'Shorter catechism.||1809.'}
]
----

== Examples (76X-78X fields -- NOT YET READY TO IMPLEMENT)
Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this set of fields.

=== 765 (`type`=translation_of)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.


==== UNCb3512881

[source]
----
=765  0\$aChina.$sLaws, etc. (Zhonghua Renmin Gongheguo fa lü hui bian).$tZhonghua Renmin Gongheguo fa lü hui bian$w(DLC)   90645849
----

[source,ruby]
----
[
  {'type'=>'translation_of',
   'author'=>'China.',
   'title'=>'Laws, etc.||(Zhonghua Renmin Gongheguo fa lü hui bian).',
   'title_variation'=>'Zhonghua Renmin Gongheguo fa lü hui bian',
   'other_ids'=>['90645849']}
]
----

==== UNCb6862243

[source]
----
=765  08$iOriginally published in France as:$tInnovations médicales en situations humanitaires.$dParis : Harmattan, c2009$z9782296100466$w(OCoLC)465089061
----

[source,ruby]
----
[
  {'type'=>'translation_of',
   'label'=>'Originally published in France as',
   'title'=>'Innovations médicales en situations humanitaires.',
   'details'=>'Paris : Harmattan, c2009',
   'isbn'=>['9782296100466'],
   'other_ids'=>['465089061']}
]
----

==== UNCb3133786 - not displayed

[source]
----
=765  1\$tItogi nauki i tekhniki. Seri︠i︡a Sovremennye problemy matematiki. Fundamentalʹnye napravleni︠i︡a$x0233-6723$w(DLC) 87645715$w(OCoLC)14198545
----

[source,ruby]
----
[
  {'type'=>'translation_of',
   'title'=>'Itogi nauki i tekhniki.||Seri︠i︡a Sovremennye problemy matematiki.||Fundamentalʹnye napravleni︠i︡a',
   'issn'=>'0233-6723',
   'other_ids'=>['87645715', '14198545'],
   'display'=>'false'}
]
----

=== 767 (`type`=translated_as)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb7043261

[source]
----
=767  08$iGerman version:$tWissenschaftliche Mitteilungen des Bosnisch-Herzegowinischen Landesmuseums. Heft A, Archäologie$x0352-1990$w(DLC)  2010223203$w(OCoLC)4818533
----

[source,ruby]
----
[
  {'type'=>'translated_as',
   'label'=>'German version',
   'title'=>'Wissenschaftliche Mitteilungen des Bosnisch-Herzegowinischen Landesmuseums.||Heft A, Archäologie'
   'issn'=>'0352-1990',
   'other_ids'=>['2010223203', '4818533']}
]
----

=== 770 (`type`=has_supplement)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb9163859

[source]
----
=770  08$isupplement (work):$tInsect pest survey. Special supplement$w(OcoLC)1032826279
----

[source,ruby]
----
[
{'type'=>'has_supplement',
 'label'=>'Supplement',
 'title'=>'Insect pest survey.||Special supplement',
 'other_ids'=>['1032826279']}
]
----

==== UNCb9147108

[source]
----
=770  0\$tBaking equipment$g1979-Dec. 1987$w(OCoLC)15639544
----

[source,ruby]
----
[
{'type'=>'has_supplement',
 'title'=>'Baking equipment',
 'details'=>'1979-Dec. 1987',
 'other_ids'=>['15639544']}
]
----

==== UNCb1256874

[source]
----
=770  1\$tFrench review. Special issue$x0271-3349$g1970-74
----

[source,ruby]
----
[
{'type'=>'has_supplement',
 'title'=>'French review. Special issue',
 'issn'=>'0271-3349',
 'display'=>'false'}
]
----

=== 772 (`type`=supplement_to)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb7383700 -- display; $r present

[source]
----
=772  0\$rReport R1474$tFurnace-type lumber dry-kiln
----

[source,ruby]
----
[
{'type'=>'supplement_to',
 'title'=>'Furnace-type lumber dry-kiln',
 'details'=>'Report number: Report R1474'}
]
----

==== UNCb9013429

[source]
----
=772  1\$6880-01$tBunka jinruigaku$w(DLC)  2005222403$w(OCoLC)55991441
----

[source,ruby]
----
[
{'type'=>'supplement_to',
 'title'=>'Bunka jinruigaku',
 'other_ids'=>['2005222403', '55991441'],
 'display'=>'false'}
]
----

==== UNCb8403445 -- i2=0 (772-specific)

[source]
----
=772  00$aKnowlton, Frank Hall, 1860-1926.$tCatalogue of the Mesozoic and Cenozoic plants of North America$w(OCoLC)670360522
----

[source,ruby]
----
[
{'type'=>'supplement_to',
 'label'=>'Parent item',
 'author'=>'Knowlton, Frank Hall, 1860-1926.',
 'title'=>'Catalogue of the Mesozoic and Cenozoic plants of North America',
 'other_ids'=>['670360522']}
]
----

=== 773 (`type`=host_item)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb2282885 -- display; $i present; $s AND $t present

[source]
----
=773  08$7nnas$iDetached from:$sGentleman's magazine (London, England : 1868)$tGentleman's magazine.$gVol. 12 (Apr. 1874)$w(OCoLC)7898234
----

[source,ruby]
----
[
{'type'=>'host_item',
 'label'=>'Detached from',
 'title'=>'Gentleman\'s magazine (London, England : 1868)',
 'title_variation'=>'Gentleman\'s magazine.',
 'details'=>'Vol. 12 (Apr. 1874)',
 'other_ids'=>['7898234']}
]
----

==== UNCb2282885 mock -- display; $i present; $s AND $t present; $3 + $i `label`

[source]
----
=773  08$7nnas$iDetached from:$sGentleman's magazine (London, England : 1868)$tGentleman's magazine.$gVol. 12 (Apr. 1874)$w(OCoLC)7898234$3pt 1
----

[source,ruby]
----
[
{'type'=>'host_item',
 'label'=>'Pt 1: Detached from',
 'title'=>'Gentleman\'s magazine (London, England : 1868)',
 'title_variation'=>'Gentleman\'s magazine.',
 'details'=>'Vol. 12 (Apr. 1874)',
 'other_ids'=>['7898234']}
]
----

==== UNCb2282885 mock -- display; $i present; $s AND $t present; $3 label

[source]
----
=773  08$7nnas$3pt. 1$sGentleman's magazine (London, England : 1868)$tGentleman's magazine.$gVol. 12 (Apr. 1874)$w(OCoLC)7898234
----

[source,ruby]
----
[
{'type'=>'host_item',
 'label'=>'Pt 1',
 'title'=>'Gentleman's magazine (London, England : 1868)',
 'title_variation'=>'Gentleman's magazine.',
 'details'=>'Vol. 12 (Apr. 1874)',
 'other_ids'=>['7898234']}
]
----

==== UNCb8571581 -- display; $p present; $y present


[source]
----
=773  0\$7c2as$aNational Academy of Sciences (U.S.).$pBiogr. mem.$tBiographical memoirs.$dWashington, National Academy of Sciences, 1938.$g23 cm. vol. XVIII, 7th memoir, 1 p. l., p. 157-174. front. (port)$x0077-2933$yBMNSAC$w(OCoLC)1759017
----

[source,ruby]
----
[
{'type'=>'host_item',
 'author'=>'National Academy of Sciences (U.S.).',
 'title'=>'Biographical memoirs.',
 'title_nonfiling'=>'Biogr. mem.',
 'details'=>'Washington, National Academy of Sciences, 1938. 23 cm. vol. XVIII, 7th memoir, 1 p. l., p. 157-174. front. (port) CODEN: BMNSAC',
 'issn'=>'0077-2933',
 'other_ids'=>['BMNSAC', '1759017']}
]
----

==== UNCb9162338 - do not display

[source]
----
=773  18$tDepartment of Health Behavior and Health Education Master's Papers and Community Diagnosis Projects, 1947-2015.$w(OCoLC)989732850
----

[source,ruby]
----
[
{'type'=>'host_item',
 'title'=>'Department of Health Behavior and Health Education Master\'s Papers and Community Diagnosis Projects, 1947-2015.',
 'other_ids'=>['989732850'],
 'display'=>'false'}
]
----

=== 775  (`type`=alt_edition)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb4827856 - 775 with $i, $s AND $t, no $a

[source]
----
=775  08$iSpanish version:$sIdentity theft and your social security number. Spanish (Online)$tRobo de identidad y su número de seguro social$w(DLC)  2005230022$w(OCoLC)57614487
----

[source,ruby]
----
[
{'type'=>'alt_edition',
 'label'=>'Spanish version',
 'title'=>'Identity theft and your social security number.||Spanish (Online)',
 'title_variation'=>'Robo de identidad y su número de seguro social',
 'other_ids'=>['2005230022', '57614487']}
]
----

==== UNCb7596773 -- $k present

[source]
----
=775  08$iTranslation of:$tRedes femeninas$dRoma : Viella, 2013$kIRCUM-Medieval cultures ; 1$w(OCoLC)830363122
----

[source,ruby]
----
[
{'type'=>'alt_edition',
 'label'=>'Translation of',
 'title'=>'Redes femeninas',
 'details'=>'Roma : Viella, 2013 (IRCUM-Medieval cultures ; 1)',
 'other_ids'=>['830363122']}
]
----

==== UNCb8955588 -- $e (language codes)

[source]
----
=775  0\$tHighlights of the International Transport Forum$x2218-9750$eeng
=775  0\$tWeltverkehrsforum : Forum Höhepunkte$x2218-9777$eger
=775  0\$tFighting Corruption in Transition Economies (Russian version)$x1990-5076$erus
----

[source,ruby]
----
[
{'type'=>'alt_edition',
 'label'=>'English language edition',
 'title'=>'Highlights of the International Transport Forum',
 'issn'=>'2218-9750'},
{'type'=>'alt_edition',
 'label'=>'German language edition',
 'title'=>'Weltverkehrsforum : Forum Höhepunkte',
 'issn'=>'2218-9777'},
 {'type'=>'alt_edition',
 'label'=>'Russian language edition',
 'title'=>'Fighting Corruption in Transition Economies (Russian version)',
 'issn'=>'1990-5076'}
]
----

=== 777 (`type`=issued_with)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb9143546

[source]
----
=777  0\$tCosmetic bench reference$x1069-1448$w(DLC)sn 93007310$w(OCoLC)9883467
----

[source,ruby]
----
[
{'type'=>'issued_with',
 'title'=>'Cosmetic bench reference',
 'issn'=>'1069-1448',
 'other_ids'=>['sn 93007310', '9883467']}
]
----

==== UNCb8954030

[source]
----
=777  08$iCompanion to:$aUniversity of North Carolina at Chapel Hill. Graduate School.$tGraduate school handbook.$w(OCoLC)45129829
----

[source,ruby]
----
[
{'type'=>'issued_with',
 'label'=>'Companion to',
 'author'=>'University of North Carolina at Chapel Hill. Graduate School.',
 'title'=>'Graduate school handbook.',
 'other_ids'=>['45129829']}
]
----

==== UNCb9147108

[source]
----
=777  1\$tBakers digest$w(OCoLC)4974418$gJan.-June 1983
----

[source,ruby]
----
[
{'type'=>'issued_with',
 'title'=>'Bakers digest',
 'other_ids'=>['4974418'],
 'display'=>'false'}
]
----

=== 780 (`type`=earlier)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb3492794 -- display; $i present; $r present

[source]
----
=780  02$iReplacement of (work):$aLudwig, F. L.$tSite selection for the monitoring of photochemical air pollutants.$dResearch Triangle Park, N.C. : U.S. Environmental Protection Agency ; Springfield, Va. : National Technical Information Service [distributor], 1978.$rEPA-450/3-78-013$w(OCoLC)4454556
----

[source,ruby]
----
[
{'type'=>'earlier',
 'label'=>'Replacement of',
 'author'=>'Ludwig, F. L.',
 'title'=>'Site selection for the monitoring of photochemical air pollutants.',
 'details'=>'Research Triangle Park, N.C. : U.S. Environmental Protection Agency ; Springfield, Va. : National Technical Information Service [distributor], 1978. Report number: EPA-450/3-78-013',
 'other_ids'=>['4454556']}
]
----

==== UNCb8262321 -- display; i2=2 but no $i present

[source]
----
=780  02$aVancouver Art Gallery Association.$tVancouver Art Gallery Association annual report.$x0315-4424$w(DLC)cn 77318987$w(OCoLC)3113301
----

[source,ruby]
----
[
{'type'=>'earlier',
 'label'=>'Supersedes',
 'author'=>'Vancouver Art Gallery Association.',
 'title'=>'Vancouver Art Gallery Association annual report.',
 'issn'=>'0315-4424',
 'other_ids'=>['cn 77318987', '3113301']}
]
----

==== UNCb8971570 -- display; i2=4

[source]
----
=780  04$tAlberta English.$dEdmonton, English Language Arts Council of the Alberta Teachers' Association.$x0382-5191$w(DLC)cn 76301138$w(OCoLC)2297987
=780  04$tVoices (Edmonton, Alta.).$d[Edmonton] : English Language Arts Council of the Alberta Teachers' Association, ©1986-2002$x0832-8315$w(CaOONL) 870315102$w(DLC)cn 87031510
----

[source,ruby]
----
[
{'type'=>'earlier',
 'label'=>'Formed by the union of',
 'title'=>'Alberta English.',
 'details'=>'Edmonton, English Language Arts Council of the Alberta Teachers\' Association.',
 'issn'=>'0382-5191',
 'other_ids'=>['cn 76301138', '2297987']},
{'type'=>'earlier',
 'label'=>'Formed by the union of',
 'title'=>'Voices (Edmonton, Alta.).',
 'details'=>'[Edmonton] : English Language Arts Council of the Alberta Teachers\' Association, ©1986-2002',
 'issn'=>'0832-8315',
 'other_ids'=>['870315102', 'cn 87031510']} 
]
----

=== 785 (`type`=later)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb9162399

[source]
----
=785  00$aUnited States.$bAgricultural Stabilization and Conservation Service. Warren County ASCS Office.$tUnion County ASCS ... annual report$w(OCoLC)1028240203
----

[source,ruby]
----
[
{'type'=>'later',
 'label'=>'Continued by',
 'author'=>'United States. Agricultural Stabilization and Conservation Service. Warren County ASCS Office.',
 'title'=>'Union County ASCS ... annual report',
 'other_ids'=>['1028240203']}
]
----

==== UNCb9167128 -- not displayed (display handled by 580)

[source]
----
=785  17$tActa pathologica, microbiologica et immunologica Scandinavica. Section B, Microbiology$x0108-0180$w(DLC)sc 82005096$w(OCoLC)8246434
=785  17$tActa pathologica, microbiologica et immunologica Scandinavica. Section C, Immunology$x0108-0202$w(DLC)sc 82005097$w(OCoLC)8276661
=785  17$tAPMIS$x0903-4641$w(DLC)sn 88026537$w(OCoLC)17476618
----

[source,ruby]
----
[
{'type'=>'later',
 'title'=>'Acta pathologica, microbiologica et immunologica Scandinavica. Section B, Microbiology',
 'issn'=>'0108-0180',
 'other_ids'=>['sc 82005096', '8246434'],
 'display'=>'false'},
{'type'=>'later',
 'title'=>'Acta pathologica, microbiologica et immunologica Scandinavica. Section C, Immunology',
 'issn'=>'0108-0202',
 'other_ids'=>['sc 82005097', '8276661'],
 'display'=>'false'}
{'type'=>'later',
 'title'=>'APMIS',
 'issn'=>'0903-4641',
 'other_ids'=>['sn 88026537', '17476618'],
 'display'=>'false'}
 ]
----

=== 786 (`type`=data_source)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb6869637 mock

[source]
----
=786  0\$tAustralian plant name index.$d[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium$vData for inclusion in initial database at launch$w(DLC)  2009252503$w(OCoLC)64343431
----

[source,ruby]
----
[
{'type'=>'data_source',
 'title'=>'Australian plant name index.',
 'details'=>'[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium Contributed: Data for inclusion in initial database at launch',
 'other_ids'=>['2009252503', '64343431']}
]
----

=== 787 (`type`=related)

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb1808070 - $u present

[source]
----
=787  0\$aRush, James E.$tTechnical report on development of non-roman alphabet capability for library processes$uOCLC/DD/TR-80/4$w6081468$gFebruary 29, 1980
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Rush, James E.',
 'title'=>'Technical report on development of non-roman alphabet capability for library processes',
 'details'=>'Techical report number: OCLC/DD/TR-80/4 February 29, 1980',
 'other_ids'=>['6081468']}
]
----

==== UNCb1448729 -- `display`=false, $y present

[source]
----
=787  1\$tJournal of chemical research. Synopses$x0308-2342$yJRPSDC
----

[source,ruby]
----
[
{'type'=>'related',
 'title'=>'Journal of chemical research. Synopses',
 'issn'=>'0308-2342',
 'other_ids'=>['JRPSDC'],
 'display'=>'false'}
]
----

==== UNCb5305354 -- display=false, $r present

[source]
----
=787  1\$7p1am$aRosenau, William.$tSubversion and insurgency : RAND counterinsurgency study--paper 2$rRAND/OP-172-OSD
----

[source,ruby]
----
[
{'type'=>'related',
 'author'=>'Rosenau, William.',
 'title'=>'Subversion and insurgency : RAND counterinsurgency study--paper 2',
 'other_ids'=>['RAND/OP-172-OSD'],
 'display'=>'false'}
]
----
