:toc:
:toc-placement!:

= `related_work` field

"Authorized access point" (or approximation thereof) for *work related to the resource described by the catalog record*

*Uses the https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_work_entry.adoc[`work_entry` Argot pattern]*

toc::[]

== Data sources

* 700, 710, or 711 with ind2!=2 and $t or $k present
** Label specifying type of relationship from $i if present
* 730 with ind2!=2 (will not include author elements)
** Label specifying type of relationship from $i if present
* 740 with ind2!=2 (will not include author elements)
* Any of the following fields having a $t or $s (may or may not include author elements), where label specifying type of relationship from $i if present
** 765
** 767
** 770
** 772
** 773
** 775
** 777
** 780
** 785
** 786
** 787

== Processing notes

* Segment/subfield delimiter '||' is provided in title portion to facilitate adaptive hyperlinking
* `display` = defaults to true (so it doesn't need to be set explicitly)
* `type` = varies by source MARC field, as shown in table below

[cols=2*,options=header]
|===
|Source MARC
|`type` value

|700
|related

|710
|related

|711
|related

|730
|related

|740
|related

|765
|translation

|767
|translated

|770
|has_supplement

|772
|supplement_parent

|773
|parent

|775
|edition

|777
|issued_with

|780
|earlier

|785
|later

|786
|data_source

|787
|related
|===

== Examples (parallel with `included_work`)
The examples in the section below demonstrate how, for these fields, the processing for `related_work` is nearly identical to that for `included_work`.

The differences are:

* In the MARC, the i2 here is blank instead of 2
* In the Argot, `type` is 'related' instead of 'included'


=== 700

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X00.adoc[general spec on processing X00 fields]

==== UNCb5976398 mock -- omit relator code

[source]
----
=700  1\$aSaint-Saëns, Camille,$d1835-1921.$4cmp$tQuartets,$mviolins (2), viola, cello,$nno. 2, op. 153,$rG major
----

[source]
----
[
  {'type'=>'related',
   'author'=>'Saint-Saëns, Camille, 1835-1921.',
   'title'=>'Quartets,||violins (2), viola, cello,||no. 2, op. 153,||G major'}
]
----

==== UNCb8630424 mock -- omit relator term

$e is preceded by ', ' and ends with a period signifying the end of the author name segment.

We want to remove the comma that precedes a $e, but keep or provide a period at the end of the author segment.

[source]
----
=700  1\$aSchwenkel, Christina,$eauthor.$tArchitecture and dwelling in the 'war of destruction' in Vietnam.
----

[source]
----
[
{'type'=>'related',
 'author'=>'Schwenkel, Christina.',
 'title'=>'Architecture and dwelling in the \'war of destruction\' in Vietnam.'}
]
----

==== UNCb8069067 mock -- `label` from $i; `details` from $g

[source]
----
=700  1\$iFacsimile of:$aFerrini, Vincent,$d1913-2007.$tTidal wave : poems of the great strikes.$f1945$g(New York : Great-Concord Publishers)
----

[source]
----
[
{'type'=>'related',
 'label'=>'Facsimile of',
 'author'=>'Ferrini, Vincent, 1913-2007.',
 'title'=>'Tidal wave : poems of the great strikes.||1945',
 'details'=>'(New York : Great-Concord Publishers)'}
]
----


*Display*

*Related items:*

* Facsimile of: http://query.info/on_author[Ferrini, Vincent, 1913-2007.] http://query.info/on_title[Tidal wave : poems of the great strikes.] http://query.info/on_title_to_left_plus[1945] (New York : Great-Concord Publishers)


*Indexed as*

`related_author`: Ferrini, Vincent, 1913-2007.

`related_title`: Tidal wave : poems of the great strikes. 1945

`related_work`: Ferrini, Vincent, 1913-2007. Tidal wave : poems of the great strikes. 1945


==== UNCb7416515 mock -- label from $3 and $i; special $i processing

See sections of https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_subfield_i.adoc[$i spec] related to deleting WEMI terms and RDA terminology replacements.

[source]
----
=700  0\$3Tome 1, volume 1$iContainer of (expression):$aPlotinus.$tPeri tou kalou.$lFrench$s(Achard and Narbonne)
----

[source]
----
[
{'type'=>'related',
 'label'=>'Tome 1, volume 1: Contains',
 'author'=>'Plotinus.',
 'title'=>'Peri tou kalou.||French||(Achard and Narbonne)'}
]
----

==== UNC mock -- $g as part of `author`

[source]
----
=700  1\$aName, Author,$g(Test name),$d1944-.$tTest title.
----

[source]
----
[
{'type'=>'related',
 'author'=>'Name, Author, (Test name), 1944-.',
 'title'=>'Test title.'}
]
----

=== 710

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X10.adoc[general spec on processing X10 fields]

==== UNCb1619280 mock -- no $t, but has $k

[source]
----
=710  2\$aKungliga Biblioteket (Sweden).$kManuscript.$nKB787a.$lChurch Slavic.$f1966.
----

[source]
----
[
{'type'=>'related',
 'author'=>'Kungliga Biblioteket (Sweden).',
 'title'=>'Manuscript.||KB787a.||Church Slavic.||1966.'}
]
----

==== UNCb1616558 mock -- $n, $d part of `author`

[source]
----
=710  1\$aUnited States.$bCongress$n(94th, 2nd session :$d1976).$tMemorial services held in the House of Representatives and Senate of the United States, together with remarks presented in eulogy of Jerry L. Litton, late a Representative from Missouri.$f197.
----

[source]
----
[
{'type'=>'related',
 'author'=>'United States. Congress (94th, 2nd session : 1976).',
 'title'=>'Memorial services held in the House of Representatives and Senate of the United States, together with remarks presented in eulogy of Jerry L. Litton, late a Representative from Missouri.||197.'}
]
----

==== UNCb1298659 mock -- $n part of `title` 

[source]
----
=710  1\$aNorth Carolina.$bBuilding Code Council.$tNorth Carolina state building code.$n1,$pGeneral construction.$n11X,$pMaking buildings and facilities accessible to and usable by the physically handicapped.
----

[source]
----
[
{'type'=>'related',
 'author'=>'North Carolina. Building Code Council.',
 'title'=>'North Carolina state building code.||1,||General construction.||11X,||Making buildings and facilities accessible to and usable by the physically handicapped.'}
]
----

==== UNCb2383742

[source]
----
=710  1\$aGermany (East).$tTreaties, etc.$gGermany (West),$d1990 May 18.$f1990.
----

[source]
----
[
{'type'=>'related',
 'author'=>'Germany (East).',
 'title'=>'Treaties, etc.||Germany (West),||1990 May 18.||1990.'}
]
----

==== UNCb4364438 mock -- has $4

[source]
----
=710  2\$aCafé Tacuba (Musical group)$4prf$t12/12
----

[source]
----
[
{'type'=>'related',
 'author'=>'Café Tacuba (Musical group)',
 'title'=>'12/12'}
]
----

=== 711

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X11.adoc[general spec on processing X11 fields]

==== UNCb6256550 mock -- $e kept; $d before $t or k
[source]
----
=711  2\$aGreat Central Fair for the U.S. Sanitary Commission$d(1864 :$cPhiladelphia, Pa.).$eCommittee on Public Charities and Benevolent Institutions.$tPhiladelphia [blank] 1864. 619 Walnut Street. To [blank] ...
----

[source]
----
[
{'type'=>'related',
 'author'=>'Great Central Fair for the U.S. Sanitary Commission (1864 : Philadelphia, Pa.). Committee on Public Charities and Benevolent Institutions.',
 'title'=>'Philadelphia [blank] 1864. 619 Walnut Street. To [blank] ...'}
]
----

==== UNCb1099159 mock -- $d and $g after $t; $x

[source]
----
=711  2\$aDeutsch Foundation Conference$d(1930 :$cUniversity of Chicago).$tCare of the aged.$d2000, $f1972.$gReprint.$x1234-1234
----

[source]
----
[
{'type'=>'related',
 'author'=>'Deutsch Foundation Conference (1930 : University of Chicago).',
 'title'=>'Care of the aged.||2000,||1972.',
 'details'=>'Reprint.',
 'issn'=>'1234-1234'}
]
----

=== 730

==== UNCb7339540 mock -- $x

[source]
----
=730  0\$aCahiers de civilisation médiévale.$pBibliographie.$x0240-8678
----

[source]
----
[
{'type'=>'related',
 'title'=>'Cahiers de civilisation médiévale.||Bibliographie.',
 'issn'=>'0240-8678'}
]
----

==== UNCb4873545 mock -- $a and $t in field

[source]
----
=730  0\$aJane Pickering's lute book.$tDrewries Accord's;$oarr.
----

[source]
----
[
{'type'=>'related',
 'title'=>'Jane Pickering\'s lute book.||arr.',
 'title_variation'=>'Drewries Accord\'s;'}
]
----


==== UNCb7055039 mock -- i1 not blank or 0

[source]
----
=730  0\$iContains (expression):$aMagnificent Ambersons (Motion picture).$lSpanish.
=730  4\$iContains (expression):$aThe magnificent Ambersons (Motion picture).$lEnglish.
----

[source]
----
[
{'type'=>'related',
 'label'=>'Contains',
 'title'=>'Magnificent Ambersons (Motion picture).||Spanish.'},
 {'type'=>'related',
 'label'=>'Contains',
 'title'=>'Magnificent Ambersons (Motion picture).||English.',
 'title_nonfiling'=>'The magnificent Ambersons (Motion picture). English.'}
]
----

==== UNCb7644390 mock -- both $3 and $i in label

[source]
----
=730  0\$3Guide:$iBased on (expression):$aDeutsche Geschichte.$nBand 6.
----

[source]
----
[
{'type'=>'related',
 'label'=>'Guide: Based on',
 'title'=>'Deutsche Geschichte.||Band 6.'}
]
----

=== 740

==== UNCb7182040 mock -- i1 not blank or 0

[source]
----
=740  4\$aThe English pilot.$nThe fourth book : describing the West India navigation, from Hudson's-Bay to the river Amazones ...
----

[source]
----
[
{'type'=>'related',
 'title'=>'English pilot.||The fourth book : describing the West India navigation, from Hudson\'s-Bay to the river Amazones ...',
 'title_nonfiling'=>'The English pilot. The fourth book : describing the West India navigation, from Hudson\'s-Bay to the river Amazones ...'}
]
----

==== UNCb1094156

[source]
----
=740  \\$aIndustrial sales management game$p5.
----

[source]
----
[
{'type'=>'related',
 'title'=>'Industrial sales management game||5.'}
]
----

= IGNORE THE CONTENT BELOW THIS LINE
It is from older documentation and contains some good examples, but they need to be worked into the approach we decided to use.

=== UNCb8843477 - 710 with $i
==== MARC
 100 1 _ $aJacobson, Sidney,$eauthor.
 245 1 4 $aThe torture report :$ba graphic adaptation /$cSid Jacobson and Ernie Colón ; introduction by Jane Mayer ; afterword by Scott Horton.
 710 1 _ $iGraphic novelization of (work):$aUnited States.$bCongress.$bSenate.$bSelect Committee on Intelligence.$tSenate Intelligence Committee report on torture.

==== Argot
[source,javascript]
----
{
 "related_name_title": {
  "label": "Graphic novelization of:",
  "author": "United States. Congress. Senate. Select Committee on Intelligence.",
  "title": "Senate Intelligence Committee report on torture."
 }
}
----

==== Behavior

*Displayed:*

RELATED ITEMS:

Graphic novelization of: http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=United%20States.%20Congress.%20Senate.%20Select%20Committee%20on%20Intelligence.&N=0[United States. Congress. Senate. Select Committee on Intelligence.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Senate%20Intelligence%20Committee%20report%20on%20torture.|United%20States.%20Congress.%20Senate.%20Select%20Committee%20on%20Intelligence.&N=0[Senate Intelligence Committee report on torture.]
  


*Combined `name_title_idx_related` index entry for intracatalog linking (and autosuggest?):*

- United States. Congress. Senate. Select Committee on Intelligence. Senate Intelligence Committee report on torture.

*`author_related_idx` index entry:*

- United States. Congress. Senate. Select Committee on Intelligence.

*`title_related_idx` index entry:*

- Senate Intelligence Committee report on torture.

=== UNCb8843477 - 711 without label
==== MARC
 100 1 _ $aEmerson, Joseph,$d1777-1833.
 245 1 4 $aThe Evangelical primer$h[microform].
 711 2 _ $aWestminster Assembly$d(1643-1652).$tShorter catechism.$f1809.

==== Argot
[source,javascript]
----
{
 "related_name_title": [
 {
  "author": "Westminster Assembly (1643-1652).",
  "title": "Shorter catechism.||1809."
 }
 ]
}
----

==== Behavior
*Displayed:*

RELATED ITEMS:

- http://search.trln.org/search?Nty=1&Ntk=Author&Ntt=Westminster%20Assembly%20(1643-1652).&N=0[Westminster Assembly (1643-1652).] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Shorter%20catechism.|Westminster%20Assembly%20(1643-1652).&N=0[Shorter catechism.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Shorter%20catechism.%201809.|Westminster%20Assembly%20(1643-1652).&N=0[1809.]
  
*Combined `name_title_idx_related` index entry for intracatalog linking (and autosuggest?):*

- Westminster Assembly (1643-1652). Shorter catechism. 1809.

*`author_related_idx` index entry:*

- Westminster Assembly (1643-1652).

*`title_related_idx` index entry:*

- Shorter catechism. 1809.

=== UNCb4914240 - 710 with $g in title
==== MARC
 245 0 0 $aRecueil de pièces de luth en tablature italienne ;$bXVIIe siècle.
 500 _ _ $aFacsimile of Bibliothèque du Conservatoir Royal de Musique de Bruxelles, Ms. 16.662 -16.663.
 710 2 _ $iFacsimilie of (manifestation):$aConservatoire royal de musique de Bruxelles.$bBibliothèque.$kManuscript.$g16.662.
 710 2 _ $iFacsimilie of (manifestation):$aConservatoire royal de musique de Bruxelles.$bBibliothèque.$kManuscript.$g16.663.

==== Argot
[source,javascript]
----
{
 "related_name_title": [
 {
  "label": "Facsimilie of:",
  "author": "Conservatoire royal de musique de Bruxelles. Bibliothèque.",
  "title": "Manuscript.||16.662."
 },
 {
  "label": "Facsimilie of:",
  "author": "Conservatoire royal de musique de Bruxelles. Bibliothèque.",
  "title": "Manuscript.||16.663."
 }
 ]
}
----

==== Behavior
*Displayed:*

RELATED ITEMS:

- Facsimilie of: http://search.trln.org/search?Nty=1&Ne=2+200043+206472+210899+210956&N=0&Ntk=Author&Ntt=Conservatoire%20royal%20de%20musique%20de%20Bruxelles.%20Biblioth%C3%A8que[Conservatoire royal de musique de Bruxelles. Bibliothèque.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Manuscript.|Conservatoire%20royal%20de%20musique%20de%20Bruxelles.%20Biblioth%C3%A8que&N=0[Manuscript.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Manuscript.%2016.662.|Conservatoire%20royal%20de%20musique%20de%20Bruxelles.%20Biblioth%C3%A8que&N=0[16.662.]
- Facsimilie of: http://search.trln.org/search?Nty=1&Ne=2+200043+206472+210899+210956&N=0&Ntk=Author&Ntt=Conservatoire%20royal%20de%20musique%20de%20Bruxelles.%20Biblioth%C3%A8que[Conservatoire royal de musique de Bruxelles. Bibliothèque.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Manuscript.|Conservatoire%20royal%20de%20musique%20de%20Bruxelles.%20Biblioth%C3%A8que&N=0[Manuscript.] http://search.trln.org/search?Nty=1&Ntk=Title|Author&Ntt=Manuscript.%2016.663.|Conservatoire%20royal%20de%20musique%20de%20Bruxelles.%20Biblioth%C3%A8que&N=0[16.663.]
  
*Combined `name_title_idx_related` index entry for intracatalog linking (and autosuggest?):*

- Conservatoire royal de musique de Bruxelles. Bibliothèque. Manuscript. 16.662.
- Conservatoire royal de musique de Bruxelles. Bibliothèque. Manuscript. 16.663.

*`author_related_idx` index entry:*

- Conservatoire royal de musique de Bruxelles. Bibliothèque.

*`title_related_idx` index entry:*

- Manuscript. 16.662.
- Manuscript. 16.663.

=== 770
==== MARC
 210 0 _ $aAm. econ. rev.
 222 _ 4 $aThe American economic review
 245 0 4 $aThe American economic review$h[serial].
 500 _ _ $aEach vol. includes also: Papers and proceedings of the ... Annual Meeting of the American Economic Association.
 515 _ _ $aVol. 1 called also Bulletin of the American Economic Association, 4th series.
 515 _ _ $aThe American economic review, with its supplements, forms the 4th series of the Publications of the American Economic Association.
 525 _ _ $aHas frequent supplements.
 730 0 _ $aBulletin of the American Economic Association.
 770 0 _ $aAmerican Economic Association.$tPapers and proceedings of the annual meeting$g1911-$x0065-812X$w(DLC)   01011768$w(OCoLC)1479792
 776 0 8 $iOnline version$tAmerican economic review (Online)$x1944-7981$w(DLC)sn 97023013$w(OCoLC)35705012
 776 0 8 $iOnline version:$tAmerican economic review$w(OCoLC)565226305
 777 0 _ $aAmerican Economic Association.$tPapers and proceedings of the annual meeting$x0065-812X$w(DLC)   01011768$w(OCoLC)1479792
 780 0 4 $tEconomic bulletin (Baltimore, Md.)$x1536-1489$w(DLC)   09025911$w(OCoLC)1567381
 780 0 4 $tAmerican Economic Association quarterly$x1532-5059$w(DLC)sn 91026538$w(OCoLC)6483348

=== 772
=== 765
=== 767
=== 773
=== UNCb4827856 - 775 with $i and $s, no $a
==== MARC
 130 0 _ $aIdentity theft and your social security number (Online)
 245 1 0 $aIdentity theft and your social security number$h[electronic resource].
 580 _ _ $aIssued also in Spanish.
 580 _ _ $aReports in several languages available via the SSA multilanguage gateway.
 775 0 8 $iSpanish version:$sIdentity theft and your social security number. Spanish (Online)$tRobo de identidad y su número de seguro social$w(DLC)  2005230022$w(OCoLC)57614487
 775 0 8 $iOther language versions:$tIdentity theft and your social security number (Online)$w(DLC)  2006230527$w(OCoLC)64391649$w(DLC)  2006230517$w(OCoLC)64201706$w(DLC)  2006230627$w(OCoLC)64560561$w(DLC)  2006230601$w(OCoLC)64402658$w(DLC)  2006230673$w(OCoLC)65181174$w(DLC)  2006230683$w(OCoLC)65189576$w(DLC)  2006230449$w(OCoLC)63761026

=== 787

=== UNCb6869637 - 740 and 786, somewhat duplicated data
Because of system limitations for displaying MARC 76X-78X (Linking Entries), the data recorded in 'linking fields' is often duplicated in other fields.

*Ideally we could figure out some way to minimize display of duplicated data.* One idea for this could be:

- Once `related_title` has been completely populated, identify the entries where the `title` element is a duplicate (maybe stripping off terminal punctuation to do some vague normalization)
- Keep entries with duplicate `title` if they have `label`, but the `label` values differ
- Prefer entry with a `label` value if some entries with duplicate `title` lack a `label` value
- If there are multiple entries with duplicate `label` + `title` (`title` with no `label`), prefer the one with more other info

==== MARC
 245 0 4 $aThe international plant names index$h[electronic resource].
 500 _ _ $a"The records in IPNI come from three sources: the Index Kewensis (IK), the Gray Card Index (GCI) and the Australian Plant Names Index (APNI)." --"About the index" page (viewed Nov. 10, 2011).
 740 0 _ $aIndex Kewensis.
 740 0 _ $aGray card index.
 740 0 _ $aAustralian plant name index.
 786 0 _ $tAustralian plant name index.$d[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium$w(DLC)  2009252503$w(OCoLC)64343431
 786 0 _ $tIndex Kewensis plantarum phanerogamarum. Supplementum$w(DLC)   89659069$w(OCoLC)2992677
 786 0 _ $tIndex Kewensis. Supplement$w(DLC)sn 88021550$w(OCoLC)16733857
 786 0 _ $tGray card index.$dCambridge, Mass. : Harvard University Herbraria, [c1992-]$w(OCoLC)43851144

==== Argot (without deduplication)
[source,javascript]
----
{
 "related_title": [
  {"title": "Index Kewensis."},
  {"title": "Gray card index."},
  {"title": "Australian plant name index."},
 {
  "label": "Data source:",
  "title": "Australian plant name index.",
  "details": "[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium"
 },
 {
  "label": "Data source:",
  "title": "Index Kewensis plantarum phanerogamarum. Supplementum"
 },
  {
  "label": "Data source:",
  "title": "Index Kewensis. Supplement"
 },
 {
  "label": "Data source:",
  "title": "Gray card index.",
  "details": "Cambridge, Mass. : Harvard University Herbraria, [c1992-]"
 }
 ]
}
----

==== Argot (ideal, deduplicated)
[source,javascript]
----
{
 "related_title": [
 {"title": "Index Kewensis."},
 {
  "label": "Data source:",
  "title": "Australian plant name index.",
  "details": "[Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium"
 },
 {
  "label": "Data source:",
  "title": "Index Kewensis plantarum phanerogamarum. Supplementum"
 },
  {
  "label": "Data source:",
  "title": "Index Kewensis. Supplement"
 },
 {
  "label": "Data source:",
  "title": "Gray card index.",
  "details": "Cambridge, Mass. : Harvard University Herbraria, [c1992-]"
 }
 ]
}
----

==== Behavior (based on deduplicated Argot)
*Displayed:*

RELATED ITEMS:

- http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Index%20Kewensis.&N=0[Index Kewensis.]
- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Australian%20plant%20name%20index.&N=0[Australian plant name index.] [Canberra, A.C.T.] : Australian National Botanic Gardens : Australian National Herbarium
- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Index%20Kewensis%20plantarum%20phanerogamarum.%20Supplementum&N=0[Index Kewensis plantarum phanerogamarum. Supplementum]
- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Index%20Kewensis.%20Supplement&N=0[Index Kewensis. Supplement]
- Data source: http://search.trln.org/search?Nty=1&Ntk=Title&Ntt=Gray%20card%20index.&N=0[Gray card index.] Cambridge, Mass. : Harvard University Herbraria, [c1992-]
  

*`title_related_idx` index entry:*

- Australian plant name index.
- Index Kewensis plantarum phanerogamarum. Supplementum
- Index Kewensis. Supplement
- Gray card index.
- Index Kewensis.


=== linking field not for display

== Field-specific processing notes
=== 770
- Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/76X-78X_linking_entry_processing.adoc[76X-78X linking entry processing procedures].
- If no $i, `label`  =  `Is supplemented by:`

=== 786
- Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/76X-78X_linking_entry_processing.adoc[76X-78X linking entry processing procedures].
- If no $i, `label`  =  `Data source:`

