:toc:
:toc-placement!:

= `series_work` field

"Authorized access point" (or approximation thereof) for *consistent/controlled form of series title* -- facilitates collocation/retrieval of all volumes in the series together.

*Uses the https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_work_entry.adoc[`work_entry` Argot pattern]*

toc::[]


== Processing notes

* Segment/subfield delimiter '||' is provided in title portion to facilitate adaptive hyperlinking
* For all source MARC fields except 762: `type` = series
* For source MARC field 762: `type` = subseries
* `display` = defaults to true (so it doesn't need to be set explicitly)
* Remove semicolon (and any padding spaces) at the end of `title` value

== Examples

=== 800

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X00.adoc[general spec on processing X00 fields]

==== UNCb4446219

[source]
----
=800  1\$aShakespeare, William,$d1564-1616.$tWorks.$kSelections.$f1880 ;$vno. 23-24.
----

[source,ruby]
----
[
  {'type'=>'series',
   'author'=>'Shakespeare, William, 1564-1616.',
   'title'=>'Works.||Selections.||1880',
   'details'=>'no. 23-24.'}
]
----

==== UNCb2908427 -- drop relator terms/codes

[source]
----
=800  1\$aEllington, Duke,$d1899-1974.$4prf$tPrivate collection ;$vv. 6
----

[source,ruby]
----
[
  {'type'=>'series',
   'author'=>'Ellington, Duke, 1899-1974.',
   'title'=>'Private collection',
   'details'=>'v. 6'}
]
----

==== UNCb3054298 -- $g as part of `title`

[source]
----
=800  1\$aField, John,$d1782-1837.$tConcertos,$mpiano, orchestra.$gChandos Records (Firm) ;$vv. 4.
----

[source,ruby]
----
[
  {'type'=>'series',
   'author'=>'Field, John, 1782-1837.',
   'title'=>'Concertos,||piano, orchestra.||Chandos Records (Firm)',
   'details'=>'v. 4.'}
]
----

=== 810

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X10.adoc[general spec on processing X10 fields]

==== UNCb5204637 -- $x present

[source]
----
=810  2\$aCanadian Mathematical Society.$x1613-5237
----

[source,ruby]
----
[
  {'type'=>'series',
   'title'=>'Canadian Mathematical Society.',
   'issn'=>'1613-5237'}
]
----

==== UNCb5204637 -- $x present

[source]
----
=810  2\$aCanadian Mathematical Society.$x1613-5237
----

[source,ruby]
----
[
  {'type'=>'series',
   'title'=>'Canadian Mathematical Society.',
   'issn'=>'1613-5237'}
]
----

=== 811

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X11.adoc[general spec on processing X11 fields]

==== UNCb4383310

[source]
----
=811  2\$aWorld Conference on Faith and Order.$eContinuation Committee.$tPamphlets published by the Continuation Committee ;$v33-103.
----

[source,ruby]
----
[
  {'type'=>'series',
   'author'=>'World Conference on Faith and Order. Continuation Committee.',
   'title'=>'Pamphlets published by the Continuation Committee',
   'details'=>'33-103.'}
]
----

==== UNCb8460056

[source]
----
=811  2\$aGoing Romance (Conference).$tRomance languages and linguistic theory ;$vv. 9.$x1574-552X.
----

[source,ruby]
----
[
  {'type'=>'series',
   'author'=>'Going Romance (Conference).',
   'title'=>'Romance languages and linguistic theory',
   'details'=>'v. 9.',
   'issn'=>'1574-552X'}
]
----

==== UNCb9178008 -- do not output

[source]
----
=830  \0$aTaiwan Resource Center for Chinese Studies at UW-EAL.$5WaU
----

*NO ARGOT OUTPUT* -- non-whitelisted $5 value

=== 830

See https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_field_X30.adoc[general spec on processing X30 fields]


==== UNCb3086182 -- Interpret i2=blank as i2=0.

[source]
----
=830  1\$aPolicy, research, and external affairs working papers ;$vWPS 702.
----

[source,ruby]
----
[
  {'type'=>'series',
   'title'=>'Policy, research, and external affairs working papers',
   'details'=>'WPS 702.'}
]
----

==== UNCb9155383 -- respect non-filing character indicator

[source]
----
=830  \4$aThe Handbook of Environmental Chemistry,$x1867-979X ;$v65.
----

[source,ruby]
----
[
  {'type'=>'series',
   'title'=>'Handbook of Environmental Chemistry,',
   'title_nonfiling'=>'The Handbook of Environmental Chemistry,',
   'issn'=>'1867-979X',
   'details'=>'65.'}
]
----

==== UNCb6040789 -- label from $3

[source]
----
=830  \0$aHouse document (United States. Congress. House)$31920-1922
=830  \0$aEx. doc. (United States. Congress. House)$31871, 1886
=830  \0$aDepartment of State publication.$31922-1931
----

[source,ruby]
----
[
  {'type'=>'series',
   'label'=>'1920-1922',
   'title'=>'House document (United States. Congress. House)'},
  {'type'=>'series',
   'label'=>'1871, 1886',
   'title'=>'Ex. doc. (United States. Congress. House)'},
  {'type'=>'series',
   'label'=>'1922-1931',
   'title'=>'Department of State publication.'}
]
----

==== UNCb4205105 -- $a and $t present

[source]
----
=830  \0$aBiblical seminar ;$v86.$tLost coin.
----

[source,ruby]
----
[
  {'type'=>'series',
   'title'=>'Biblical seminar',
   'title_variation'=>'Lost coin.',
   'details'=>'86.'}
]
----

=== 760

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb8799467 mock -- $i label; segment title

[source]
----
=760  08$iSome volumes in main series:$tVital and health statistics. Series 22, Data from the national vital statistics system$x0083-2049$w(DLC)   66060347$w(OCoLC)1768533
----

[source,ruby]
----
[
  {'type'=>'series',
   'label'=>'Some volumes in main series',
   'title'=>'Vital and health statistics.||Series 22, Data from the national vital statistics system',
   'issn'=>'0083-2049',
   'other_ids'=>['66060347', '1768533']}
]
----

==== UNCb7202287 -- author/title

[source]
----
=760  0\$aKazan, Russia (City) Universitet.$tUchenye zapiski,$gt. 128, kn. 4; t. 129, kn. 7.
----

[source,ruby]
----
[
  {'type'=>'series',
   'author'=>'Kazan, Russia (City) Universitet.',
   'title'=>'Uchenye zapiski,',
   'details'=>'t. 128, kn. 4; t. 129, kn. 7.'}
]
----

==== UNCb7335021 -- no display

[source]
----
=760  1\$aFood and Agriculture Organization of the United Nations. Committee on Commodity Problems.$t[Document] CCP$x0426-7877$w(DLC)   65079781$w(OCoLC)1380035
----

[source,ruby]
----
[
  {'type'=>'series',
   'author'=>'Food and Agriculture Organization of the United Nations. Committee on Commodity Problems.',
   'title'=>'[Document] CCP',
   'issn'=>'0426-7877',
   'other_ids'=>['65079781', '1380035'],
   'display'=>'false'}
]
----

=== 762

Refer to https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_linking_entry_fields_76X-78X.adoc for general processing pattern for this field.

==== UNCb7274043 -- subseries

[source]
----
=762  0\$aCullowhee Normal and Industrial School (Cullowhee, N.C.).$tCatalogue number.
=762  0\$aCullowhee Normal and Industrial School (Cullowhee, N.C.).$tSummer school number.
----

[source,ruby]
----
[
  {'type'=>'subseries',
   'author'=>'Cullowhee Normal and Industrial School (Cullowhee, N.C.).',
   'title'=>'Catalogue number.'},
  {'type'=>'subseries',
   'author'=>'Cullowhee Normal and Industrial School (Cullowhee, N.C.).',
   'title'=>'Summer school number.'}
]
----

==== UNCb7470152 -- subseries; do not display

[source]
----
=762  1\$aFrance. Service des études économiques et financières.$tÉtudes de comptabilité nationale$w(OCoLC)6313705
----

[source,ruby]
----
[
  {'type'=>'subseries',
   'author'=>'France. Service des études économiques et financières.',
   'title'=>'Études de comptabilité nationale',
   'other_ids'=>['6313705'],
   'display'=>'false'}
]
----
