:toc:
:toc-placement!:

= Subject and genre-related fields

toc::[]

== Two types of subject and genre fields

Argot has two types of subject/genre fields: headings fields and facet fields.

=== Headings fields

Headings fields include:

* `genre_headings`
* `subject_headings`

These fields:

* Contain the full field data from source data subject fields (MARC 6XX, etc.)
* Are displayed as progressive hyperlinks in the full record view, so clicking a segment of the heading will conduct a query for the heading _up to and including that segment_.
* Are included in the subject search index. User-entered queries will search in these fields. 
** This requires script detection and language parsing when vernacular scripts are present

`subject_headings` fields are displayed in the "This item is about" section of the record display.

[NOTE]
====
*Known issue we can't do anything about:*

In some cases, such as short story collections, LC instructs catalogers to record genre/form in a subject heading (650) field. Because such headings are coded as *subjects*, they will appear under "This item is about" even though they are not really subjects. Here is https://discovery.trln.org/catalog/UNCb5340468[an example].

We didn't have this issue when we lumped subjects and genre/form headings together. However, labeling all genre/form headings as subjects was a much more widespread issue than what we've introduced by actually treating subject headings as though they are subjects.
====

`genre_headings` are currently being displayed as "Genre or form" in the "Other details" section of the record display.

=== Facet fields

Facet fields include:

* `subject_chronological`
* `subject_genre`
* `subject_geographic`
* `subject_topic`

These fields:

* Contain individual subdivision/subfield values from the source data subject fields. That is, a MARC 650 with chronological, geographic, and genre/form subdivisions will have each of its segments assigned to the appropriate facet field.
* Populate the three subject-related facets and the genre facet.
* Are *not* included in the subject search index. User-entered queries will *not* search in these fields.
** Anything in these fields will also be part of a value included in a `subject_headings` or `genre_headings` field, so searching these would be redundant. footnote:[The exception to this statement is the special addition of "Primary Sources" and "Reference" based on certain other facet values as discussed below, and cases where `subject_genre` values are provided based on 008 or 006 coding only.]
** Script detection and language parsing is therefore *not* required when vernacular scripts are present.

== Different subject heading vocabularies

Initially, product owners decided that all subject headings---LCSH, MeSH, and any others present---will be treated the same.

The `subject_headings` fields will contain all headings from all vocabularies, and the TRLN Discovery application will not know anything about the source vocabulary.

There is initially no separate MeSH Subject facet in TRLN Discovery.

This could change in future releases based on stakeholder feedback.

== MARC field-to-Argot field mappings

A few selected mapping examples appear below.

For full details on the MARC-to-Argot mappings, consult the mappings tab of https://github.com/trln/data-documentation/blob/master/argot/argot.xlsx[the Argot specification spreadsheet] or the https://github.com/trln/data-documentation/blob/master/argot/_mappings.csv[mappings .csv derived from it].

=== Explanation of weird 653 handling
In the 653 field, 2nd indicator = 4 means "This is a chronological term"

Thus it'd follow that we map 653 values with 2nd indicator = 4 to the `subject_chronological` facet.

However, we are mapping it to `subject_topical` facet instead. Why?

Because, in almost all other MARC fields from which we take subject data, 2nd indicator = 4 means "We don't know what controlled vocabulary this term came from." And usually 653 terms come from an unidentified vocabulary. And people (and vendors) are sloppy. So we have *way too many* topical 653s coded as chronological, which junks up the chronological subject facet if we try to use the indicator as it is defined.

=== Special handling for `subject_genre`

==== 008 and 006 values

For language materials (coded as such in LDR or an 006), set `subject_genre` based on Literary form (006/16, 008/33) and Biography (006/17, 008/34) codes.

==== Primary sources value

If one or more of the following values is written to the `subject_genre` facet values for a record, "Primary sources" is also added to the `subject_genre` facet values.

* Archival resources
* Archives
* Correspondence
* Diaries
* Interviews
* Interview
* Notebooks, sketchbooks, etc.
* Personal narratives
* Sources
* Speeches, addresses, etc.

==== Reference value

If one or more of the following values is written to the `subject_genre` facet values for a record, "Reference" is also added to the `subject_genre` facet values.

* Bibliography
* Bio-bibliography
* Dictionaries
* Directories
* Encyclopedias
* Handbooks, manuals, etc.
* Handbooks, manuals, etc
* Identification
* Indexes
* Style manuals

== Examples

=== Multi-field
[source]
----
=600  10$aAsperger, Hans.
=650  \0$aAsperger's syndrome in children$xPatients$zAustria$zVienna$xHistory.
=650  \0$aAsperger's syndrome in children$zAustria$zVienna$xDiagnosis$y20th century.
=650  \0$aAsperger's syndrome in children$zAustria$zVienna$xHistory$y20th century.
=650  \7$aMEDICAL / Pediatrics.$2bisacsh
=650  \2$aAsperger Syndrome$xhistory.
=655  \4$aNonfiction.
=655  \7$aNonfiction.$2lcgft
----

[source,ruby]
----
{
"subject_headings" => [
    { "value" => "Asperger, Hans" },
    { "value" => "Asperger's syndrome in children -- Patients -- Austria -- Vienna -- History" },
    { "value" => "Asperger's syndrome in children -- Austria -- Vienna -- Diagnosis -- 20th century" },
    { "value" => "Asperger's syndrome in children -- Austria -- Vienna -- History -- 20th century" },
    { "value" => "MEDICAL / Pediatrics" },
    { "value" => "Asperger Syndrome -- history" }
    ],
  "genre_headings" => [
    { "value" => "Nonfiction" }
  ],
  "subject_genre" => [
    "Nonfiction"
  ],
  "subject_geographic" => [
    "Austria",
    "Vienna"
  ],
  "subject_topical" => [
    "Asperger, Hans",
    "Asperger's syndrome in children",
    "Patients",
    "History",
    "Diagnosis",
    "MEDICAL / Pediatrics",
    "Asperger Syndrome"
  ],
  "subject_chronological" => [
    "20th century"
  ]
}
----

=== UNCb8430921 - non-Roman genre_headings

[source]
----
  <datafield tag='880' ind1=' ' ind2='7'>
    <subfield code='6'>655-10/r</subfield>
    <subfield code='a'>التراجم الذاتية.</subfield>
    <subfield code='2'>qrmak</subfield>
  </datafield>
----

[source,ruby]
----
  "genre_headings" => [
    { "value" => "التراجم الذاتية.",
      "lang" => "ara"}
  ],

----

=== UNCb4591956 - non-Roman subject_headings

[source]
----
=650  07$6880-04$aAn mo liao fa (zhong yi)$vJiao cai$2cct.
=880  07$6650-04/{dollar}1$a按摩疗法(中医)$v教材$2cct.
----

[source,ruby]
----
'subject_headings' => [
  { 'value' => 'An mo liao fa (zhong yi) -- Jiao cai' },
  { 'value' => '按摩疗法(中医) -- 教材',
    'lang' => 'cjk' }
]
----
