:toc:
:toc-placement!:

= Title history fields

*See the https://github.com/trln/data-documentation/tree/master/argot[Argot Excel file available here] or the https://github.com/trln/data-documentation/blob/master/argot/_mappings.csv[mappings.csv file] for field/subfield specific instructions.*

*Test records*
The UNC bib records referred to by bib number in this document are at:
todo

toc::[]



== Argot title history patterns and behavior
The reason for two weirdly named patterns here is based on fact that there are three different cataloging practices related to title change:

* latest entry cataloging (don't make new, separate record when title changes) -- very old legacy practice
* integrated entry cataloging (don't make new, separate record when title changes) -- current practice
* successive entry cataloging (make new, separate record when title changes) -- current practice)

Relevant differences in catalog behavior between these include:

* title history titles recorded in records using latest and integrated entry:
** will always be FORMER titles, and can be labeled as such
** will not retrieve additional/different records if searched as title, so title should not be hyperlinked
** basically, should be treated as a specially labeled variant title of the work described in this record
** are handled by `title_variant` Argot field

* title history titles recorded in records using successive entry:
** may be former or later titles -- need to be labeled as such for display (though former vs. later can be indexed the same -- neither takes relevance preference)
** will retrieve additional/different records if searched as title, so related-work-type hyperlinking should be applied
** basically, should be treated as a subcategory of related works, in terms of behavior and display (because the 580 note that sometimes stands in for display of these fields is not specifically defined for earlier/later titles. It gets used to clarify relationships that cannot be adequately generated from any linking entry fields 760-787.)
** are handled by the Argot `work_entry` pattern of fields described https://github.com/trln/data-documentation/blob/master/argot/spec_docs/_pattern_work_entry.adoc[here].

Both types of fields may be coded to display or not to display.

When coded to not display, there will typically be a note that serves the display purpose.

These fields are always indexed, even when MARC coding specifies not to "make an access point" (which is more related to catalog card printing than indexing rules)
